CHANGES
nipype/interfaces/spm/preprocess.py

I fixed bug reported in http://neurostars.org/p/2768/, wrong prefix in case to execute 'Normalize' with modulation.
I'd appreciate it if you could reflect this change.

Fix bug in Normalize with modulation

---

CHANGES
nipype/interfaces/ants/legacy.py

when generating the _list_outputs if -t RA or -t RI is set, *_warp_field
outputs will not be required

ENH: antsIntroduction handles RA and RI transformations

---

nipype/interfaces/base.py

Fixes #1000
I didn't think this would be so easy.
Note: `full_info` was added to traits in [this commit](https://github.com/enthought/traits/blob/8e298a8770c7efb52b04c8dc08e9ba397c8ad461/enthought/traits/trait_handlers.py#L297) for 3.0.

DOC: Fix input type description in Interface.help()

---

CHANGES
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

As mentionned [here](https://neurostars.org/p/2874/) `split_filename` doesn't work when passing path ending with `'/'`. This PR fixes that.

Fix split filename

---

CHANGES
nipype/pipeline/plugins/base.py

This code was failing to find matplotlib and
the first import was silently continuing, but
then the second call that requires matplotlib
began failing.

BUG: matplotlib is supposed to be optional

---

.gitignore

When running make in the nipype folder, documentation.zip is created. Running git status then shows this as an untracked file.

Git ignore add documentation.zip as ignored

---

CHANGES
nipype/interfaces/ants/__init__.py
nipype/interfaces/ants/base.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/tests/test_JointFusion.py

ENH: ANTs JointFusion wrapping

ENH: ANTs JointFusion with nosetests

---

examples/rsfmri_vol_surface_preprocessing.py
examples/rsfmri_vol_surface_preprocessing_nipy.py

This is a very minor correction, but the example resting state scripts do not correctly specify the variable type for the arguments. This causes issues with negative values. The string "-1" evaluates as true in the ``bandpass_filter`` function on the line ``if lowpass_freq > 0:``, which does not produce the intended effect of suppressing the lowpass filter.
I am happy to write tests for this, although I don't see any tests associated with the example scripts. Let me know if there is anything else I can do to help.

FIX Set type on bandpass frequency arguments.

---

examples/rsfmri_vol_surface_preprocessing.py
examples/rsfmri_vol_surface_preprocessing_nipy.py

The constant column in the motion regressor results in the FSL GLM reporting a SingularMatrix exception. I can not find reference to a constant (intercept) term in the ``fsl_glm`` documentation. It could potentially be a result of the ``--demean`` argument when calling the ``fsl_glm`` command. Do you have any insights into what may be causing this?
For now, I am opening the pull request to start discussion. If this seems like a reasonable fix, I will go through the other steps listed in the "contributing" document.

FIX Constant column in motion regressor causes singular matrix

---

.travis.yml
CHANGES
doc/users/install.rst

Python 2.7 brings argparse and some useful testing functions
(http://stackoverflow.com/questions/17585207/python-unittest-assetraises).
Both debian stable and ubuntu LST come with Python 2.7.

ENH/FIX?: Drop support for Python 2.6

---

nipype/pipeline/plugins/sgegraph.py

During the re-running of a workflow with SGEgraph, we can greatly
reduce the dependancies by determining which nodes have completed
prior to generating the submit-graph.
Job numbers need to be based on job ID's not on job names.  Job names are not unique.
BUG: Job names must be valid bash variables.

ENH: Add support for reduced SGEgraph on re-run

---

CHANGES
nipype/interfaces/io.py

Corrected an issue in which the path to the downloaded files was not returned in full. Hence the pipelines were not working

SSHDataGrabber outputs now returns full path to the grabbed files

---

CHANGES
nipype/interfaces/dcmstack.py
nipype/interfaces/tests/test_auto_DcmStack.py
nipype/interfaces/tests/test_auto_GroupAndStack.py
nipype/interfaces/tests/test_auto_MergeNifti.py
nipype/interfaces/tests/test_auto_SplitNifti.py

Enables absolute path definitions in DCMStack (#1087)

Fix DCMStack output

---

CHANGES

Erroneous lines were introduced by myself in commit df63a28152540ff95e7955403a9dc09f6f6e0876

Fix CHANGES file after commit df63a28152540ff95e7955403a9dc09f6f6e0876

---

nipype/pipeline/plugins/base.py
nipype/pipeline/utils.py
nipype/utils/config.py
nipype/utils/provenance.py

The config module used `os.environ['HOME']` that is often undefined in Windows.
Sevaral places use the `pwd` package to get the login name of the user, but
`pwd` is specific to Unix.
`getpass.getuser()` seems to be a simpler and more general alternative:
http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

MRG: fixes to get Windows tests to run

---

nipype/interfaces/fsl/preprocess.py
nipype/interfaces/fsl/tests/test_preprocess.py

PR #978 broke FUGUE (see #977). This PR reverts back that one, and adds a test to ensure that outputs of interface are actually filled in.
Close #977. 
@bpinsard, could it be that in your pipelines you are trying to get an output that is actually undefined by design of the FUGUE interface?, something like you want to apply the forward warping but look into unwarped_file at the output?

Revert #978 adding tests (see also #977)

---

doc/quickstart.rst
doc/users/tutorial_101.rst

I didn't manage to link the terms to the glossary yet, but it would be good if someone could check whether I got the definitions right - I think a glossary might be helpful for beginners

WIP_adding_glossary_to_tutorial

---

CHANGES
doc/users/config_file.rst
nipype/interfaces/base.py
nipype/utils/config.py

Change to _redirect_x block to allow more wait time for Xvfb if needed. Max wait time could potentially be set in config. Hard coded for now. @chrisfilo, thoughts?

MRG:Allow extra wait time for Xvfb if needed

---

CHANGES
nipype/interfaces/fsl/dti.py

Small bugfix in the FSLXCommand _list_outputs function

FIX: Bug in _list_outputs function

---

nipype/algorithms/mesh.py
nipype/interfaces/base.py
requirements.txt

This PR fixes #1155. Additionally, ```CommandLineInterface``` has been also modified to be run with the ```xvfb-run``` script.
- Two tests checking 1) BaseInterface redirection, and 2) CommandLineInterface after this change.
- The code may  fail when running many BaseInterfaces at the same time, but at least the workflow doesn't fail.
Question: maybe the approach should be opening just one virtual display and redirecting all the nodes with redirect_x in the host to that display. What do you think? Currently, a lot of new virtual displays need to be open, but only one per host is enough.

[FIX] Improve redirections of X

---

nipype/interfaces/ants/segmentation.py

Adding an interface for the ANTs based JointFusion program.
Added _format_xarray() method to ANTSCommand base class

ENH: Add ants JointFusion() node with testing

---

nipype/pipeline/plugins/sge.py

PEP8 Correction. Typo and function definition cleanup. Hopefully cut down on number of qstat/qacct calls.

MRG: Updates to SGE Plugins

---

CHANGES
doc/users/config_file.rst
nipype/interfaces/io.py
nipype/utils/config.py
nipype/utils/filemanip.py

In many cases on Unix, the data sink is on the same
physical drive as the internal nipype cache.  In
that case, we can use a hard link to save both
time necessary to duplicate data, and space
necesssary to hold the same data at two different
inodes.  This allows removal of the cache
directory without modifying the results
directory.
In large analysis, this optimization can save
several terabytes of storage consumption.

ENH: Attempt to use hard links for data sink.

---

CHANGES
nipype/interfaces/fsl/dti.py
nipype/interfaces/fsl/tests/test_auto_BEDPOSTX5.py
nipype/interfaces/fsl/tests/test_auto_FSLXCommand.py
nipype/interfaces/fsl/tests/test_auto_XFibres5.py

Fixes this minor but blocking bug

[FIX] XFibres5 fails in _list_outputs if n_fibres is undefined

---

CHANGES
nipype/interfaces/ants/registration.py

Registration interface was failing to support
multimodal input when they are given.
ex)
nipype:
antsWF.inputs.fixed_image=['fixed_t1.nii.gz',
'fixed_t2.nii.gz']
antsWF.inputs.moving_image=['moving_t1.nii.gz',
'moving_t2.nii.gz']
corresponding correct commandline:
--metric MI[\
fixed_t1.nii.gz,\
moving_t1.nii.gz,\ ...
--metric MI[\
fixed_t2.nii.gz,\
moving_t2.nii.gz,\ ...
Reported in issue: https://github.com/nipy/nipype/issues/1175

BUG: Registration interface failed multi-modal

---

CHANGES
nipype/interfaces/ants/registration.py

Reverts nipy/nipype#1176
@hjmjohnson, @chrisfilo - reverting this change - breaks nipype.

Revert "BUG: Registration interface failed multi-modal"

---

nipype/interfaces/ants/registration.py

@hjmjohnson please add (not replace) multimodal doctests along with the corrected multimodal PR

Current ANTS doctests are only valid for unimodal registrations

---

CHANGES
nipype/interfaces/ants/registration.py

Registration interface was failing to support
multimodal input when they are given.
ex)
nipype:
antsWF.inputs.fixed_image=['fixed_t1.nii.gz',
'fixed_t2.nii.gz']
antsWF.inputs.moving_image=['moving_t1.nii.gz',
'moving_t2.nii.gz']
corresponding correct commandline:
--metric MI[\
fixed_t1.nii.gz,\
moving_t1.nii.gz,\ ...
--metric MI[\
fixed_t2.nii.gz,\
moving_t2.nii.gz,\ ...
Modifed test to be more clear about the multi-modal state
Reported in issue: https://github.com/nipy/nipype/issues/1175

BUG: Restore registration interface failed multi-modal

---

nipype/algorithms/modelgen.py
nipype/algorithms/tests/test_modelgen.py

@satra you were right, I tested simply correcting the line you pointed out solved the problem. Fix for #1198.

fix for SpecifySPMModel

---

nipype/interfaces/ants/base.py
nipype/interfaces/ants/registration.py
nipype/interfaces/ants/segmentation.py

Registration and jointFusion
interface was improved to support
multimodal input when they are given.
ex)
nipype:
antsWF.inputs.fixed_image=['fixed_t1.nii.gz',
'fixed_t2.nii.gz']
antsWF.inputs.moving_image=['moving_t1.nii.gz',
'moving_t2.nii.gz']
corresponding commandline:
--metric MI[\
fixed_t1.nii.gz,\
moving_t1.nii.gz,\ ...
--metric MI[\
fixed_t2.nii.gz,\
moving_t2.nii.gz,\ ...

FIX: Joint Fusion multimodal Interface Fix

---

nipype/workflows/dmri/fsl/tbss.py

If an image is loaded with more than 3 dimensions the function crashes.
For example, suppose we load an an image with dimensions (100, 50, 50, 1). The last dimension here is redundant, but still, it is there. This gives an tuple of length 4, which is to long for the format statement on the next line. 
By limiting it to 3 dimensions, this works again.

FIX: Bug in tbss1

---

circle.yml
nipype/interfaces/io.py
nipype/interfaces/tests/test_io.py

* Added S3DataGrabber to nipype/interfaces/io.py
* Added S3DataSink to nipype/interfaces/io.py
* Added tests to nipype/interfaces/tests/test_io.py
* Currently the S3 tests are using a bucket on our lab's account.
* We would like to have a conversation about a more long-term testing solution.

Added support for grabbing and putting data on S3.

---

nipype/interfaces/dcm2nii.py

This is a blind push to get a PR against master. The actual manual tests were done against 0.11.

Sometimes the filename 'arrow' is shorter (Fixes gh-1267)

---

nipype/interfaces/dcm2nii.py

dcm2nii removes a DWI volume and prefixes with 'x' accordingly.
Note: Patch is against 0.11.0 -- last version that runs on Debian jessie, as python-future is not available as a package (AFAICS).

Adjust expected bvecs/bvals filenames for the Philips DWI case

---

nipype/algorithms/modelgen.py

`spm_hrf` generates a divide-by-zero warning on its first run. Makes for ugly output with no user action indicated.

ENH: Suppress division by zero warning in spm_hrf

---

nipype/interfaces/freesurfer/utils.py

SurfaceTransform may specify either a source_file or a source_annot_file (mutually exclusive). However, if out_file is not specified and source_annot_file is specified, _list_outputs will try to generate the out_file name using the source_file (which won't be defined in this case). Added an extra check to see if self.input.source_file is defined and if it's not then use self.inputs.source_annot_file instead.

Fix FreeSurfer SurfaceTransform gen out_file

---

nipype/interfaces/dipy/tensors.py

`get_data()` returns a `numpy` array, so `img.get_data()` and `img.get_affine()` should fail.
Introduced in aa061ae

BF: Erroneous get_data call

---

nipype/interfaces/fsl/model.py

For the f-test vector need to explicitly set elements for contrasts that should not be included in the test to 0.

explicitly set f-test contrasts to 0

---

nipype/interfaces/ants/registration.py

The invert_initial_moving_transform variable in RegistrationInputSpec
needs usedefault=True to fix "TypeError: int() argument must be a
string or a number, not '_Undefined'". This occurred in line 817
"do_invert_transform = int(self.inputs.invert_initial_moving_transform)".

BUG: Sets usedefault=True for invert_initial_moving_transform

---

nipype/interfaces/fsl/maths.py

Fixes two typos in the ```desc``` arguments of ```class ThresholdInputSpec(MathsInput)```.

nipype/interfaces/fsl/maths.py: Fix typos

---

nipype/__init__.py
nipype/interfaces/base.py

this PR has two fixes:
- I discovered a bug in the ipython kernel (https://github.com/ipython/ipykernel/issues/91) that caused faulthandler.enable() to fail with an IOError.  I added explicit catching of IOError to catch this
- decoding of stderr/stdout using the standard .decode() failed in py3.  I added decoding using ISO-8859-1

py3 and ipython fixes

---

nipype/interfaces/matlab.py

In SPM12 standalone r6685 and above, the MATLAB function mfilename() is
overloaded and care must now be taken when calling it. This change is
backward compatible with older SPM versions.

Bug fix in the MATLAB interface for recent SPM standalones

---

.travis.yml
nipype/interfaces/afni/base.py
nipype/interfaces/afni/preprocess.py

Added version checking in afni.SkullStrip to avoid use of virtual display with AFNI >= 16
(comes from https://github.com/poldracklab/mriqc/issues/25#issuecomment-173917499)

[ENH] Check AFNI version in SkullStrip to avoid xvfb

---

circle.yml

Since ```~/examples/fsl-feeds``` was cached, this problem passed unnoticed. Amends #1333.

[FIX] Missing link to fsl-feeds from apt (rel. #1333)

---

nipype/interfaces/afni/base.py
nipype/interfaces/afni/preprocess.py

#1328 only implemented the use case when AFNI was outdated and <16.0.00. This means, ```afni_vcheck``` returned a version ID derived from the date of compilation. Since 16.0.00 it returns an ID containing the version number.
However, with the release of 16.0.01 tonight, I've found that the case of outdated installations with the new format was not correctly processed. This PR fixes that (until they change the version ID format again...)

[ENH] Improved AFNI version parsing after recent publication of 16.0.01

---

nipype/interfaces/freesurfer/utils.py
nipype/pipeline/plugins/oar.py

mri_surf2vol can either be run using a source file OR without a
source_file if the user wants to create a binary mask. Added XOR
parameter to take this behavior into account

FIX: Freesurfer surf2vol - Added XOR to mkmask and source_file

---

nipype/pipeline/engine/utils.py

This fixes an incompatibility with networkx>=1.11 reported here:
https://github.com/nipy/nipype/issues/1350#issuecomment-181495121

Fixed write_dot error for networkx>=1.11 in nipype/pipeline/utils.py

---

nipype/workflows/dmri/fsl/dti.py

Example in source code comments can introduce bug in user code if
followed blindly, passing `params` as positional argument actually gets
it assigned to parameter named `compute_all_outputs`, meaning `params` gets
default values. Fix is to explicitly use named argument in function
call.

Update example to prevent obscuring passed params

---

nipype/interfaces/camino/connectivity.py

The `tract_stat` input option is mandatory when you use `scalar_file` using Camino's ConMat.
I fixed the example so people don't forget to set it.

fix: Complete the documentation for ConMat

---

CHANGES
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Fixes bug introduced in #1161.
Attempting to link to a symlink results in `DataSink` pushing symlinks to the nipype working directory out onto the filesystem at large. Can reproduce by connecting a `Rename` node to a `DataSink` node.
Test verifies the behavior of copying and linking from a symlink, fails prior to fix. Final patch passes optional `copyfiles` arguments to secondary calls. That seems like the least surprising behavior.

FIX: Use realpath to determine hard link source

---

nipype/pipeline/plugins/slurmgraph.py

Our system prints out a lot of additional information about the submission process that cannot be disabled using the --quiet option to sbatch. This PR is one potential fix. Below is the example output:
-----------------------------------------------------------------
Welcome to the Lonestar 5 Supercomputer          
-----------------------------------------------------------------
No reservation for this job
--> Verifying valid submit host (login1)...OK
--> Verifying valid jobname...OK
--> Enforcing max jobs per user...OK
--> Verifying availability of your home dir (/home1/03872/wtriplet)...OK
--> Verifying availability of your work dir (/work/03872/wtriplet/lonestar)...OK
--> Verifying availability of your scratch dir (/scratch/03872/wtriplet)...OK
--> Verifying valid ssh keys...OK
--> …

Improve sbatch stdout parsing for JobID.

---

CHANGES
nipype/interfaces/base.py
nipype/interfaces/spm/tests/test_base.py
nipype/interfaces/tests/test_base.py

fix: unicode characters in stderr on certain systems 

---

CHANGES
circle.yml
doc/documentation.rst
doc/users/pipeline_tutorial.rst
nipype/interfaces/base.py
nipype/pipeline/plugins/base.py
nipype/pipeline/plugins/pbs.py

FIX: job execution on systems/approaches where locale is undefined

---

nipype/interfaces/petpvc.py
nipype/interfaces/tests/test_utility.py
nipype/pipeline/engine/workflows.py

This is a PR related with issue #1404

fix:test & fix bug using aux functions in connect

---

.travis.yml
CHANGES
circle.yml
nipype/testing/__init__.py
nipype/testing/tests/test_utils.py
nipype/testing/utils.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Added a patch that addresses #1387 by falling back on `copyfile(copy=True)` when symlinking fails. But it seems it might be good to fully work out the cases, now that hard linking is an option, as well.
The current logic is:
flag:copy | flag:use_hardlink | sys:posix | cap:hardlink | action
-------|-------------------|-----------------------|------------------------|---------
T | T | * | T | hard link
T | F | * | * | copy
T | * | * | F| copy
F | * | T | * | symlink
F | T | F | T | hard link
F | * | F | F | copy
F | F | F | * | copy
I see two problems:
1. `os.name == 'posix'` does not guarantee symlinks work, so we need some other `cap:symlink`
indicator.
2. `copy == False and use_hardlink == True` on a POSIX system uses a symlink when a hard link
could work and be more in line with the …

REF/FIX: Correct link/copy behavior

---

examples/README

The link to the example dataset wasn't working. This PR updates the link to one that currently works.

FIX: Updates link to the example tutorials site and data.

---

nipype/pipeline/plugins/oar.py

Previously, the arguments supposed to be passed onto the oarsub command just were discarded. Now they are correctly passed to the command such that one can for example set higher wall times or restrict job submission to a certain subset of nodes etc
Tested and working on our OAR cluster

Pass on the oarsub args

---

nipype/testing/data/epi_param.txt

For the workflows/dmri/fsl/artifacts the acc_factor was missing. I guess epi_acc was renamed to acc_factor?
FYI: On Philips scanners this factor is always 1, even with Sense acceleration. The Sense factor is taken into account during the echo spacing calculation.
wfs(Hz) = gamma * B0 * 3.4 ppm => 434.215 Hz at 3T
Echo spacing = WFS(pixel) / (wfs *(ETL +1))
Changing Sense will affect both WFS and ETL.
see Philips doc: EPI unwarping using B0 maps.pdf

epi_param.txt: missing acc_factor added. epi_acc renamed to acc_factor?

---

CHANGES
nipype/interfaces/freesurfer/__init__.py
nipype/interfaces/freesurfer/base.py
nipype/interfaces/freesurfer/model.py
nipype/interfaces/freesurfer/tests/test_model.py
nipype/interfaces/freesurfer/tests/test_preprocess.py
nipype/interfaces/freesurfer/tests/test_utils.py

The example as given in the [docs](http://nipy.org/nipype/interfaces/generated/nipype.interfaces.freesurfer.model.html#id1) will fail to run, raising:
TraitError: The 'concatenated_file' trait of a ConcatenateOutputSpec instance must be an existing file name, but a value of 'bar.nii' <type 'str'> was specified.
While the `ConcatenateInputSpec` seems happy with a relative path, it seems `ConcatenateOutputSpec` needs an absolute path, so simply passing it through is insufficient. This change prepends the working directory. I've tested this on my own pipeline, and it resolves an error like the one above.

FIX: Permit relative path for concatenated_file input to Concatenate()

---

nipype/interfaces/utility.py

Hi,
I saw you had old code in in `IdentityInterface._add_output_traits`, I change it for it to call `add_traits` instead.

Quick cleanup of IdentityInterface code

---

nipype/workflows/smri/freesurfer/autorecon1.py

A number of cleanups I saw while looking at #1431.
* This uses nibabel instead of SimpleITK to determine image shape. SimpleITK is still a dependency in two functions in nipype/workflows/smri/freesurfer/utils.py.
* From what I could see, the conversion from `.mgz` to `.nii` was to allow SimpleITK to load the file, so I removed it.
* I used list/generator comprehensions to reduce indentation levels and separate unrelated calculations.
@dgellis90 Can you verify that this still behaves as expected in your tests?
Minor change, so forgoing a CHANGES entry unless otherwise instructed.

REF: Simplify checkT1s

---

nipype/workflows/fmri/fsl/preprocess.py
nipype/workflows/smri/freesurfer/autorecon1.py

before: AttributeError: 'MRIConvert' object has no attribute 'outputs' converting T2 file.

autorecon1: convert_modalities output fix

---

nipype/interfaces/petpvc.py

Change the PETPVC node docstrings so it prints better on the documentation page.

improve petpvc docstrings

---

nipype/pipeline/engine/nodes.py

The fact that Python 3.x deletes the exception variable after the `except` block makes this `finally` necessary.

add a finally statement in _node_runner

---

CONTRIBUTING.md

It was linking to https://github.com/nipy/nipype/blob/master/neurostars.org.

Fix neurostars link; was viewed as rel path by Github

---

nipype/interfaces/freesurfer/tests/test_auto_Sphere.py
nipype/interfaces/freesurfer/utils.py
nipype/workflows/smri/freesurfer/autorecon3.py
nipype/workflows/smri/freesurfer/recon.py

@dgellis90  and @hjmjohnson - could you please take a look at these changes? this did allow running from start to finish. 
```
from nipype import config
config.enable_provenance()
import os
from nipype.workflows.smri.freesurfer import create_reconall_workflow
recon_all = create_reconall_workflow()
recon_all.inputs.inputspec.subject_id = 'time'
recon_all.inputs.inputspec.subjects_dir = os.getcwd()
recon_all.inputs.inputspec.T1_files = os.path.abspath('mprage003.nii.gz')
recon_all.base_dir = os.getcwd()
recon_all.run(plugin='MultiProc', plugin_args={'n_procs': 4})
```
also subject_id did not seem to get carried along into the sub commands. so i saw commands like this where the --subject is called with subejct_id instead of 'time' as i used in calling the workflow.
```
Running: mri_segstats …
```

fix: to have recon-all work with 5.3 on OSX

---

nipype/interfaces/dcm2nii.py

New: Saving 65 DTI gradients. Please validate if you are conducting DTI
analyses.
see https://github.com/nipy/nipype/issues/1389

output for DTI vectors changed (dcm2nii -> dcm2niix)

---

nipype/workflows/smri/freesurfer/autorecon1.py

Fixes the createTemplate function which was failing when it tried to get the output from the RobustTemplate interface.
Fixes #1472

FIX: Fixes createTemplate function

---

doc/links_names.txt
doc/sphinxext/numpy_ext/numpydoc.py
doc/users/install.rst

small changes to start contributing!

DOC:add instructions to install; fix doc build for python 3

---

nipype/interfaces/dipy/base.py

being passed into the object correctly, so I changed the function used
to create the GradientTable object

FIX: The GradientTable object should be immutable; the bvalues aren't

---

doc/users/plugins.rst
nipype/pipeline/plugins/ipython.py
nipype/pipeline/plugins/ipythonx.py

fix: clarify ipython plugin usage - fixes #1451

---

nipype/pipeline/plugins/ipython.py

I want to manage cluster processing outside of the default IPython profile, and this change allows nipype to accommodate that. While I'm only using the `profile` argument, this change accepts all of the valid parameters for `IPython.parallel.Client`. I think `url_file`, `profile` and `cluster_id` are probably a minimal set.
No tests yet, but throwing this up before I get too far, in case people have opinions on the approach, whether this is a good idea, etc.

WIP/ENH: Allow client args as IPython plugin_args

---

CHANGES
nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/tests/test_Level1Design.py

This also provides a framework that is easily extensible to other convolution methods which we do not yet provide.
Fixes issue #1498

fixed fsl.Level1Design gamma convoluion

---

nipype/interfaces/fsl/model.py

Removed the "experimental" disclaimer for the Randomise interface. This has been causing a lot of confusion over the years, but as far as I know there is nothing wrong with this interface.

removed "experimental" warning of Randomise

---

nipype/pipeline/engine/utils.py

the previous version was experiencing errors when run on an HPC system, wherein multiple processes were trying to create the same directory at exactly the same time. this adds code to prevent this error, but still throw an error if the directory can't be made and doesn't exist.

added logic to prevent directory creation collisions

---

doc/users/grabbing_and_sinking.rst

corrects the doc usage of DataGrabber given sort_true is a mandatory argument now. Fixes #1471 .

correct usage of the DataGrabber node

---

nipype/interfaces/fsl/maths.py
nipype/interfaces/fsl/tests/test_maths.py

Hi, I added a class to fslmaths to calculate the standard deviation in a voxel. 
Here is the neurostars-thread about it:
https://neurostars.org/p/4004/
I already tried it out in my local nipype version in a workflow like this.
stdev = pe.Node(fsl.maths.StdImage(), name= 'Std_deviation_calculation')
The result looks good.
It is the first time I do something like this. Is this right? Also, I don't know, where I would have to add documentation. Feedback appreciated. Thanks, Leonie

fslmaths -Tstd option added

---

nipype/interfaces/fsl/model.py

* updated string formatting syntax to the cleaner `.format()`
* removed unneeded substitutions (only kept substitutions for which variables are used)
* no longer using scientific number notation (sometimes causes issues with FSL)

Minor L2Model improvements

---

nipype/pipeline/engine/base.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py

I tried to use the export feature of the workflow object, but it kept failing because of the import of the inspect module. The latter was indeed missing. Since inspect is not available for the early Python 3 and Python 2 releases, I also use the funcsigs module which backports the signature function.
I have tested it on my private fork, running Python 2.7 and the export now works. However I could not figure out how to specify the conditional install_requires on funcsigs inside the setup.py. You guys might want to merge this PR as it is and fix the setup.py later, or give me some pointers on how to do it.
cheers.

Fix broken format_node due to missing inspect import.

---

nipype/pipeline/engine/utils.py

Import the pickle module, which is required for workflow export
function.

FIX: import error in workflow export

---

nipype/info.py
nipype/interfaces/base.py
nipype/interfaces/tests/test_runtime_profiler.py
nipype/interfaces/utility.py
nipype/utils/config.py

fix: remove psutils usage by default

---

CHANGES
nipype/interfaces/fsl/__init__.py
nipype/interfaces/fsl/tests/test_auto_AvScale.py
nipype/interfaces/fsl/utils.py

Necessary for producing correct tsv files with motion parameters @chrisfilo

[ENH] Implement missing inputs/outputs in avscale

---

nipype/interfaces/base.py

The correct_runtime_codes default is a list, which is mutable. This allows for the default to be changed in subsequent calls. Changed to a tuple

Changed default for CommandLine._run_interface to not be mutable

---

circle.yml

This is causing #1570 and other PRs to fail.

[FIX] CircleCI fails when examples are not cached

---

nipype/pipeline/plugins/base.py

Fixed exception syntax to be compatible with Python 3.
@oesteban It looks like the "e" reference is used in L172 if the clause on L164 executes.

Fix for https://github.com/nipy/nipype/issues/1575

---

CHANGES
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

FIX: Fix symlink test in copyfile

---

CHANGES
nipype/utils/tests/test_filemanip.py

Not actually a bug, since there's no harm in what we were doing, but the test from #1570 caught unexpected behavior. Seen in [test failure](https://circleci.com/gh/effigies/nipype/79) for #1379.
The general rule when creating symlinks in `copyfile` is: if the new symlink will point to the same place as the old, do not replace. When creating a symlink from a symlink, though, it does not dereference the source symlink to check whether the end reference would be the same, and so always removes and recreates the destination symlink.
This brings the behavior with a symlink source file in line with behavior for a regular source file.
Separated the test to be more thorough and added error messages for debugging.

TEST: Do not test copy idempotence for unlinked files

---

nipype/interfaces/nipy/model.py

Updated the import, as suggested by this warning I am getting:
```
/usr/lib64/python2.7/site-packages/nipy/labs/glm/glm.py:9: FutureWarning: Module nipy.labs.utils.routines deprecated, will be removed
from ..utils import mahalanobis
/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/model.py:18: FutureWarning: Module nipy.labs.glm deprecated, will be removed. Please use nipy.modalities.fmri.glm instead.
import nipy.labs.glm.glm as GLM
```
Tested the update with real data.

updated GLM imports

---

nipype/interfaces/spm/preprocess.py

Allows the user to submit a list of warping regularization parameters to an spm.NewSegment routine, which appears to be required for some SPM12 workflows. This is a fix for Issue #1272.

[Issue #1272] Input a list of warping regularization parameters to interfaces.spm.NewSegment

---

bin/nipype_crash_search
bin/nipype_display_pklz

- fix nipype_crash_search to print usage on no args.
- change nipype_crash_search shebang to #!python.
- add nipype_display_pklz to look into .pklz node files.

A few fixes to bin scripts and a proposal of a new one

---

nipype/interfaces/traits_extension.py

The future strings in traits definition causes crashes for most interfaces using os.environ as an input.

Fix dictstrstr

---

nipype/interfaces/semtools/brains/__init__.py
nipype/interfaces/semtools/brains/utilities.py

@hjmjohnson 
Hans, this branch is successfully rebased based on the latest head of NIPYPE (git://github.com/nipy/nipype.git ); however, the latest version of NIPYPE has conflicts with our local BRAINSia nipype (git@github.com:BRAINSia/nipype.git)

Added to semtools

---

setup.py
setup_egg.py

When installing with pip install -e ., these needed to be already installed.

[FIX] setup.py: remove future and configparse deps

---

nipype/utils/tests/test_filemanip.py

From #1617, comparing `stat` on an unchanged file can falsely indicate a change if the filesystem sets `atime`s.
The first commit uses a helper function to cause tests to always span a clock tick, to demonstrate that all test-timing-related bugs (e.g. #1586) are handled, so we don't have to keep coming back to this.
The second commit removes the delays so that the tests run in <1s instead of ~13s.
Given that this follows on #1391, #1570 and #1586, no changelog entry.

TEST: Ignore atime in test_filemanip.test_recopy

---

nipype/pipeline/engine/tests/test_engine.py

A tiny leftover. I have checked that we don't import six nor from six anymore.

[FIX] Remove remaining import from six

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

In response to #1612
Refactors using DRY principal, define related files once.
Additionally, can be patched to extend the related filtypes with:
import nipype
nipype.utils.filemanip.related_filetype_sets.extend([
('.avh', '.hv', '.v'),
('.avs', '.hs', '.s'),
])
Local tests run, and I have checked the above patching with some of my code using Interfiles.
Potential caveats:
- copyfile is recursive, my base condition is not to recurse if the destination file exists (i.e., has been copied). This could lead to infinite recursion if the copy fails. Suggestions are welcome (check for infinite recursion and throw instructive error? Add a new function argument defining whether to check related files so is only checked at top level?)
- behaviour is not identical to before. i.e., before `copyfile` …

REF: define related filetypes once.

---

nipype/pipeline/plugins/tests/test_multiproc.py

FIX sometimes-failing test (memory) iss 1607

---

.travis.yml

issue https://github.com/nipy/nipype/issues/1622
I've finished retries for travis. I need to focus on other things so circle will have to wait.

TST Automatic retries in travis

---

CHANGES
nipype/algorithms/modelgen.py
nipype/caching/memory.py
nipype/external/due.py
nipype/interfaces/base.py
nipype/interfaces/fsl/dti.py
nipype/pipeline/engine/base.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/sge.py
nipype/utils/filemanip.py

- Close #1655: fixes the References:: leftover in help() of interfaces
- Close #1644: fixes the parameterized paths generated with python 2
- All uses of ```repr()``` and re-definitions of ```__repr__``` have been revised
(again, this is related to #1644, #1621, etc).

[FIX] Several fixes related to unicode literals

---

.travis.yml
nipype/interfaces/fsl/possum.py

The `inputs.output_type` was not specified in the B0calc example, and a tests run by travis didn't fail since an export statement was outside an if block.

[FIX] Minor errors in the travis file and in one doctest

---

nipype/pipeline/plugins/multiproc.py
nipype/pipeline/plugins/semaphore_singleton.py

There was a bug on how the semaphore of the multiproc plugin was initialized and released.
The semaphore counter was initialized with 1, being acquired over and over again and never released.
That is because semaphore.acquire() was called more times than semaphore.release(), so the semaphore internal counter would always be > 0, leading to the master process to be active all the time.
We noticed that bug because the master process of the run was utilizing 100% cpu, even on the times it was supposed to be sleeping.
This fix makes the multiproc plugin have the expected behavior: the main process sleeps when it is waiting for jobs to finish.
Besides that, the multiproc plugin still works exactly the same as before.

fix semaphore acquire bug

---

nipype/info.py

otherwise - kaboom:
```shell
$> virtualenv venv-tests
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/venv-tests/bin/python2
Also creating executable in /tmp/venv-tests/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
2 16589.....................................:Mon 31 Oct 2016 12:36:49 PM EDT:.
hopa:/tmp
$> source venv-tests/bin/activate
(venv-tests) 2 16590.....................................:Mon 31 Oct 2016 12:36:51 PM EDT:.
hopa:/tmp
$> pip install nipype
Collecting nipype
Using cached nipype-0.12.1-py2.py3-none-any.whl
Collecting nibabel>=2.0.1 (from nipype)
Collecting traits>=4.3 (from nipype)
Collecting future>=0.15.2 (from nipype)
Collecting scipy>=0.11 (from nipype)
Using cached scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl …
```

BF: install requires configparser

---

nipype/pipeline/engine/base.py
nipype/pipeline/engine/tests/test_join.py
nipype/pipeline/engine/utils.py

now correctly connects joinnodes within nested workflows - see example
adds node.itername to engine base

fix: joinnode connection bugfix

---

nipype/interfaces/fsl/preprocess.py

We had ConvertXFM and ApplyXfm. For consistency, we could deprecate ApplyXfm in favor of ApplyXFM.

FIX: Make XFM capitalization consistent

---

nipype/interfaces/fsl/preprocess.py
nipype/interfaces/fsl/tests/test_preprocess.py

NEW: `FAST._list_outputs()` was incorrectly listing output files in `cwd` when `out_basename` is not set. This PR fixes it.
OLD:The FAST interface is not outputting files into the correct directory when `out_basename` is not set. This solution feels hacky. I'm also concerned that this seemingly obvious bug hasn't been caught and fixed before now.
I'll fix up the tests once I have confidence this is the "right" solution.

[FIX] FAST output files

---

nipype/interfaces/spm/preprocess.py

With the newer SPM12, it is now possible to use "slice onsets" in milliseconds, instead of the good old simple slice order.
I've tested if there is any difference between slice_order [0 1 2 3,...] or [0.0 1.0 2.0 3.0,...] and with my test data there was none.
SPM12 and SPM8, both accept the float point approach, but SPM8 crashes if one tries to use actual onsets, i.e. [0.0 66.66 133.33, 200.0...].

changes slice_order type from Int to Float

---

.travis.yml
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/engine/workflows.py

suggested to Fix #1584
Colors now cycle, yellow for top-level, then B, R, G, B, R, G...

Fix #1584 color graphing to loop through blue, red, green.

---

nipype/algorithms/confounds.py
nipype/algorithms/tests/test_auto_TCompCor.py

- input mask is not being ignored anymore (fixes #1744)
- use np.percentile instead of implementing it by hand
- output the estimated high variance mask (useful for debugging)

Fixes for tCompCor

---

nipype/algorithms/confounds.py
nipype/algorithms/tests/test_compcor.py
nipype/algorithms/tests/test_mesh_ops.py
nipype/algorithms/tests/test_modelgen.py
nipype/algorithms/tests/test_overlap.py
nipype/interfaces/freesurfer/tests/test_preprocess.py
nipype/interfaces/fsl/tests/test_base.py
nipype/interfaces/fsl/tests/test_dti.py
nipype/interfaces/fsl/tests/test_epi.py
nipype/interfaces/fsl/tests/test_maths.py
nipype/interfaces/fsl/tests/test_preprocess.py
nipype/interfaces/fsl/tests/test_utils.py
nipype/interfaces/spm/tests/test_base.py
nipype/interfaces/spm/tests/test_preprocess.py
nipype/interfaces/tests/test_base.py
nipype/interfaces/tests/test_io.py
nipype/interfaces/tests/test_nilearn.py
nipype/interfaces/tests/test_utility.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/engine/tests/test_join.py
nipype/pipeline/engine/tests/test_utils.py
nipype/pipeline/plugins/tests/test_base.py
nipype/pipeline/plugins/tests/test_callback.py
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/utils/tests/test_cmd.py
nipype/utils/tests/test_filemanip.py

I forgot to remove trailing spaces from pytest PR

removing trailing spaces

---

circle.yml
nipype/interfaces/tests/test_runtime_profiler.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/plugins/base.py
nipype/pipeline/plugins/multiproc.py
nipype/pipeline/plugins/tests/test_callback.py
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/pipeline/plugins/tests/test_multiproc_nondaemon.py

FIX MultiProc deadlock
Reduced the complexity of the MultiProc processing to reduce likelihood for deadlock by:
removing semaphores and replacing with event, this allows for a timeout in the wait that safeguards against deadlock
setting results directly from apply_async callback rather than two stage processing, where a signal is sent from the callback, that wakes the multiproc.run() thread, which then sets the results -- this is where i think the previous deadlock was happening
Found deadlock where events would be cleared before they were handled, creating scenarios where thread waits for a signal that will never come -- fixed by changing the location from before the wait to after
Added missing close thread pool
Re-enabled multiproc tests
-- rebased with master

FIX MultiProc deadlock

---

nipype/pipeline/plugins/sge.py

attribute mistyped causing crashes:
```
AttributeError: 'QJobInfo' object has no attribute '_queue_state'
```

fix sge plugin __repr__

---

nipype/interfaces/base.py

fixes  #1752
It looks like adding additional if statement solves the problem related to a new version of `traits.HasTraits.traits`.
I'm not sure what is the main purpose of the modified loop, so waiting for other suggestions.

[FIX] problems with traits4.6 

---

nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/tests/test_Level1Design_functions.py
nipype/interfaces/script_templates/feat_ev_gamma.tcl

The FSL model parameter passing to substitute the variables in the template EV files is very clunky and difficult to extend. I have streamlined parameter passing by putting all the EV file variable parameters in a dict. Also, using this new and easier paremeterization system, I have added parameters for gammadelay and gammasigma.
After this PR more even parameters can be added very easily and without cluttering the code.

more concise and flexible parameter passing, increased parametrization

---

nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/tests/test_Level1Design_functions.py
nipype/interfaces/script_templates/feat_ev_ortho.tcl

Currently FEAT's orthogonalization function is entirely unaccessible via nipype.
This PR makes it accessible via a dict.

added support for orthogonalization

---

nipype/pipeline/engine/tests/test_engine.py

* I left the try/except blocks in `test_node_init` and  `test_io_subclass`: it looks like the tests should fail only for some exceptions, and others are ok
* I removed also `logger.info('Exception: %s' % str(e))` parts, most other test don't have it anyway. I can bring it back if needed.

simplifying tests, removing some try/except blocks

---

nipype/algorithms/confounds.py

When the input files are not compressed, numpy wraps memmap around the
dtype. This makes the traits.Float validation to fail.
An more robust way would be overloading traits.Float to validate also
these memmap objects. But this is probably overkilling the problem.
For now, this casting is the easiest and safest solution.

Cast DVARS float outputs to avoid memmap error

---

circle.yml
docker/circleci/tests.sh

- Cache both docker containers.
- Split the tests across all 4 containers.

Make CircleCI use all 4 containers

---

doc/users/config_file.rst

Looks like hash_method has defaulted to ``timestamp`` for a while:
https://github.com/nipy/nipype/blob/master/nipype/utils/config.py
Updating the config documentation.

DOC: update docs to reflect default hash_method value

---

.travis.yml
nipype/algorithms/misc.py
nipype/algorithms/modelgen.py

* defaults to latest icu (58.1)
* removes non-integers from array slicing/initializing in `algorithms/misc` and `algorithms/modelgen` , which now throw hard errors

tst: not defining specific icu

---

nipype/interfaces/freesurfer/preprocess.py

`bbregister` has new initialization options, including an implicit default of using `mri_coreg`, as of version 6.0.0.
This change updates the `init` trait if FreeSurfer is version 6 or newer, following the example from [FSL](https://github.com/nipy/nipype/blob/f5ed4d68fc922fa3eea6a43036b09f79bfa94acb/nipype/interfaces/fsl/model.py#L589).
Is there a good way to test this?

ENH: Enable new BBRegister init options for FSv6+

---

nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/tests/test_auto_BBRegister.py

Instead of replicating FS default of `--init-coreg`, set `init` as non-mandatory.
Follow-up to #1811.

Unset default init for BBRegister in FS 6+

---

nipype/algorithms/misc.py
nipype/algorithms/tests/test_misc.py
nipype/testing/fixtures.py

Hi,
I've found a bug in misc.CreateNifti while running Camino tractography workflows.
This seems to fix it.
Cheers,
Alex

Fix small bug/typo in misc.CreateNifti

---

nipype/interfaces/petpvc.py

Updating the reference to PETPVC with their new publication.

update PETPVC reference

---

nipype/interfaces/dipy/preprocess.py
nipype/workflows/dmri/dipy/denoise.py
nipype/workflows/dmri/fsl/epi.py
nipype/workflows/dmri/fsl/tbss.py
nipype/workflows/dmri/fsl/utils.py
nipype/workflows/misc/utils.py

Follow-up to #1796. Some imports were at the file level when they should have been at the function level. My criterion for moving was whether there are other function-local imports.
Addresses issue discovered in poldracklab/fmriprep#362 (and poldracklab/fmriprep#363).

FIX: Import NUMPY_MMAP inside functions

---

nipype/info.py
requirements.txt
rtd_requirements.txt

On an otherwise headless server, xvfbwrapper pulls in a significant stack totalling at least 42 dependencies:
```
[ebuild  N     ] sys-libs/mtdev-1.1.5::gentoo  USE="-static-libs" 268 KiB
[ebuild  N     ] media-libs/libepoxy-1.4.0::gentoo  USE="{-test}" ABI_X86="(64) -32 (-x32)" 301 KiB
[ebuild  N     ] x11-proto/fontsproto-2.1.3::gentoo  USE="-doc" 151 KiB
[ebuild  N     ] x11-proto/xineramaproto-1.2.1-r1::gentoo  ABI_X86="(64) -32 (-x32)" 94 KiB
[ebuild  N     ] x11-proto/randrproto-1.5.0::gentoo  ABI_X86="(64) -32 (-x32)" 139 KiB
[ebuild  N     ] x11-proto/videoproto-2.3.3::gentoo  ABI_X86="(64) -32 (-x32)" 119 KiB
[ebuild  N     ] x11-libs/libxkbfile-1.0.9-r1::gentoo  USE="-static-libs" ABI_X86="(64) -32 (-x32)" 340 KiB
[ebuild  N     ] x11-apps/xauth-1.0.10::gentoo  USE="ipv6 …
```

removed obligatory xvfbwrapper dependency

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Hello,
I'm working with 4D files and SPM and I didn't find a way to copy the header files generated by spm realign into the output folder of my workflow.
Also, I found that when these header files are not in the working directory of another node (eg, normalization), then the results of Nipype are different from those when the same workflow is executed in SPM Matlab. 
I hope these modifications are useful.
Cheers,
Jaime

Estimated transform files in spm realign output directory for 4D files

---

nipype/interfaces/ants/segmentation.py

When strings are formatted in unicode, then the format
of the AntsJointFusion -g, -t flags is not the same
as the python string representations of lists.  These
flags need to be unpacked one-by-one and a new string
representation needs to be provided on the command line.

FIX: AntsJointFusion unicode command line formatting

---

nipype/interfaces/fsl/preprocess.py

[DOC] update FSL preprocess

---

nipype/interfaces/freesurfer/utils.py

This PR creates "implicit" output types for Freesurfer utilities, where no explicit `--out_type` is supported, but a filename with the associated extension will be correctly produced as that type.
At present, I've only tested this with GIFTI on `mri_vol2surf`. I expect `mri_surf2surf` will have the same level of support. I also suspect that any of the `mris_convert` outputs would work fine.
Note that `.gii.gz` actually produces a `.mgz` file with `.gii.gz` extension, and so any additional output types need to be checked for correctness. Similarly, not all files seem to produce a correct GIFTI; for example, `--srchit test.gii` produces a valid GIFTI file with completely different data.

[RTM] Support GIFTI outputs in SampleToSurface

---

nipype/interfaces/utility/base.py
nipype/interfaces/utility/tests/test_base.py

At present, `Merge()` does nothing, providing an undefined `outputs.out`. This change allows it to merge a list of lists (`inputs.in_lists`) into a single list, rather than enumerating them with `inputs.in1 .. inputs.inN`.
If no `inputs.in_lists` is set, `Merge()` still provides an undefined `outputs.out`, so we shouldn't break existing code.
`Merge(n)` for `n < 0` is unchanged.

ENH: Make interfaces.utility.Merge(1) merge a list of lists

---

nipype/interfaces/fsl/epi.py

FIX: Select Eddy command at runtime

---

CHANGES
doc/conf.py
doc/documentation.rst
doc/users/index.rst
doc/users/sphinx_ext.rst
nipype/info.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/sphinxext/__init__.py
nipype/sphinxext/plot_workflow.py
nipype/utils/filemanip.py

Adds a sphinx extension to the nipype installation. After adding `nipype.sphinxext.plot_workflow` to the `extensions` list in the `doc/conf.py`, sphinx will parse blocks like:
```
.. workflow ::
:graph2use: flat
:simple_form: no
from nipype.workflows.dmri.camino.connectivity_mapping import create_connectivity_pipeline
wf = create_connectivity_pipeline()
```
The graph is embedded at the point where the block is placed in the docstring.

[ENH] Sphinx extension to plot workflows

---

nipype/utils/draw_gantt_chart.py

A minor revision of this utility.

[FIX] Python 3 compatibility of gantt chart generator

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

There appear to be cases where hacks to make symlinks work on filesystems that don't directly support them can cause `FileNotFoundError`s. In particular, the CIFS network filesystem driver for Linux supports the `mfsymlinks` option, which enables symlinks at the VFS level, having the effect that symlinking can be subject to network timeouts or temporary inconsistencies.
CIFS+`mfsymlinks` is the Docker-supported way to mount filesystems into a container from a Windows host, which means this may be increasingly a problem for Nipype users, as containers are becoming a more popular environment for running workflows. An [error](https://github.com/poldracklab/fmriprep/pull/398#issuecomment-291723199) reported on poldracklab/fmriprep#398 ran into this issue when running an interface that …

ENH: Disable symlinks on CIFS filesystems

---

nipype/interfaces/utility/tests/test_wrappers.py
nipype/interfaces/utility/wrappers.py

Found this branch sitting around. Will be glad to update (and improve) if there's interest.
Closes #1386.

ENH: Auto-derive input_names in Function

---

nipype/pipeline/engine/workflows.py

FIX: catch write_graph errors for 'hierarchical/colored

---

nipype/interfaces/freesurfer/base.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/tests/test_preprocess.py

This change replaces `interfaces.freesurfer.preprocess.FSVersion` with `interfaces.freesurfer.Info.looseversion()`, and makes the corresponding updates throughout the code.
The goal is to get a well-behaved version string that is comparable across versions, including no installation. `LooseVersion` is used in anticipation of the most common use case.
`FSCommand().version` is updated to pull the version string out of `Info.looseversion()` to ensure that the same logic is applied whenever a parsed version string is used.
Release versions use simple version strings (no githash). Post-v6 `dev` versions follow format suggested by @satra in #1928: `6.0.0-dev.GITHASH`. `dev` versions without githashes are parsed as before.
Closes #1928.

Centralize FreeSurfer version parsing

---

nipype/interfaces/ants/registration.py

Newer ANTs versions aren't verbose by default, but take a verbose flag.

ENH: Add a verbose tag for newer ANTs versions

---

nipype/pipeline/engine/utils.py

Currently the detailed graph is always returned, so code that depends on the return value of `export_graph`, such as the Sphinx workflow extension.
`export_graph()` currently always writes out a detailed graph and a (potentially) simple one. I didn't change this, because I'm not sure if anybody is expecting both graphs.
Related: poldracklab/fmriprep#463

FIX: Return simple filename from export_graph if simple form is requested

---

examples/rsfmri_vol_surface_preprocessing_nipy.py

fixes error in example from #1971 
[This page](http://nipype.readthedocs.io/en/latest/users/examples/rsfmri_vol_surface_preprocessing_nipy.html) also needs to be updated, but where is it?

fix: incorrect import paths

---

nipype/algorithms/rapidart.py

not sure if this cause the #1965, but I believe that the backend should be set there anyway.

changing backend in ArtifactDetect

---

nipype/interfaces/base.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/plugins/multiproc.py

This PR:
- Sets the default `estimated_memory_gb` to 0.25 (most of the nodes of a workflow will never reach 1GB)
- Makes two new arguments available to creating Nodes (n_procs and mem_gb), that will set those two values in the inner interface (no need to set node.interface.num_threads anymore).
- Fixes a small error formatting one Exception (we had `__interface` instead of `_interface`).
TODO list:
- Remove estimated_memory_gb and num_threads from the BaseInterface
- Find a way to synchronize the Node level num_threads and the inner interface inputs (maybe a new metadata threads=True to identify these inputs?)
- Resource handling of MapNodes (check if these changes would affect those).

[ENH] Migrating resource handler to Node level

---

nipype/pipeline/plugins/pbs.py

When using python3 to call the PBS status command line script there is a TypeError crash (bytes-like object not str required). To fix this I have used the interfaces.base CommandLine class.
CommandLine already uses the default encoding to decode the
stdout/stderr of the command, so take advantage of that functionality
rather than re-implementing.
First try was to implement decoding pattern seen elsewhere - then I
changed my mind and used a CommandLine object from the interfaces.base
module. (It was already imported to the module anyway)
First Attempt
-------------
Decode the stderr using the default encoding
* Fixes TypeError bug for PBS jobs running on python3.x
* Fixes issue #1959
Second Attempt
--------------
Use the nipype CommandLine class instead of Popen
Remove unused modules …

FIX: TypeError bug for PBS process communication in python3

---

nipype/pipeline/plugins/sge.py

This is an artifact from #1656. Causes an AttributeError when zombie processes are found.

Fixed type referencing non-existent attribute in QJobInfo

---

nipype/interfaces/freesurfer/preprocess.py

Allows for the flags input to ReconAll interface to be either a string or a list of strings. This makes it possible to set multiple flags on ReconAll without having to first convert them to a string as is the case here: https://neurostars.org/p/4314/#4320

ENH: Allows ReconAll.inputs.flags to take in a list of flags

---

nipype/interfaces/ants/segmentation.py

Only when it is not already defined. Also check if the interface failed for that reason nonetheless.
Fixes #1901

[FIX] Define ANTSPATH for ants.BrainExtraction automatically

---

nipype/interfaces/script_templates/feat_header_l1.tcl

Feat was expecting lower level .feat folders, when running interfaces.fsl.model.FEATModel().  This suggestion fixes the bug.

debug 'folder does not exist' error when running feat

---

nipype/interfaces/freesurfer/preprocess.py

The goal of this PR is to give access to most* [multi-stage flags](https://github.com/freesurfer/freesurfer/blob/3e316ab/scripts/recon-all#L6641-L6938), in particular the `autorecon2-volonly` and `autorecon-hemi` flags.
At present, estimating thread consumption is difficult, and `recon-all -parallel -openmp N` can consume up to 2N threads at OpenMP-enabled sections of the surface processing sections of `autorecon2` and `autorecon3`. This change allows `autorecon2-volonly` to be tagged as consuming N threads, and (for instance) two invocations of `autorecon-hemi` to each be tagged as consuming N threads.
This also updates the docstring to document and test the more recent commandline altering changes.
--- 
\* The one that's missing is `gcatrain-iter`, which takes 2 arguments and would thus …

ENH: Update multi-stage recon-all directives

---

nipype/interfaces/fsl/model.py

`ev_parameters.pop('derivs')` removes `'derivs'` from the `ev_parameters`.  As a consequence, only for the first regressor, a temporal derivative is added.  This fixes the issue.

remove bug to have a temporal derivative for multiple variables

---

docker/base.Dockerfile

FSL's FEAT uses (in FSLFixText) the file command to check file type.

command file required by FSL FEAT

---

nipype/interfaces/niftyreg/base.py
nipype/interfaces/niftyreg/tests/test_auto_NiftyRegCommand.py
nipype/interfaces/niftyreg/tests/test_auto_RegAladin.py
nipype/interfaces/niftyreg/tests/test_auto_RegAverage.py
nipype/interfaces/niftyreg/tests/test_auto_RegF3D.py
nipype/interfaces/niftyreg/tests/test_auto_RegJacobian.py
nipype/interfaces/niftyreg/tests/test_auto_RegMeasure.py
nipype/interfaces/niftyreg/tests/test_auto_RegResample.py
nipype/interfaces/niftyreg/tests/test_auto_RegTools.py
nipype/interfaces/niftyreg/tests/test_auto_RegTransform.py
nipype/interfaces/niftyreg/tests/test_regutils.py
nipype/interfaces/niftyseg/base.py

Dear Nipype Team,
In our previous release of the niftyreg interfaces, int the base interface, we added some line of code to set at least by default the number of thread use by niftyreg tools.
I just realized this morning that the code I used isn't correct since I am not checking if the key exists in the dictionary. I edited with @effigies advice from the issue #2004 . 
Basically, I am setting the self.inputs.environ['OMP_NUM_THREADS'] to the environ variable if it exists, else to the num_threads if not found (default 1).
I ran a node using the interface RegAladin and it worked. I tested as well one interface for NiftySeg and it worked as well.
Let me know if you think I should change something from those few lines.
Kind Regards,

Fixing the base interface _run_interface function for NiftyRegCommand

---

nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_engine.py

This PR copies the `num_threads` attribute from source `MapNode`'s interface to those of the generated nodes.
Fixes #2016

FIX: Copy num_threads to MapNode-generated Nodes

---

circle.yml
docker/base.Dockerfile

- Replaces the full installation of FS by a minimized version by @satra
- Depends on #2022

[Docker] Install minimized version of FS6

---

nipype/interfaces/fsl/ICA_AROMA.py

Fixes #2026
added `outputs = self.output_spec().get` to _list_outputs
May or may not fix the other error message.

FIX: Correctly populate output spec for ICA_AROMA

---

nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/tests/test_BBRegister.py

To make up for over-eager issue closing. This PR adds `out_lta_file` to the `BBRegister` interface.
Set `min_ver=5.2.0` based on [this tag](https://github.com/freesurfer/freesurfer/blob/release_5_2_0/scripts/bbregister).
Fixes #266

ENH: Add LTA output to BBRegister

---

nipype/interfaces/spm/model.py
nipype/interfaces/spm/tests/test_auto_EstimateModel.py

Fixes #2029 + #1786 .
- FIX: `inputs.flags` is now a dictionary and works as intended
- ENH: `inputs.write_residuals` is a boolean that will write create an image for each residual
- ENH: supports `Bayesian` estimation outputs

fix+enh: support for Bayesian spm.ModelEstimate, add write_residuals for Classical

---

circle.yml
nipype/algorithms/confounds.py
nipype/algorithms/tests/test_tsnr.py
nipype/caching/memory.py
nipype/interfaces/afni/utils.py
nipype/interfaces/base.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/tensors.py
nipype/interfaces/dipy/tracks.py
nipype/interfaces/utility/base.py
nipype/pipeline/engine/nodes.py
nipype/workflows/dmri/fsl/epi.py

Tests are currently failing, I think at least partially because of a bunch of deprecation warnings about `HasTraits.set`.
This fixes that (I think). Then hopefully the logs will be clear enough to identify other issues.

Replace deprecated HasTraits.set with trait_set

---

nipype/info.py
nipype/interfaces/base.py
requirements.txt
rtd_requirements.txt

External projects, such as [poldracklab/niworkflows](https://github.com/poldracklab/niworkflows), may maintain a set of interfaces, that over time require deprecating portions of their input and output specs. At present, the deprecation machinery is intrinsically tied to nipype's version number.
This PR adds a `package_version` attribute to each interface, which defaults to nipype's, but allows other packages easily to add their own versioning information to specs with a deprecation schedule.

ENH: Permit external packages to deprecate interfaces

---

nipype/workflows/dmri/fsl/artifacts.py

Rationale:
Similar to pull request #1831 (and follow up to #1796) there was a function level import for NUMPY_MMAP that was missing, causing a `NameError`
- import `NUMPY_MMAP` into `_gen_index` [inner function of `all_fsl_pipeline`]

FIX: Import mmap into inner function for all_fsl_pipeline

---

nipype/algorithms/icc.py
nipype/algorithms/metrics.py
nipype/algorithms/misc.py
nipype/interfaces/dipy/preprocess.py
nipype/interfaces/fsl/ICA_AROMA.py
nipype/interfaces/fsl/fix.py
nipype/interfaces/niftyseg/base.py
nipype/interfaces/petpvc.py
nipype/interfaces/utility/wrappers.py
nipype/pipeline/engine/utils.py
nipype/utils/__init__.py
nipype/workflows/dmri/fsl/artifacts.py
nipype/workflows/smri/freesurfer/autorecon1.py
nipype/workflows/smri/freesurfer/autorecon2.py
nipype/workflows/smri/freesurfer/autorecon3.py
nipype/workflows/smri/freesurfer/ba_maps.py
nipype/workflows/smri/freesurfer/recon.py
nipype/workflows/smri/niftyreg/groupwise.py

With our (FMRIPREP/MRIQC) mismatched release cycles, we're running into the situation where correctly managing dependencies puts an undue burden on users (at least those installing natively, rather than running the Docker/Singularity images). We're attempting to move to include nipype as a submodule in niworkflows. Our projects will then import from `niworkflows.nipype`, which will avoid clashing with other installs of nipype.
Absolute imports assume that the root module is named `nipype`, where relative imports will permit (relatively) easy use as a submodule.
This should not affect the actual behavior of nipype at all, but will require that future PRs refrain from using absolute imports.
Changes proposed in this pull request:
- Move to relative imports in non-testing code

ENH: Reduce within-package absolute imports

---

nipype/interfaces/ants/registration.py
nipype/interfaces/ants/tests/test_auto_Registration.py

- Add `--restrict-deformation` option to antsRegistration interface

ENH: Add --restrict-deformation option to antsRegistration

---

nipype/pipeline/plugins/pbs.py

- PBSPro version listed below does not return Unknown Job Id when a job has finished to stderr, instead it returns a message to stderr saying that the job has finished, recommending a command to access completed job details.
- This means that the _is_pending command continually reruns every 2 seconds (waiting for the job to complete)
- the _fix_ for this is to check explicitly for the job finished message, and pass along that the job is no longer pending.
```bash
$ qstat --version
pbs_version = PBSPro_13.1.0.160576
```
All tests passed successfully with make check_before_commit

ENH: Handle PBSPro message when job completed

---

nipype/interfaces/fsl/ICA_AROMA.py

Fixes #2056 
Accidentally got rid of the necessary "isdefined" module when changing to relative imports. this  fixes the dependency.

FIX: added isdefined module to ICA_AROMA.py

---

nipype/interfaces/fsl/preprocess.py

- Add `FLIRT._log_written` flag to indicate whether to write the log. This prevents multiple calls to `aggregate_outputs` from cluttering the log.
- Some additional logic/style fixes in `_parse_inputs` while I was there.
- Don't overwrite a pre-existing skip list
- Take advantage of undefined traits evaluating `False`

ENH: Only write FLIRT log if not previously written

---

circle.yml
docker/base.Dockerfile

- Update pinned afni package
See also poldracklab/fmriprep#557

FIX: Update AFNI pin to current NeuroDebian package

---

nipype/utils/config.py

- Nipype by default should be stateless and not create any change outside of the directory it is called from.

fix: do not create a nipype folder in the home directory by default

---

nipype/interfaces/fsl/ICA_AROMA.py

I had a typo in the ICA_AROMA.py denoising documentation
none becomes no.

FIX: typo in ICA_AROMA.py

---

nipype/interfaces/base.py

Fixes #2068.
- Constrain environment dictionary to bytes in Windows
This filter is run just before the `Popen` call, which has the advantage that it will be very difficult for a unicode entry to slip through, but the disadvantage that any work that it does will be done many times. Still, it should be a cheap operation.

FIX: Constrain environment dictionary to bytes in Windows

---

nipype/interfaces/io.py
nipype/interfaces/tests/test_io.py

I ran into an issue where I wanted to use attribute access in the string format template I pass to `SelectFiles`, but due to some (imo, bizarre) [aspects](http://lucumr.pocoo.org/2016/12/29/careful-with-str-format/) of how format strings are implemented, the template key names were not getting properly parsed and turned into input fields.
If I have a template `"{group.name}'s template"`, then when the `string.Formatter().parse(template)` is called, it returns a key `"group.name"`. Python's string formatting then additionally processes this string with a private function that lives in different places on Python 2 and 3. The result of that processing grabs the `group` kwarg from call to `.format()` and accesses its `name` attribute. Rather than deal with private Python functions, I chose to …

ENH: Parse SelectFiles format keys to allow attribute access

---

nipype/interfaces/io.py

See https://github.com/nipy/nipype/issues/2091

Fix: String-based error inspection on Python 3

---

nipype/interfaces/dcm2nii.py

Fixes #2109.
- Add an extra term to search for in the dcm2niix stdout to detect for these dicoms.

FIX: fix for some missed DTIs during dcm2niix conversion 

---

nipype/interfaces/niftyseg/stats.py

Fixes StatsCommand in Niftyseg interfaces.
Changes proposed in this pull request:
- typo error line 78, it was UnaryStats instead of StatsCommand. 
- remove print statement in the StatsCommand.
Kind Regards,
Ben

FIX StatsCommand

---

nipype/algorithms/confounds.py
nipype/algorithms/tests/test_auto_ACompCor.py
nipype/algorithms/tests/test_auto_TCompCor.py
nipype/algorithms/tests/test_compcor.py
nipype/workflows/rsfmri/fsl/resting.py

- Adds a high-pass filter using the discrete cosine transform
- Enabled with `high_pass_filter`
- TR can be specified as an input or derived from the NIfTI header
- Cosine regressors can be saved
Todo:

ENH: Add cosine-basis high-pass-filter to CompCor

---

nipype/interfaces/ants/base.py

FIX: Do not assume githash in ANTs version

---

nipype/interfaces/freesurfer/longitudinal.py
nipype/interfaces/freesurfer/tests/test_auto_RobustTemplate.py

- Subclassing from FSCommandOpenMP enables the `num_threads` input
954f3b3 is the commit that matters. The style commit should have no semantic changes.

ENH: Subclass RobustTemplate from FSCommandOpenMP

---

nipype/algorithms/confounds.py

Follow-up to #2122.
- Use consistent (CamelCase) column headers for all columns in pre-filter file
- "SteadyState" => "NonSteadyStateOutlier" for accuracy
- "cos" => "Cosine" and "poly" => "Legendre" for descriptive clarity

ENH: Improve pre-filter column header names

---

nipype/info.py
requirements.txt
rtd_requirements.txt

This PR explores the issues with the currently failing builds.
Currently checking whether the prov 1.5.1 release is the issue.

FIX: Set prov==1.5.0 dependency

---

.zenodo.json
nipype/interfaces/io.py

- When finding files on S3 (using `S3DataGrabber`), the command ...
`bkt_files = list(k.key for k in bkt.list())`
... finds *all* files in a given bucket, which takes *very* long for the `openneuro` and `openfmri` buckets. On my computer, this command (using the example from `nipype/interfaces/tests/test_io.py`) takes 170 seconds. However, as proposed in my PR, when you use the `prefix` argument with the `bucket_path` in the `bkt.list()` call, it only takes 116 milliseconds. This is because it restricts the filesearch to *only* the files in the specified `bucket_path`. The interface still works when `bucket_path` is not set as input (i.e., it works with the default `''` value of the `bucket_path` parameter).
- Add name/affiliation to zenodo-file …

ENH: Speed up S3DataGrabber using prefix arg

---

doc/users/saving_workflows.rst
nipype/interfaces/utility/wrappers.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/utils/functions.py
nipype/utils/misc.py
nipype/utils/tests/test_functions.py
nipype/utils/tests/test_misc.py

Fixes #2060 #2038 .
- FIX: allow python 2 code in `Function` again

fix: python 2 Function interfaces recompatibility

---

nipype/interfaces/freesurfer/longitudinal.py

- Allows `transform_outputs=True` and `scaled_intensity_outputs=True` to create files with default names, rather than pre-specifying.
From the docs:
```
OPTIONAL FLAGGED ARGUMENTS
--lta <tp1.lta> <tp2.lta> ...
output xforms to template (for each input)
[...]
--iscaleout <is1.txt> <is2.txt> ...
output final intensity scales (will activate --iscale)
```

ENH: Add default transform, intensity scaling files to RobustTemplate

---

nipype/interfaces/fsl/dti.py

updated PR from #2168
- added `outputs['way_total']`, a default output
- changed target file for omatrix1's `outputs['network_matrix']` to `matrix_seeds_to_all_targets`, the correct probtrackx2 output file

FIX: update probtrackx2 outputs

---

nipype/interfaces/ants/legacy.py
nipype/interfaces/ants/segmentation.py

ANTs' ``buildtemplateparallel.sh`` and ``N4BiasFieldCorrection`` allow 4D images as input files. Nipype restricted the inputs to be 2D or 3D.

FIX: updates input spec to allow 4D images

---

nipype/pipeline/engine/tests/test_workflows.py
nipype/pipeline/engine/workflows.py

If the workflow contained an unconnected node with a duplicate name, the check failed with a nondescript `IndexError`, which required the user to either manually re-check their entire connections list for any errors at all, or hack the nipype code with print calls to find out which node is triggering the exception.
Now, the check gives the correct name duplication error and the name of the node, even if the node has no lineage.

FIX: Detecting and apropriately warning about unconnected duplicatlely nodes

---

doc/users/install.rst
examples/dmri_dtk_dti.py
examples/dmri_dtk_odf.py
examples/dmri_fsl_dti.py
examples/fmri_slicer_coregistration.py
nipype/info.py
nipype/interfaces/afni/base.py
nipype/interfaces/afni/preprocess.py
nipype/interfaces/cmtk/cmtk.py
nipype/interfaces/cmtk/nbs.py
nipype/interfaces/cmtk/nx.py
nipype/interfaces/cmtk/parcellation.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/tests/test_linear.py
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/pipeline/plugins/tests/test_multiproc_nondaemon.py
nipype/pipeline/plugins/tests/test_oar.py
nipype/pipeline/plugins/tests/test_pbs.py
nipype/pipeline/plugins/tests/test_somaflow.py
nipype/utils/misc.py
requirements.txt
rtd_requirements.txt

this is a replacement for #2171 to get merged so that master is back on track.
fixes #2159
fixes #2194
closes #2171
(Fix/close lines edited by @effigies)

fix for networkx and afni

---

nipype/interfaces/freesurfer/tests/test_utils.py

Fixes #2131.
- Do not run `MRIsExpand` interface, to avoid touching `$SUBJECTS_DIR/fsaverage/surf`.
Loses the verification that the command line is untouched by running. We could restore it by making a copy of the `fsaverage` directory instead, if it seems worth it.

TEST: Do not modify SUBJECTS_DIR contents

---

.travis.yml

This gives our dependencies a chance to break a Travis build before breaking everything downstream. I would treat failures of `--pre` builds as non-blocking for most PRs.

CI: Add pip install --pre entry to Travis

---

docker/base.Dockerfile

Since sourceforge is having some hiccups and we were using the outdated 1.0.0 version, this PR updates it to 1.1.0 and pulls it down from OSF, which seems more reliable.

[ENH] Update C3D version in nipype/base docker image

---

nipype/algorithms/rapidart.py

`algorithms.rapidart._calc_norm` uses an affine-based algorithm to calculate norms and displacements, translating from a list of motion parameters at each time point. This PR separates the two processes, creating a `_calc_norm_affine` function that performs the core functionality, which `_calc_norm` passes a list of affine matrices translated from the motion parameters.
- New function: `_calc_norm_affine`
- Update: `_calc_norm` translates motion parameters, calls `_calc_norm_affine`
- Removed `_nanmean`, since the minimum numpy (1.9) includes `np.nanmean`

RF: Separate mcparam -> affine translation from norm calculation in ArtifactDetect

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_Allineate.py

AFNI's `3dAllineate` accepts either float or dataset as weight

allow float as weight in afni's Allineate

---

nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/tests/test_auto_RobustRegister.py
nipype/interfaces/freesurfer/tests/test_preprocess.py

RobustRegister does not correctly return the full path to manually-specified `out_reg_file` names, and, if unspecified, creates them in the original folder.
- Make `out_reg_file` a normal `Either(True, File)` trait, with default value `True`
- `out_reg_file` is created in working directory by default
Also did some cleanup. See 5be5de94801bb9b07404a8c35d469f4d472fe241 for significant changes.

 FIX: Create out_reg_file correctly in RobustRegister

---

nipype/pipeline/plugins/base.py

#2200 added nice detailed stats, but by default it will print every 2s even with no change.
- Check for changes in statistics before printing
- Set standard progress report to DEBUG level

ENH: Reduce verbosity of distributed plugin

---

nipype/interfaces/freesurfer/preprocess.py

- Check value of `out_lta_file` rather than `out_fsl_file` when setting `outputs.out_lta_file`

FIX: Typo in BBRegister._list_outputs

---

nipype/interfaces/freesurfer/tests/test_auto_Tkregister2.py
nipype/interfaces/freesurfer/utils.py

- Add LTA input/output with inversion
- Reorganize input/output transforms to make future work on this interface a little easier
- Add an `xor` to `fstal` that follows this section of the help:
```
--fstal
Check and edit the talairach registration that was created during
the FreeSurfer reconstruction. Sets the movable volume to be 
$FREESURFER_HOME/average/mni305.cor.mgz and sets the registration file to be
$SUBJECTS_DIR/subjectid/transforms/talairach.xfm. User must have
write permission to this file. Do not specify --reg with this
flag. It is ok to specify --regheader with this flag. The format
of the anatomical is automatically detected as mgz or COR. By default,
the target c_ras is temporarily set to 0 to assure that the target
is properly …
```

ENH: Add LTA in/out to Tkregister2

---

nipype/interfaces/base.py

This adds `niworkflows.interfaces.base.SimpleInterface` to `nipype.interfaces.base`.
`SimpleInterface` is an interface that gives dictionary access to the output spec. We've found it a very useful boilerplate-reducer for making interfaces by simply defining input/output specs and `_results`.
Merging this would reduce friction for a lot of other poldracklab (niworkflows, mriqc, fmriprep) interfaces that people may want to see merged into nipype proper. I'm open to cleaning it up to be slightly less simple, as long as it achieves the same reduction in boilerplate in subclasses.
Slightly related: #2083
@oesteban EDITED: changed `_runtime` for `_results`.

ENH: Add SimpleInterface

---

CONTRIBUTING.md

- Link to a general guide for submitting a contribution
- Emphasizing the zenodo modifications

Contributor guide adjustments

---

README.rst

Quick fix.
Thanks for adding a CoC, @chrisfilo. Looks imminently reasonable.

DOC: README is .rst, not .md

---

nipype/interfaces/base.py
nipype/utils/filemanip.py

Replace chars when standard out can't be decoded

---

nipype/utils/profiler.py

[FIX] Resource monitoring minor bugfix

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_Qwarp.py

Afni qwarp output paths

---

nipype/interfaces/fsl/epi.py

eddy_openmp is placed in the $FSLDIR/bin directory not the $FSLDIR directory
Fixes # 1.
- Single minor bug-fix, which is needed to actually run eddy_openmp (if available) rather than eddy
I'm not sure how to test for this as the result depends on the content of $FSLDIR/bin

BUG: check for eddy_openmp in the right place

---

nipype/interfaces/ants/resampling.py
nipype/interfaces/ants/tests/test_resampling.py

I added a set of simple tests, mostly based on doctest, but just testing a few different scenarios.
Have 2 xfail test for wrong (i.e. out of range) `invert_affine`. Should this raise exception?

changing _format_arg in WarpImageMultiTransform, should fix #2192 

---

nipype/interfaces/base.py

When running large nipype graphs, the open file-descriptors end up provoking OSError 12 (could not allocate memory).

[ENH] Close file descriptors

---

nipype/interfaces/afni/base.py
nipype/interfaces/ants/base.py
nipype/interfaces/base.py
nipype/interfaces/freesurfer/base.py

Fixes #2273.
- Create `PackageInfo` template that reads version information from a file or command output, passes to a subclass-defined parser, and stores the result for future calls
- Example subclasses for AFNI, ANTs and FreeSurfer

Memoize version check

---

nipype/interfaces/afni/preprocess.py

in `afni.preprocess`, used to debug I guess

remove useless printing

---

nipype/workflows/fmri/fsl/preprocess.py

helps with poldracklab/fmriprep#706
- add `list_fwhms` option to `create_susan_smooth` to allow a list of fwhms to be run, instead of one.

[ENH]: add list_fwhm option to create_susan_smooth

---

.circleci/config.yml

Fixes breaking CircleCI deploy step.
- Use higher compression ratio when saving Docker images to `tar.gz` file.
The lowest amount of compression created a tar.gz file of over 5.0 GB. Persisting this to the CircleCI workspace did not show errors, but the tar.gz file in the next step of the workflow would be empty. This caused `docker load` to fail. More compression leads to a tar.gz file that is about 4.7 GB. This relatively smaller file can be loaded in the next step of the CircleCI workflow.
In a future PR, the Nipype container will be minimized with ReproZip. This will create smaller containers and alleviate the issue that this commit aims to fix.

FIX: use gzip compression -6 instead of -1

---

doc/users/plugins.rst
nipype/pipeline/plugins/multiproc.py

To avoid the workers to grow too big. Offer one new plugin_args to modify this option.
Now testing if this alleviates in any ways the memory issues we are experiencing in poldracklab/fmriprep#833.

[ENH] Set maxtasksperchild in MultiProc Pool

---

.circleci/config.yml
docker/generate_dockerfiles.sh

Fixes issue where download steps in `docker build` fail, causing CircleCI build to fail.
- Use newer version of `neurodocker` to generate Dockerfiles. The newer version includes `--retry 5` in `curl` commands to retry downloads.
- Build the base Docker image in a loop, and try building at most 5 times.

TST+ENH: update neurodocker version + retry building base image

---

nipype/pkg_info.py

Fixes #1970 , partly #2281  .
- encode the opening of `COMMIT_INFO.txt` to avoid unicode problems within configparser (python 2 compatibility)

fix: ensure encoding when opening commit info

---

.circleci/config.yml

(Actually) Fixes breaking deploy step in CircleCI.
- Do not save an empty `tar.gz` file in container 1-3. The empty files overwrote the `tar.gz` file of Docker images, causing `docker load` to fail.
- Persist `/tmp/docker/*` instead of `/tmp/docker/nipype-base-latest-py36-py27.tar.gz`. This will save the tarball of Docker images in container 0 and will not fail on containers 1-3.
- Use fastest `gzip` compression. Turns out this was not the issue.
Tests of this PR on my fork
- [changes with `gzip -6 ...`](https://circleci.com/gh/kaczmarj/nipype/348)
- [changes with `gzip -1 ...`](https://circleci.com/gh/kaczmarj/nipype/353)
Fastest `gzip` produces a 5.1 GB file in 9:30, and `gzip -6` produces a 4.7 GB file in 16:04. Fastest `gzip` compression results …

TST+FIX: do not save empty tar.gz file + use fastest gzip compression

---

nipype/interfaces/ants/segmentation.py

Interface `ants.BrainExtraction` had problems determining `$ANTSPATH`. This PR fixes the issue, and improves the error messages.

[FIX] Improve determination of ANTSPATH in BrainExtraction interface

---

nipype/interfaces/ants/registration.py
nipype/interfaces/ants/tests/test_registration.py

I've changed `metric_weight` (took default from other interfaces) and `radius` (left without default value).
Unfortunately other interfaces from that file have similar problems (do not work after providing all mandatory fields) and it was already reported in #529.
I can keep adding `mandatory` to traits and guessing default values, but it might be better for those interfaces if someone who is using them do it (or help me).

changing ANTS input traits, fixes #2245

---

nipype/interfaces/base.py

Fixes #2326.
- Correctly iterate over dict
- Encode val, instead of key
Suspect we got away with this because Windows use is small.

FIX: Environment canonicalization bugs

---

nipype/pipeline/plugins/multiproc.py

With large numbers of processors, moderate (~1GB) increases in memory consumption can produce large spikes in memory committed by the kernel when a batch of processes is forked. For example, if 16 1-core nodes are executed in one round of the MultiProc scheduler, then 16x the virtual memory footprint of the main process is committed by the kernel - so a 500MB increase in main process size would correspond to an 8GB increase in committed memory. For systems which disallow over-commitment of memory, these brief spikes can produce crashes even if the maximum resident memory never approaches the system limits.
This PR adds garbage collection at two points to reduce the memory footprint before forking and after running nodes in the main process, which has the most potential to accumulate …

ENH: Explicit garbage collection in MultiProc

---

nipype/pipeline/plugins/base.py

This PR introduces a minimal modification to the logging trace that happens when a node has been run, in order to provide more detailed information and whether the node was cached or actually run.

[ENH] Logging - indicate whether the node was cached

---

nipype/pipeline/plugins/multiproc.py

When the verbosity of logs is >= INFO, a list of currently running tasks is generated and printed out. Also, a `[MultiProc]` prefix is added to logging traces from this module.

[ENH] Logging - MultiProc report current tasks

---

nipype/pipeline/plugins/base.py

This change directs nipype to attempt constant-interval poll loops, rather than constant-sleep poll loops.
This is (kind of) a complement to #2315, to prevent additional work, such as garbage-collection from adding to the time between loops. 
- Constant-interval loops in DistributedPluginBase
- PEP8/pyflakes cleanup

ENH: Improve loop timing in DistributedPluginBase

---

nipype/interfaces/base/core.py
nipype/pipeline/engine/utils.py
nipype/utils/profiler.py

Given that some systems are limited on virtual memory allocation, and not actual memory consumption, being able to profile both memory metrics would be useful

ENH: Profile VMS as well as RSS

---

nipype/interfaces/freesurfer/tests/test_auto_SampleToSurface.py
nipype/interfaces/freesurfer/utils.py

Close #1078 as this PR supersedes it

[FIX] Fix surf_reg input trait

---

CHANGES
nipype/interfaces/afni/utils.py

Fixes https://github.com/poldracklab/mriqc/issues/677
- more robust handling of 3dFWHMx outputs

Fix 3dFWHMx outputs

---

nipype/pipeline/plugins/multiproc.py

Fixes #2372.
- Return to a more explicit technique for collecting available job IDs, which does not depend on newer numpy
cc @divetea @oesteban @mgxd

FIX: Collect jobids in a numpy 1.9 compatible manner

---

.gitignore
nipype/pipeline/engine/nodes.py

Fixes [#2325 (comment)](https://github.com/nipy/nipype/pull/2325#issuecomment-356485950).
- move some logging to `.format` substitution
Eventually, we should be thorough and replace most `%` substitutions

fix: logging error if % in node cmd

---

nipype/pipeline/engine/utils.py
tools/interfacedocgen.py

graph.png and graph.dot side by side is a lot better than graph.dot.png and graph.dot - for both tab completion, and software which has trouble intelligently parsing extensions (e.g. LaTeX's \includegraphics).
reiteration of #2268

No longer concatenating extensions

---

nipype/interfaces/afni/base.py
nipype/interfaces/base/core.py
nipype/interfaces/base/tests/test_core.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/minc/minc.py
nipype/utils/filemanip.py

This PR adds a `_cmd_prefix` which is a string that is prepended (with no space) to the command. This will permit users to add installation-specific prefixes, whether they be installation directories that are not in the path or idiosyncratic names that have been chosen by a package manager.
The idea is that users could do something like:
```Python
import nipype
nipype.interfaces.ants.AntsCommand._cmd_prefix = '/opt/ants/'
```
or
```Python
import nipype
nipype.interfaces.fsl.FSLCommand._cmd_prefix = 'fsl_'
```
Fixes #1415.
cc @satra @TheChymera

ENH: Add _cmd_prefix class variable to CommandLine

---

examples/nipype_tutorial.ipynb
nipype/pipeline/engine/utils.py

Only colored and hierarchical graphs are currently renamed to drop the `.dot` from the filename when converted to PNG or SVG.
The relevant branch is here: https://github.com/nipy/nipype/blob/a2d054aa8feb9c278c2b0503cc2fd4a9d3d4583c/nipype/pipeline/engine/workflows.py#L429-L450
- Factors out the renaming logic and updated command line from #2381 and calls from both `export_graph` and `format_dot`.
Follow-up to #2381.
Would appreciate review from @TheChymera and @djarecka.

RF: Use consistent dot file renaming scheme

---

CONTRIBUTING.md
doc/devel/interface_specs.rst

Updates the contributing guidelines and linked documentation.

[DOC] Update CONTRIBUTING [skip ci]

---

nipype/interfaces/afni/model.py
nipype/interfaces/afni/tests/test_extra_Deconvolve.py

- Patches cbucket output for 3dDeconvolve
- Correctly parses output of 3dSynthesize

[FIX] Bug fixes for afni.model

---

doc/users/saving_workflows.rst
nipype/workflows/smri/ants/ANTSBuildTemplate.py
nipype/workflows/smri/ants/antsRegistrationBuildTemplate.py

[FIX,WIP] Setting inputs.ignore_exception

---

doc/users/saving_workflows.rst
nipype/interfaces/base/core.py
nipype/workflows/smri/ants/ANTSBuildTemplate.py
nipype/workflows/smri/ants/antsRegistrationBuildTemplate.py

[FIX] Make ignore_exception a class attribute

---

nipype/interfaces/afni/model.py
nipype/interfaces/afni/tests/test_auto_Deconvolve.py

I thought I already added this fix in https://github.com/nipy/nipype/pull/2334, but it somehow reverted back when pep8ified. 
- Fix ortvec argstr

FIX: fix ortvec argstr for Deconvolve

---

nipype/caching/memory.py

Fixes the lesser part of #2406.
Bug introduced in 6c6cd787e71ca730fceae0764a2f55dacdd5baf4.
- Replace curly brace with close paren to create a valid format string

FIX: PipeFunc __repr__ format string

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_BlurToFWHM.py

Fix argstr for mask input in BlurToFWHM

FIX: argstr for mask in BlurToFWHM

---

nipype/algorithms/icc.py

Fixes #2421 .
- `sessions_F_map` was removed in d1ad1f9dd542d1489489e813ad8ddd5d22df5f7d, removing the last instance of it from `ICC._list_outputs`

fix: remove deprecated output from _list_outputs

---

nipype/interfaces/afni/tests/test_auto_Merge.py
nipype/interfaces/afni/tests/test_auto_Zcat.py
nipype/interfaces/afni/utils.py

little bugs make `afni.Zcat` and `afni.Merge` crash when the out_file is kept as default.

fix little out_file  bugs in  afni.Zcat and afni.Merge

---

nipype/pipeline/plugins/base.py

This PR forces running a node if an Exception is raised when checking its hash. In that situation, a warning with the traceback is logged.

[ENH] Delay crashing if exception is raised in local hash check

---

nipype/interfaces/base/traits_extension.py
nipype/interfaces/spm/preprocess.py

Fixes #2406. Essentially reverts #2375, but using `InputMultiPath` instead of `Either`.
- Re-enables spm.Realign to take lists of lists, using nested `InputMultiPath`s.

ENH: Re-enable spm.Realign to take lists of lists of files

---

.travis.yml

Lately, travis builds had 1 or 2 builds within the matrix that would time-out, probably due to run-on functions.
- split up long `apt_inst` and `conda_inst` functions into one or two step commands.
- makes `.travis.yml` file more explicit

enh: improve travis build reliability

---

nipype/pipeline/engine/base.py
nipype/pipeline/engine/tests/test_base.py

fix: set _id property of cloned node too

---

nipype/interfaces/io.py

There are two other classes in the io.py file, they maybe have the same problem, if you think my change works, you can also change the other two classes.

bug for datagrabber

---

codecov.yml

This is an attempt to get more accurate coverage reports. Follow-up to #2386, which re-enabled codecov uploads. Will update the following list to reflect steps taken.
1. Removing tests directories, to reduce noise in report

[WIP] COV: Ignore tests in calculating coverage

---

docker/files/run_pytests.sh

Creating a PR just to get Circle moving. I'm not sure if this will make any difference to coverage.

CI: Add doctests to pytest script

---

.circleci/config.yml
.travis.yml
docker/generate_dockerfiles.sh

Travis builds on master are failing, apparently because of today's miniconda release, which bundled asn1crypto 0.24. Possibly rolling back to 0.23 will fix the issue.

CI/DOCKER: Hard code miniconda 4.3.31

---

.zenodo.json
nipype/algorithms/confounds.py

Fixes [#2456](https://github.com/nipy/nipype/issues/2456) .
- extract unit information from image header, rather than from image directly

Fix: Extract unit information from image header in CompCor

---

nipype/interfaces/diffusion_toolkit/dti.py

The bvecs file was read assuming that directions followed YZX order, which created a gradients_matrix.txt with swapped directions. The new order is XYZ.
Closes #2435.

[FIX] #2435 Error creating gradients in DTIRecon

---

doc/links_names.txt
doc/users/install.rst
doc/users/neurodocker.rst

Fixes #2439.
- Add a brief Neurodocker tutorial to the documentation (would be available at https://nipype.readthedocs.io/en/latest/users/neurodocker.html)
- Add links to Neurodocker tutorial in https://nipype.readthedocs.io/en/latest/users/install.html.
- Add links to Singularity and Neurodocker in `link_names.txt`.

DOCS: add brief neurodocker tutorial

---

.zenodo.json
nipype/interfaces/niftyreg/regutils.py
nipype/interfaces/niftyreg/tests/test_auto_RegTools.py

Fixes #2470
Note: I ran `make check-before-commit` and got the following:
```
(nipype)  nipype   add-interp-to-niftyreg-regtools  make check-before-commit                                                                                           ◂◂◂◂◂◃◃◃◃◃
Checking specs and autogenerating spec tests
env PYTHONPATH=".:" python tools/checkspecs.py
File "tools/checkspecs.py", line 15, in <module>
from yapf.yapflib.yapf_api import FormatCode
ModuleNotFoundError: No module named 'yapf'
make: *** [specs] Error 1
```
I fixed it with `pip install yapf`.

ENH: Add interpolation order parameter to NiftyReg's RegTools

---

nipype/pipeline/engine/tests/test_join.py
nipype/pipeline/engine/utils.py

Fixes #2257.
- Add test to replicate #2257.
- Apply fix suggested by @williford.

FIX: Check against full node name when reconnecting JoinNodes

---

requirements.txt
rtd_requirements.txt

These entries weren't synced with the versions listed in `nipype/info.py`.

DEP: Sync requirements with info.py

---

.travis.yml
docker/generate_dockerfiles.sh

Tracks fixes to miniconda. Tests should be periodically rerun, to see if Continuum is fixing things on their end.
Follow-up to #2454.

CI: Update Travis builds, Docker to use latest miniconda

---

CONTRIBUTING.md
nipype/info.py

MAINT: Add dev install option, update CONTRIBUTING

---

CONTRIBUTING.md

- Update CONTRIBUTING.md to direct new contributors to the `orphaned` tag

DOC: Describe 'orphaned' tag in CONTRIBUTING

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Fixes #2473.
Follow-up to #2444 and #1941.
- Log a debug message on parse failure.
- Separate matching from retrieving, to enable error checking.
- Ignore blank lines. These shouldn't happen, but we shouldn't be sensitive to them.
- Simplify regular expression by enumerating stop conditions in fstype group.
@yarikoptic Can you verify this resolves your issue?

FIX: Check and report mount table parsing failures

---

nipype/utils/nipype2boutiques.py
nipype/utils/tests/test_nipype2boutiques.py

fix: handle automatic module creation, name extraction, default value

---

CONTRIBUTING.md
doc/devel/testing_nipype.rst

I've change Nipype testing section and slightly change `Contributing.md`. 
I did include changes in doc from #2477, I will resolve conflict after merge.
About Nipype testing section:
- I've tried to remove as much as I could. I was checking suggestions regarding settings env variables on my OSX and within Linux container, and if I didn't find that they are needed I just removed the section.
- I didn't know what to do with `MATLABCMD` suggestion for `Debian`. I can see that `MATLABCMD` is different in the Debian container (`/opt/mcr/v92/toolbox/matlab`), but would need some help to create a more general form of this suggestion.
- I've decided to use `pytest` command as **the** way of testing (just to simplify, I haven't removed anything from `Makefile`)
- in the Docker section I decided to …

Updating contributing and testing (closes #2445)

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

All AFNI commands work also on files with extension `.niml.dset` (for surfaces).
- consider `*.niml.dset` as special extension to correctly split filenames

FIX: mark .niml.dset as special extension in utils.filemanip

---

nipype/interfaces/fsl/model.py

@jokedurnez This is the fix you suggested in #2073. I'm reading the second comment in that thread as verification that it successfully did what you intended, but I just want to double-check.
Fixes #2073.
- Cherry-picked @jokedurnez's commit
- Minor refactor to reduce number of times the same string is calculated, and satisfy PEP8

FIX: FSL orthogonalization bug

---

nipype/pipeline/engine/nodes.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

This fix supports an earlier ridiculous hack (#1857) that was broken by properly managing working directories (#2368).
Fixes #2518.
- Construct `cmdline` within the working directory, for the probably one case in which the `cmdline` depends on the working directory.
- Adds and tests an `indirectory` context manager, because I hate the `os.getcwd(); os.chdir(); CONTENT; os.chdir()` pattern.
There may be a more elegant way to get input traits into a file, but it's not clear to me what that is at this point, so I went for the cheap solution.

FIX: Build cmdline from working directory

---

.circleci/config.yml
tools/retry_cmd.sh

Fixes #2489.
- Add `retry_cmd.sh` script
- Replace loops in `.circleci/config.yml`

CI: Add retry script for Docker commands

---

nipype/interfaces/afni/tests/test_auto_CatMatvec.py
nipype/interfaces/afni/utils.py

Fixes #2526  .
- use `name_template` and `name_source` for generating the out_file
- add `_list_outputs` method

Fix catmatvec

---

nipype/interfaces/fsl/tests/test_auto_ImageMaths.py
nipype/interfaces/fsl/utils.py

[FIX] Add ``-mas`` argument to fsl.utils.ImageMaths

---

nipype/interfaces/ants/registration.py

Fixes #2543.
- `antsRegistrationSynQuick.sh -> antsRegistrationSyNQuick.sh` (note the "n" in "Syn")
I've checked back several versions of ANTs, and the script didn't change names. We just had a typo.

FIX: Typo in "antsRegistrationSyNQuick.sh"

---

nipype/interfaces/base/core.py
nipype/interfaces/base/specs.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py

Deprecation mark: https://github.com/enthought/traits/blob/a99b3f64d50c5f7f28ffc01bf69419b061f9e976/traits/has_traits.py#L1481
Fixes the following deprecation warning:
```
nipype/nipype/interfaces/base/specs.py:160: DeprecationWarning: use "HasTraits.trait_get" instead
out = super(BaseTraitedSpec, self).get(**kwargs)
```
This warning has started to appear recently, traits must have gotten a major update.

FIX: Replace deprecated ``HasTraits.get`` with ``trait_get``

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_Allineate.py
nipype/interfaces/base/core.py

Fixes #2499, #2216 
-See linked issue #2499

[FIX] fix afni.allineate interface

---

nipype/workflows/dmri/fsl/utils.py

Fixes #1787
- applies the matrix transforms from the adjusted/enhanced non-B0 volumes to the original non-B0 volumes, so that the image intensities remain the same. Ideally flirt should just estimate/apply linear transforms, not change the image intensities. As @salma1601 mentioned, `exposure.equalize_adapthist` appears to be the culprit.
[example dwi data for testing](https://osf.io/hde8t/download)
[related code that _can_ be used for testing (with modification)](https://github.com/uiowa-mri-course-2018/Labs/blob/master/11-Lab/DWI.ipynb)

[FIX] return non-enhanced volumes from dwi_flirt

---

nipype/algorithms/misc.py

Following [Neurostars #1623](https://neurostars.org/t/attention-with-anonymization-and-gzipped-files-you-might-be-publishing-subject-information/1623), I checked on the nipype `Gzip` implementation. Apparently I misremembered, because I found `Gunzip` instead. Anyway, here are some cleanups and a doctest.
- FIX: `_gen_output_file_name` had a bad test for `.gz` extension
- ENH: Use `shutil.copyfileobj` to ensure more memory-friendly buffering
- TEST: Add doctest to demonstrate usage and verify filename change

FIX/TEST: Gunzip cleanup and test

---

nipype/interfaces/fsl/aroma.py

As reported here https://github.com/maartenmennes/ICA-AROMA/issues/25#issuecomment-386169296, ICA-AROMA changes of directory to allow for relative imports.
That is confusing Nipype's interpretation of the input. This workaround fixes poldracklab/fmriprep#1090.

FIX: Workaround to ICA-AROMA change of directory

---

.travis.yml

This should help identify whether code that's dependent on dependency versions is being exercised.

CI: Submit Travis results to codecov

---

nipype/interfaces/base/core.py
nipype/interfaces/mixins/__init__.py
nipype/interfaces/mixins/reporting.py

Related (closes?): #2553
- Adds pre- and post-run hooks to BaseInterface, which is intended to allow mix-ins to be more flexible about where exactly they fall within the method resolution stack.
- Creates `ReportCapableInterface` as a mix-in that is also written to work as a base class as well.
This factors out what seemed to be the essential parts of the niworkflows [`ReportCapableInterface`](https://github.com/poldracklab/niworkflows/blob/9d4163e30dae3caf7560313ef353d4177a38004f/niworkflows/interfaces/report_base.py#L23-L108).
Differences:
* Compression is removed as an option - without the actual figure generation and compression machinery, this would be under-supported. If these are worth adding, we can do so, but in point of fact we're …

ENH: ReportCapableInterface mix-in/base interface

---

.circleci/config.yml
.travis.yml

Closes #2313.
- Moves PyPI deployment to CircleCI
The Travis builds are a little weird in that, on tagging, the first to successfully complete will upload to PyPI, while the rest will fail. This seems unnecessary, and we might as well use the dependencies allowed by Circle 2.0 workflows.
This will need @satra's PyPI credentials stored properly in Circle before it makes sense to merge.
Testing everything but the `twine` upload.

CI: Move PyPI deployment to Circle 

---

nipype/pipeline/engine/tests/test_join.py
nipype/pipeline/engine/utils.py

Fixes #2578
Follow-up to #2479
- Narrow node name check to ensure `JoinNode`s aren't excluded incorrectly
- Add test

FIX: Correctly connect JoinNodes in nested iterables

---

nipype/pipeline/plugins/base.py

Fixing this: https://github.com/nipy/nipype/issues/2570
- calls to _clean_queue in plugins/base.py now always have the information about exceptions when it's available

FIX: Set default result in DistributedPluginBase._clean_queue

---

doc/users/config_file.rst
doc/users/debug.rst
nipype/utils/config.py
nipype/utils/tests/test_config.py

Fixes #1169
- Update logging levels in enable_debug_mode 
- Add a test

 FIX: Update logging levels in enable_debug_mode 

---

.travis.yml
nipype/conftest.py
nipype/interfaces/base/core.py
nipype/interfaces/dcm2nii.py
nipype/interfaces/image.py
nipype/interfaces/io.py
nipype/interfaces/niftyreg/regutils.py

Suggested in #2598. Will allow us to test more vanilla installations of Python.
Should speed up Travis builds, too.

CI: Stop using Miniconda on Travis

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_TProject.py
nipype/interfaces/ants/tests/test_auto_AntsJointFusion.py

Adds a -dsort option to ``nipype.interfaces.afni.TProject``

[ENH] add -dsort option to TProject

---

nipype/pipeline/plugins/tools.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Fixes #2625.
- Add a JSON header as metadata for the crash files, containing the original nipype version.
- When opening a crash file with the cli utility, it can check for the nipype version and warn the user about problems that different versions of nipype may generate when using the utility.
- It shows the version from the header.
- It works seamlessly with old versions.

ENH: Add versioning metadata to crash files

---

.circleci/config.yml

Should at least catch one surprise we ran up against today.
- Add README render check to `rel/*` branches to avoid one source of PyPI rejection

CI: Add PyPI validation on rel/* branches

---

nipype/pipeline/plugins/legacymultiproc.py

#2598 did not incorporate #2611's move to hierarchical loggers.
This is likely to be a breaking change for a lot of downstream users, so we should make a particular note of it in the release notes.

FIX: LegacyMultiProc workflow logger

---

nipype/pipeline/engine/nodes.py

I changed `abspath` to `realpath` in `Node._output_dir` to fix problems with temporary directories on OSX. `abspath` gives `/var/...` and `realpath` returns `/private/var...`.  In [`clean_working_directory`](https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/utils.py#L1385) we had `needed_files` that used `/private/var/...` and `cwd` used `/var/...`, so many files were removed.
I'm not sure if this is the best place to change the path, I can do it also in `clean_working_directory`, if for any reason we should keep `abspath` in `_output_dir`.
There is a chance that this will solve the general issue from #2395. For now it fixed all tests from `heudiconv`, so should also solve [this issue](https://github.com/nipy/heudiconv/issues/231)

changing Node._output_dir to realpath

---

.github/PULL_REQUEST_TEMPLATE.md

After our experience with https://github.com/poldracklab/fmriprep/blob/master/docs/pull_request_template.md, I apply here @effigies' suggestion of using HTML comments, and add a checkbox for the license.
Please, have a look into FMRIPREP's template to decide whether we want to import any more ideas into nipype.

[ENH] Minor improvements to PR template

---

nipype/interfaces/io.py

Fixes #2620.
- Try to connect to the bucket non-anonymously when there is no AWS credential, before trying the anonymous config
- It will give the possibility to use instance roles w/ S3 access, that is safer than dealing with secrets (recommended by AWS)

ENH: S3 access using instance role

---

nipype/interfaces/io.py
nipype/interfaces/tests/test_io.py

In future pybids versions, derivatives will not be automatically indexed, and test data has been added to help ensure that derivatives are properly handled.
This is a potentially breaking change, so we should consider if we would prefer some other approach.
Fixes #2650.
* Add `strict` input to `BIDSDataGrabber` that currently excludes `derivatives/`, `code/` and `sourcedata/` subdirectories from indexing.
* Only return images by default, per documentation.
* Make test more resilient by checking whether expected file is present, not first.

FIX: Various BIDSDataGrabber fixes

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_Warp.py

I added an option to save the warp from the stdout because it can be useful. But the warp transform is printed only if  `verbose` is set to True, otherwise the saved file is empty. I don't know if there is something like the `xor` and `requires` that checks if a required trait is set to True.

ENH: Allow transform to be saved from AFNI 3dWarp

---

doc/links_names.txt
doc/users/neurodocker.rst

- update [neurodocker tutorial](https://nipype.readthedocs.io/en/latest/users/neurodocker.html)
- update links to docker and singularity websites. The departing singularity website displays the message
> This website is going away soon! Update your bookmarks! Documentation is now hosted at https://www.sylabs.io/docs.
- docker.io redirects to docker.com, so i changed the link to docker.com.

DOC: update neurodocker tutorial for neurodocker version 0.4.0

---

nipype/info.py

Since we have `pytest` in `REQUIRES` I added also `pytest-xdist`, since this is now required to run `nipype.test()` (motivated by #2645)

MAINT: Make pytest-xdist a dependency

---

nipype/interfaces/tests/test_auto_BIDSDataGrabber.py

Follow-up to #2650.
* `make specs`

TEST: make specs

---

nipype/interfaces/freesurfer/preprocess.py

Fixes #2655. See discussion there for justification.
* Copy `FSCommand.version` to `ReconAll.version`

FIX: Copy FSCommand.version to ReconAll.version

---

Makefile
Vagrantfile
doc/links_names.txt
nipype/pipeline/plugins/tests/test_base.py
nipype/pipeline/plugins/tests/test_tools.py

MAINT: Remove vestiges of nose testing library

---

nipype/interfaces/fsl/epi.py
nipype/interfaces/fsl/tests/test_auto_TOPUP.py

This is follow-up to the #2533. I started from `topup`, issues were reported by @atsuch  in the comments to the PR.
- I removed the default values and `usedefault=True` and introduced default value in the description (it's probably better to let FSL set these values)
- fixing reg_labda input
If this is ok, I should probably add similar changes to other FSL interfaces changed in #2533

FIX: Un-set incorrect default options in TOPUP

---

.travis.yml

reverse #2659 
It looks like the new release of `xdist` resolve the dependencies better and `travis retry` not needed.

CI: removing travis_retry for pip install pytest xdist 1.22.5

---

.github/ISSUE_TEMPLATE.md

This will help make issues more readable by adding newlines and vertically aligning keys. Pretty-printing is a built-in, so no dependencies are needed.
I've also moved the suggestion to an HTML comment and provided pre-written triple ticks to help with formatting for new users.

Issue template: Pretty print platform details

---

nipype/pipeline/engine/tests/test_nodes.py
nipype/pipeline/engine/utils.py

The saving/loading of results in `Node` causes an `OutputMultiObject` that looks like `[[x]]` to be collapsed twice into `x`, as opposed to the expected `[x]`.
This PR detects collapses by performing a `clone_traits()`, which also collapses such traits, and wraps those values in a list.
Fixes #2670.
* Create a `_protect_collapses` helper function that mimics `trait_get`, but re-wraps collapsing traits in lists before returning the values.

FIX: Prevent double-collapsing of nested lists by OutputMultiObject

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/tests/test_auto_QwarpPlusMinus.py
nipype/interfaces/elastix/registration.py
nipype/interfaces/elastix/tests/test_auto_AnalyzeWarp.py

Fixes poldracklab/fmriprep#1236 .
As discussed in https://github.com/poldracklab/fmriprep/issues/1235#issuecomment-410752963, this PR strips down "helper interfaces" `_cmd` to only the executable, and adds the necessary arguments as defaults in the inputspec.

MAINT: ensure interface _cmd only includes executable

---

nipype/pipeline/engine/base.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/engine/utils.py

fixing the detailed graph and printing `workflow.run().nodes() ` for workflows with iterables, the issue was due to the changes in the node `__str__`/`__repr__`
Fixes #2668

FIX: Node __repr__ and detailed graph expansion

---

nipype/interfaces/io.py
nipype/interfaces/tests/test_io.py

PyBIDS just renamed `bids.grabbids` to `bids.layout` (INCF/pybids#230). Althrough `grabbids` links back to `layout`, we look for files through the filesystem, which didn't survive the change.
This change should handle the new layout without breaking backwards compatibility.
@adelavega @tyarkoni I would appreciate reviews from you.

FIX: Read BIDS config.json under grabbids or layout

---

.circleci/config.yml

```Shell
conda create -y -n test python=3.6
source activate test
pip install nipype==1.1.1
pip show futures
```
Output:
```
Name: futures
Version: 3.1.1
Summary: Backport of the concurrent.futures package from Python 3.2
Home-page: https://github.com/agronholm/pythonfutures
Author: Brian Quinlan
Author-email: brian@sweetapp.com
License: PSF
Location: /anaconda3/envs/test/lib/python3.6/site-packages
Requires: 
Required-by: nipype
```
This PR will attempt to ensure the wheel is correctly created to only install `futures` in Python 2. My suspicion is that upgrading setuptools before building the wheel is the correct fix.
I suggest that we add a hot-fix release, so that downstream Python 3 packages can stop installing `futures` ASAP.

MAINT: Fix wheel build to ensure futures is only required in Python 2

---

.circleci/config.yml
doc/changelog/1.X.X-changelog

Hot-fix release. Aiming for some time tomorrow.
@mgxd I don't think I have the scripts to update `.zenodo.json`. If you get a minute, could you do that?
@djarecka Could you test the tutorials?

REL: 1.1.2

---

.circleci/config.yml
.travis.yml

* Add Python 3.7-dev to test matrix
* Remove "fmri" extra removed in 3500213074f28def0f011ff59a1519fb2fd377b4
@satra Should `fmri` instead be replaced with `nipy` in Travis?

CI: Test 3.7, resume testing nipy extras

---

README.rst
doc/_templates/indexsidebar.html
doc/devel/gitwash/known_projects.inc
doc/devel/interface_specs.rst
doc/links_names.txt

I was trying to find the right place to ask a question and these links were both broken so I figured I'd send a little PR to update the two places to ask questions as linked from the index bar.
*updated*: I've also done a quick search for other instances of the old mailing list link and updated those.
Additionally I've added the gitter and slack links. Happy to remove those if you don't want to provide so many options!
Please disregard this pull request if this isn't correct or helpful! Very happy to adapt anything that's needed.
Changed links:
* http://neurostars.org/t/nipype
---> https://neurostars.org/search?q=nipype
* http://projects.scipy.org/mailman/listinfo/nipy-devel ---> https://mail.python.org/mailman/listinfo/neuroimaging
Added links to 
* https://gitter.im/nipy/nipype
* …

[DOC] Update links to user and developer help forums

---

nipype/interfaces/utility/base.py

Rename calculates the output path twice, in `_run_interface` and `_list_outputs`. By moving to `SimpleInterface`, we can calculate the path once, and use `runtime.cwd` as insurance against unexpected working directory changes.
Fixes #2687.
* Add `SimpleInterface` as mixin to `Rename`
* Calculate output path via `runtime.cwd`

RF: Use runtime.cwd in Rename

---

nipype/utils/misc.py

I've modified the docstring in the function normalize_mc_params, after discussing with @satra.
There was a mismatch in the description of the parameters ry and rz.
ry -> roll, rz -> yaw
Fixes # .

DOC: Fix naming of motion parameters (roll/yaw swapped)

---

nipype/pipeline/plugins/slurm.py

Related to #1853 .
* Catch slurm `squeue` error when jobid has completed/terminated

FIX: SLURM plugin polling

---

nipype/interfaces/fsl/preprocess.py

MCFLIRT creates optional outputs in the same directory as the `out_file`, regardless of whether that happens in the current working directory.
Fixes #2698.
* Determine output directory from `out_file`

FIX: Construct MCFLIRT output paths relative to out_file

---

.travis.yml
nipype/info.py

This is just a patch to attempt to pin pybids to 0.6.5, until we updates the interfaces that depend on pybids.

[FIX] Lock travis pybids 0.6.5

---

nipype/pipeline/engine/utils.py

[FIX] Keep profile files with ``remove_unnecessary_outputs = true``

---

doc/conf.py
docker/generate_dockerfiles.sh

Closes https://github.com/nipy/nipype/issues/2713.
Small PR that takes care of the readthedocs build error mentioned under https://github.com/nipy/nipype/issues/2713.
The problem was that `matplotlib` version 3.0.0 doesn't include the `sphinxext.only_directives` anymore.

FIX: corrects readthedocs build error

---

nipype/interfaces/mrtrix3/base.py
nipype/interfaces/mrtrix3/reconst.py
nipype/interfaces/mrtrix3/tests/test_auto_FitTensor.py

- remove `regularisation` (`reg_term`) option from MRtrix3 dwi2tensor interface.
This option was removed as part of refactoring in:
https://github.com/MRtrix3/mrtrix3/commit/9b886a94289a
Fixes
```
dwi2tensor: [ERROR] unknown option "-regularisation"
```

FIX: Remove 'reg_term'/'regularisation' from dwi2tensor interface

---

nipype/interfaces/ants/segmentation.py

Without this fix it
- looks for the wrong file whenever `output_name` is not provided (Closes #2733)
- keeps looking for the wrong file even if name is provided

FIX: Reuse _gen_filename logic in ants.LaplacianThickness

---

nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/tests/test_auto_LaplacianThickness.py

[ENH] Update ``ants.LaplacianThickness`` to use ``name_source``

---

nipype/interfaces/fsl/utils.py

The current implementation of FSL's split selects all files that start with `vol*` (or the specified prefix) as output.
This caused a problem in my setup, because I had additional files in the same folder, that started with `vol_*`. This small PR corrects this, by forcing the output to start with a number.

FIX: Refine FSL.split output identification

---

nipype/interfaces/fsl/dti.py
nipype/interfaces/fsl/tests/test_auto_DTIFit.py

Add Sum-Squared-Error to DTIFit output.
Fixes #2743  .
* add 'sse' to DTIFitOutputSpec
* add logic to ignore this output if the corresponding input-flag was not set
I was not able to run the tests since i cannot install all requirements on my work system.
My changes are very similar to the already existing 'save_tensor' input with 'tensor' output.
The logic to only add the output if the corresponding input-flag was defined and set to True, was only tested manually with an example dataset, since it depends on the actual output/file creation!
I did not find any tests for the 'save tensor' -> 'tensor' input-output pair, so i had no orientation how to approach this for my new output.
In fact i did not find any tests that go further than the correct assembly of the cmdline.
I think the …

ENH: Add 'sse' output to FSL DTIFit interface

---

nipype/interfaces/meshfix.py
nipype/interfaces/tests/test_auto_MeshFix.py

VRML is a [format](http://www.web3d.org/documents/specifications/19776-2/V3.3/index.html), VMRL doesn't seem to be, so it looks like the opposite of the problem I thought we had in #2755.
@martingrignard can you pull this branch and verify that it resolves your issue?
Fixes #2755.
* Change `save_as_vmrl` to `save_as_vrml`

FIX: VRML typo (VMRL) in MeshFix

---

nipype/pipeline/plugins/legacymultiproc.py

Fixes #2745.
Python 2.7, 3.4-3.7.0, and 3.7.1 all have different interpretations of `Pool.Process`.
In [Python 2.7](https://github.com/python/cpython/blob/4a59c9699ca8688359c460f98127a12e2db6e63b/Lib/multiprocessing/pool.py#L132-L136), it's a class:
```Python
class Pool(object):
'''
Class which supports an async version of the `apply()` builtin
'''
Process = Process
```
In [Python 3.4](https://github.com/python/cpython/blob/cd1d5c554c40b5b348de2e77d65986aa154e4477/Lib/multiprocessing/pool.py#L138-L145)-[3.7.0](https://github.com/python/cpython/blob/1bf9cc509326bc42cd8cb1650eb9bf64550d817e/Lib/multiprocessing/pool.py#L146-L153), it's a method that calls `self._ctx.Process`:
```Python
class Pool(object):
'''
Class which supports an async version of applying functions to arguments.
''' …
```

FIX: Python 2.7-3.7.1 compatible NonDaemonPool

---

.zenodo.json
nipype/interfaces/afni/preprocess.py

Fixes #2752 
* adds slice_encoding_direction input to TShift
* if `slice_encoding_direction == k-`, reverse `slice_timing`

[ENH] added slice_encoding_direction input to TShift

---

nipype/interfaces/bru2nii.py
nipype/interfaces/tests/test_auto_Bru2.py

ENH: Added support for Bru2's -z compress option

---

nipype/pipeline/plugins/legacymultiproc.py

Attempting to pickle `Process`es or `Pool`s directly fails, so I've been unable to figure out how to test pickling except to reproduce the condition that leads to this, which is to run fMRIPrep with the `LegacyMultiProc` plugin. See https://circleci.com/gh/effigies/fmriprep/2200.
Will test by patching into fMRIPrep.
Update: Working as of f1f3845: https://circleci.com/gh/effigies/fmriprep/2224?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Related to #2754, poldracklab/fmriprep#1363 and poldracklab/fmriprep#1368.
* Python 2.7: Reverts to file-level `NonDaemonProcess` definition
* Python 3.x: Subclasses all `Process` and `multiprocessing.Context` variants, and selects these variants in `NonDaemonPool`.

RF: Subclass non-daemon variants of all multiprocessing contexts

---

nipype/pipeline/plugins/base.py
nipype/pipeline/plugins/linear.py

This makes error reporting more consistent and helps building apps (such as fmriprep) on top of nipype.

ENH: Create a crashfile even if 'stop_on_first_crash' is set

---

nipype/info.py

Addresses the [numpy
bug](https://www.opensourceanswers.com/blog/you-shouldnt-use-python-37-for-data-science-right-now.html).
Fixes # .

[PIN] Force numpy>=1.15.4 when Python>=3.7

---

nipype/interfaces/base/core.py
nipype/interfaces/base/support.py
nipype/utils/subprocess.py

This PR just reorganizes minimally the source code to prepare for #2776.

[MAINT] Move ``interfaces.base.run_command`` to ``nipype.utils.subprocess``

---

doc/_templates/navbar.html

This PR proposes using https instead of http for the stylesheet https://www.google.com/cse/style/look/default.css. Currently, Chrome 70.0.3538.102 on macOS blocks that stylesheet from being loaded via http, with the error:
> Mixed Content: The page at 'https://nipype.readthedocs.io/en/latest/index.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://www.google.com/cse/style/look/default.css'. This request has been blocked; the content must be served over HTTPS.
- Use https instead of http for stylesheet

DOC: use https in css stylesheet url

---

nipype/pipeline/plugins/multiproc.py

For Python 3.7+, `concurrent.futures.ProcessPoolExecutor` can take initialization arguments and a multiprocessing context. This will allow Python 3.7 users to recover some of the lost flexibility of `LegacyMultiProc`.
* Add `mp_context` PluginArg for `MultiProc`.
* Restore initialization arguments

ENH: Add mp_context plugin arg for MultiProc

---

.zenodo.json
nipype/interfaces/meshfix.py
nipype/interfaces/tests/test_auto_MeshFix.py

This PR allows to use `--fineTuneIn` and `--fineTuneOut` instrutions from MeshFix input spec.
Fixes #2770 .
- Add description to `--fineTuneIn` MeshFix input spec.
- Set the order of the `--fineTuneIn` and `--fineTuneOut` MeshFix arguments.
- Fix the fact that the command for `--fineTuneOut` was actually `--fineTuneIn` due to a copy-paste.

Fix --fineTune arguments order for MeshFix command

---

nipype/pipeline/engine/workflows.py

When calling ``workflow.run(plugin=MultiProcPlugin())``, MapNodes are set the ``use_plugin`` member that is not pickleable if ``plugin`` is a ``MultiProcPlugin`` object.
Fixes # .

[FIX] MapNodes fail when ``MultiProcPlugin`` passed by instance

---

nipype/algorithms/confounds.py
nipype/algorithms/mesh.py
nipype/algorithms/misc.py
nipype/algorithms/modelgen.py
nipype/interfaces/base/core.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/tracks.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/fsl/base.py
nipype/interfaces/mrtrix3/base.py
nipype/utils/filemanip.py

Trying to avoid:
```
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

[MAINT] Stop using deprecated ``logger.warn()``

---

nipype/pipeline/engine/utils.py

Fix this warning that is populating nipype logs lately.

[MAINT] DeprecationWarning: use ``HasTraits.trait_set`` instead

---

nipype/interfaces/base/traits_extension.py

[MAINT] Import only Sequence to avoid DeprecationWarning

---

nipype/interfaces/base/core.py
nipype/interfaces/base/specs.py
nipype/interfaces/base/tests/test_core.py
nipype/interfaces/base/tests/test_specs.py
nipype/interfaces/freesurfer/base.py
nipype/interfaces/freesurfer/utils.py
nipype/pipeline/engine/nodes.py

This PR outsources the responsibility of gathering ``copyfile`` information from the input spec.

[MAINT] Outsource ``get_filecopy_info()`` from interfaces

---

.circleci/config.yml
.zenodo.json
doc/changelog/1.X.X-changelog
nipype/info.py
nipype/interfaces/tests/test_auto_MeshFix.py

Prep for 1.1.6 release, targeting Monday, November 26.

REL: 1.1.6

---

nipype/pipeline/plugins/linear.py
nipype/pipeline/plugins/tests/test_callback.py

Some tests were randomly failing in Travis for the Linear plugin. My
suspiction is that some other test changed the configuration of
``stop_on_first_crash`` and depending on the ordering tests were
actually run, this test would sometimes fail, apparently at random.
The tests have been expanded to test also LegacyMultiProc and to check
under both conditions (stop_on_first_crash on/off).
Fixes # .

[FIX] ``status_callback`` not called with ``stop_on_first_crash``

---

nipype/interfaces/spm/preprocess.py

* In SPM12, for Segment module (the NewSegment in Nipype), the spm.spatial.preproc.channel.write parameter (SPM's Save Bias Corrected parameter) takes [Save Bias Field = 0 or 1, Save Bias Corrected = 0 or 1]. In nypipe the initialisation of the outputs bias_field_images and bias_corrected_images are done with the inverse order. 
* This commit fix this inconsistency.

FIX: Order of SPM.NewSegment channel_info boolean tuple is (Field, Corrected)

---

nipype/utils/profiler.py

FIX: Set ResourceMonitor.fname to an absolute path

---

nipype/interfaces/base/__init__.py
nipype/interfaces/base/core.py
nipype/interfaces/base/support.py
nipype/interfaces/base/tests/test_core.py
nipype/scripts/utils.py
nipype/utils/nipype_cmd.py

This is the first on a series of PRs to clean up Nipype interfaces.
EDIT: also removed ``load_template`` from ``nipype.interfaces.base.support`` because it was deprecated since 1.0.0 and scheduled for removal in 1.1.0

[MAINT] Offload interfaces with help formatting

---

nipype/algorithms/confounds.py

Following discussion in poldracklab/fmriprep#1433, having CompCor interfaces gracefully handle failure states by returning NaN arrays of the appropriate size is preferable to crashing the pipeline.
This PR adds a `failure_mode` input to the interface, which defaults to `'error'` and maintains the current behavior. If `failure_mode == 'nan'`, then exceptions are not raised, and columns of NaNs are returned.
* Add `failure_mode` input to CompCor interfaces
* If `failure_mode == 'nan'`, return columns of NaNs instead of raising exceptions

ENH: Add NaN failure mode to CompCor interfaces

---

doc/about.rst
nipype/algorithms/confounds.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/dipy/preprocess.py
nipype/interfaces/dipy/simulate.py
nipype/interfaces/nipy/preprocess.py
nipype/interfaces/petpvc.py
nipype/workflows/dmri/fsl/artifacts.py

The DOI Foundation [started recommending a new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). While their URL change may be a bit ironic, it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old `dx` subdomain is being redirected, there is no urgency here.
- updates all static DOI links

DOC: Hyperlink DOIs to preferred resolver

---

nipype/algorithms/confounds.py

The default `lapack_driver` uses divide and conquer SVD (`gesdd`), which occasionally will cause `LinAlgError` even if the data are completely fine. Switching `lapack_driver` to `gesvd` when it fails can solve this issue.
Fixes # .

ENH/FIX: Resolve LinAlgError during SVD

---

nipype/info.py
nipype/interfaces/base/specs.py
nipype/interfaces/base/support.py
nipype/interfaces/tests/test_io.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_utils.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/tools.py
nipype/sphinxext/plot_workflow.py
nipype/utils/filemanip.py
nipype/utils/profiler.py
nipype/utils/tests/test_functions.py

In merging `master` into `dev/2.0`, I saw a Python >= 3.2 check, indicating a less-than-thorough purge of all obsolete version checks. Here I grepped for `sys.version` and removed any checks that no longer apply for Python < 3.5. (I think < 3.4.1 is the actual highest check, so we're not in the range of distinguishing 3.5 and 3.6.)
The main thing to-do is to change `to_str()` to `str()` everywhere, and remove that function fully, but I want to get tests running to make sure I'm not breaking anything.

RF: Drop various remaining compatibilities for Python < 3.5

---

nipype/info.py

not really sure why this didn't give me troubles before but it does now:
```shell
reproin@59965c6fd52f:/$ /usr/bin/heudiconv
File "/usr/bin/heudiconv", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
@_call_aside
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
return cls._build_from_requirements(__requires__)
File …
```

RF: Move pytest and pytest-xdist from general requirement into tests_required

---

nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/tests/test_auto_LaplacianThickness.py

That interface had a chance to work only when no any optional options specified since cmdline specs.
I also stripped  opt_ prefix from tollerance since they are all optional.
Some related discussions/changes on ANTs:
- https://github.com/ANTsX/ANTs/issues/688
- https://github.com/ANTsX/ANTs/pull/690

BF: ANTS LaplacianThickness cmdline opts fixed up

---

nipype/algorithms/modelgen.py
nipype/algorithms/tests/test_auto_SpecifyModel.py
nipype/algorithms/tests/test_auto_SpecifySPMModel.py
nipype/algorithms/tests/test_auto_SpecifySparseModel.py

SpecifyModel now supports BIDS event files as inputs.

ENH: Support for BIDS event files

---

.zenodo.json
nipype/interfaces/fsl/__init__.py
nipype/interfaces/fsl/epi.py

This PR adds an interface to `eddy_quad`, one of two tools in the EDDY QC framework.
See the [EDDY QC documentation](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddyqc/UsersGuide) for further details. Thanks to @akeshavan for help with my first nipype PR.
- Add `EddyQuadInputSpec` class
- Add `EddyQuadOutputSpec` class
- Add `EddyQuad` class with doctest

ENH: Add FSL `eddy_quad` interface

---

docker/generate_dockerfiles.sh

Apparently we're now hitting the #2855 issue via conda in the Docker images. See https://github.com/nipy/nipype/pull/2737#issuecomment-456548325.
Installs numpy!=1.16.0 via conda.

MNT: Install numpy!=1.16.0 from conda in Docker

---

doc/index.rst
doc/links_names.txt
nipype/interfaces/dipy/base.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/registration.py
nipype/interfaces/dipy/tests/test_base.py
nipype/interfaces/dipy/tracks.py

Hi Nipype Devs,
The main goal of this PR is to show how to convert a DIPY command line (named workflow) to a Nipype interface. This is a follow up from our discussion with @satra, @arokem, @Garyfallidis and me. 
This PR adds : 
- DKI diffusion Model
- CSA diffusion Model
- MAPMRI diffusion Model
- DTI Model
- Streamline Registration
- Reslicing
- Recobundles
- LabelsBundles
- Deterministic tracking
TODO:
--------

[ENH] Add interfaces wrapping DIPY worflows

---

nipype/interfaces/camino/convert.py

Camino procstreamlines can be used without -outputroot to filter streamlines. The function  _list_outputs insits on a definition of outputroot_files in contrast to _run_interface.

FIX: Ensure outputs can be listed in camino.ProcStreamlines by defining instance variable 

---

nipype/interfaces/ants/registration.py

DOC: Fix typos in ANTs Registration input documentation

---

nipype/pipeline/engine/tests/test_utils.py

[DOC] Replace initialism typo in comment with intended phrase

---

nipype/algorithms/modelgen.py

bids_gen_info uses functions from the csv and math modules but those are not imported.

FIX: Import math and csv modules for bids_gen_info

---

nipype/algorithms/confounds.py

Just was for some reason looking at that code and spotted wasted cycles

ENH: Threshold stddev once only in TSNR

---

nipype/interfaces/spm/model.py

One common thing in SPM is to change the default masking threshold in the `stats.fmri_spec` part. It is set to 0.8 which is quite high if you are interested in midbrain regions, OFC etc that have lower signal. At the moment I don't see how to set this default and a correct way seemed to be to add `flags` option, similar to the one implemented in the `EstimateModel` function. I tried it out on my local version and it does work correctly, it adds a correct line to the .m file created by Nipype for this job. and resulting images correspondingly change.
If some additional files with documentation should be changed, do let me know.
Re Run `make check-before-commit` before submitting the PR. Where can I find info about libraries that I need to install to run this? If I run it on basic Ubuntu OS …

ENH: Add flags dictionary input to spm.Level1Design

---

nipype/interfaces/afni/utils.py

Fixes #2874. its a follow up from #2886 where PR was accidentally closed.
Made a change to the inputs of `MaskTool` class in AFNI interface. Used `InputMultiObject` as suggested, tested it out and now it works fine with multiple input images as well as far as I can tell.

ENH: Allow afni.MaskTool to take multiple input files

---

nipype/algorithms/tests/test_CompCor.py
nipype/interfaces/dipy/tracks.py
nipype/testing/__init__.py
nipype/testing/decorators.py

Fixes #2890.
- Reduce deprecation complaints:
- import of `numpy` decorators
- `pytest.raises()` deprecated keyword (drop custom message)
- fix `dipy` import error for latest release (`0.16`) nipy/dipy#1794

MAINT: avoid deprecation warnings

---

nipype/interfaces/fsl/preprocess.py

Issue regarding the fix: https://github.com/nipy/nipype/issues/2899
* When warped_file or log_file input is set, will append the new name to the current working directory.

[FIX] Update FNIRT outputs for warped_file log_file to include cwd

---

nipype/interfaces/image.py
nipype/interfaces/tests/test_image.py

FIX: Import nibabel reorientation bug fix

---

.zenodo.json
nipype/interfaces/dipy/base.py
nipype/interfaces/dipy/preprocess.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/registration.py
nipype/interfaces/dipy/stats.py
nipype/interfaces/dipy/tests/test_base.py
nipype/interfaces/dipy/tracks.py

This PR is a follow up of #2830. It permits to add automatically all DIPY workflows following your DIPY version.  This should fix [this comment](https://github.com/nipy/nipype/pull/2830#issuecomment-456883290) from @arokem and @chrisfilo.
Originally, the goal was to fix [this issue](https://github.com/nipy/dipy/issues/1794) but thanks to @mgxd who already did it!
I tag @Garyfallidis and @satra just to keep them updated.

[ENH] Add all DIPY workflows dynamically  

---

nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/utils.py

AlignEpiAnatPy can take an AFNI file or a NIFTI file as input. If it's an AFNI file, it correctly removes the part after the +. However, a NIFTI file does not need to have a + in the filename, so the part `''.join(anat_prefix.split('+')[:-1])` returns `""`. This fix only removes the AFNI suffix if the filename contains a +.
Do not split + if it's not in the filename.
- [x ] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

FIX: parsing of filename in AlignEpiAnatPy when filename does not have +

---

nipype/pipeline/engine/nodes.py

For reasons yet to be identified, some fMRIPrep (e.g. poldracklab/fmriprep#1266) runs failed with:
```
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 528, in _get_inputs
output_value = results.outputs.trait_get()[output_name]
AttributeError: 'NoneType' object has no attribute 'trait_get'
During handling of the above exception, another exception occurred:
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
result['result'] = node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 410, in run
cached, updated = self.is_cached()
File …
```

ENH: More verbose description when a faulty results file is loaded

---

nipype/pipeline/engine/nodes.py
nipype/utils/filemanip.py

This PR downgrades the situation to a debug trace. The rationale is that going through crash reports of fMRIPrep is really hard because this error shows up in a large portion of them.
This error (trying to remove the unfinished hashfile after some run time error has occurred) is likely to happen when two twin nipype workflows are competing in the same filesystem. Downgrading this to a debug trace will help split errors derived from race conditions and other errors.

ENH: Do not override caught exceptions with FileNotFoundError from unfinished hashfile

---

nipype/interfaces/mrtrix3/preprocess.py
nipype/interfaces/mrtrix3/tests/test_auto_ResponseSD.py

For further information and why it can be left unset see http://community.mrtrix.org/t/lmax-for-dwi2response-and-dwi2fod/1099/4
cc / @oesteban
Fixes # .

FIX: Allow ``max_sh``not to be set (auto mode)

---

nipype/interfaces/camino/dti.py

Fix command line generated to run probability tracking on bedpostx output with Camino
- [x ] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

FIX: Set input model to bedpostx for camino.TrackBedpostxProba

---

nipype/algorithms/tests/test_auto_ACompCor.py
nipype/algorithms/tests/test_auto_TCompCor.py
nipype/interfaces/fsl/epi.py
nipype/interfaces/fsl/tests/test_auto_EddyQuad.py
nipype/interfaces/spm/tests/test_auto_Level1Design.py

[FIX] Remove '=' signs from EddyQuad argument specifications

---

docker/generate_dockerfiles.sh

Bumps neurodocker to 0.5.0 and sets the workdir to `~neuro` so that conda can throw temporary `.cph_tmp*` directories into the CWD with impunity.
https://github.com/conda/conda-package-handling/pull/34

FIX: Docker build

---

nipype/info.py
nipype/interfaces/base/__init__.py
nipype/interfaces/base/core.py
nipype/interfaces/base/specs.py
nipype/interfaces/base/support.py
nipype/interfaces/base/tests/test_specs.py
nipype/interfaces/base/traits_extension.py
nipype/interfaces/io.py
nipype/interfaces/spm/base.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py
requirements.txt

ENH: Modify ``Directory`` and ``File`` traits to get along with pathlib

---

docker/generate_dockerfiles.sh

Testing whether the latest Neurodocker handles the nipype use case again.
Following https://github.com/kaczmarj/neurodocker/pull/287.

MAINT: Bump neurodocker version

---

nipype/interfaces/base/core.py
nipype/interfaces/base/tests/test_core.py

Just a rewrite for improved readability.

MAINT: Refactor ``aggregate_outputs`` for readability

---

nipype/interfaces/mrtrix3/base.py
nipype/interfaces/mrtrix3/preprocess.py
nipype/interfaces/mrtrix3/tests/test_auto_DWIBiasCorrect.py
nipype/interfaces/mrtrix3/tests/test_auto_DWIDenoise.py
nipype/interfaces/mrtrix3/tests/test_auto_MRDeGibbs.py

Fixes #2975  .
- DWIDenoise
- use `name_template` to auto-generate noise file
- remove `_list_outputs()` method
- MRDeGibbs
- remove `use_default=True` so that values can be changed
- DWIBiasCorrect
- recycle `grad_file` and `grad_fsl` from `MRTrix3Base` spec and add xor since arguments are mutually exclusive
- remove `min_version=5.0.10` since the Mrtrix3 version is being checked, not FSL
- remove `_list_outputs()` method

FIX: Improve output handling in DWIDenoise and DWIBiasCorrect

---

nipype/info.py
requirements.txt

We are starting to see failed jobs in Travis.
Fixes # .

FIX: Python 3.4 is not compatible with the recent release of lxml-4.4.0

---

nipype/algorithms/misc.py
nipype/interfaces/afni/model.py
nipype/interfaces/afni/preprocess.py
nipype/interfaces/afni/utils.py
nipype/interfaces/base/__init__.py
nipype/interfaces/base/specs.py
nipype/interfaces/base/tests/test_traits_extension.py
nipype/interfaces/base/traits_extension.py
nipype/interfaces/dipy/base.py
nipype/interfaces/dipy/tests/test_base.py
nipype/interfaces/freesurfer/model.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/registration.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/fsl/fix.py
nipype/interfaces/fsl/model.py
nipype/interfaces/minc/minc.py
nipype/interfaces/niftyfit/asl.py
nipype/interfaces/niftyfit/dwi.py
nipype/interfaces/niftyfit/qt1.py
nipype/interfaces/nipy/model.py
nipype/interfaces/spm/base.py
nipype/interfaces/utility/base.py
nipype/interfaces/utility/tests/test_wrappers.py
nipype/pipeline/engine/tests/test_base.py

Two new methods ``resolve_path_traits`` and ``rebase_path_traits`` are being included.
They take trait instances from a spec (selected via ``spec.trait('traitname')``), the value and a base path. Returns the modified value (if necessary).
These two functions will be useful to progress towards #2944.

ENH: Add resolve/rebase ``BasePath`` traits methods & tests

---

nipype/pipeline/engine/tests/test_join.py

TST: Parametrize JoinNode expansion tests over config ``needed_outputs``

---

nipype/interfaces/base/specs.py
nipype/pipeline/engine/utils.py

It seems that #2944 has uncovered a rats-nest hidden in the engine. In
resolving that issue, I found out that a great deal of boilerplate was
set in place when loading/saving results to deal with
``OutputMulti{Object,Path}`` traits. The reason being that these traits
flatten single-element-list values.
This PR fixes the pickling behavior of traited specs containing these
types of traits.
Additionally, this PR also avoids the ``modify_paths`` function that was
causing problems originally in #2944. Therefore, this PR effectively
make results files static, meaning: caching if the ``base_dir`` of the
workflow is changed will not work anymore.
I plan to re-insert this feature (results file mobility) with #2971.
This PR is just to split that one in more digestible bits.
All the boilerplate …

FIX: Correctly pickle ``OuputMulti{Object,Path}`` traits

---

nipype/interfaces/base/traits_extension.py

Rewritten the validation of filename extensions, as it was incorrectly
interpreting the extension.
Fixes #2984.

FIX: Incorrect extension identified when checking ``File`` traits

---

nipype/caching/tests/test_memory.py
nipype/interfaces/base/traits_extension.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_base.py
nipype/pipeline/engine/tests/test_nodes.py
nipype/pipeline/engine/tests/test_utils.py
nipype/pipeline/engine/utils.py

Based on functionalities added in #2970.
Searches for paths in outputs of the result object to resolve/rebase them when loading/saving the pickle.
Includes a minor variation of the test @effigies proposed.
Fixes #2944 .
#2944 and posterior efforts to address it uncovered a couple of problems we may want to address some time (from https://github.com/nipy/nipype/pull/2970#issuecomment-516979640):
1. Whether we want to simplify/refactor the implementation of `hash_files` (https://github.com/nipy/nipype/pull/2970#issuecomment-515538213): this PR is a drop-in replacement of traits that should allow #2971 to remain strictly scoped into reading/writing of results files (i.e., no need to rework `hash_files`).
2. Whether we want to implement the config `use_relative_paths`, which I think fully …

FIX: Resolving/rebasing paths from/to results files

---

nipype/interfaces/mrtrix3/reconst.py
nipype/interfaces/mrtrix3/tests/test_auto_EstimateFOD.py

Change max_sh in EstimateFOD to InputMultiObject, so that one can pass a list of lmax values when using a multishell model; followed format of lmax variable from ResponseSD.
Fixes # .
* Import InputMultiObject from ..base
* Change format of EstimateFOD to InputMultiObject so one can input a list of lmax values

[ENH] Update mrtrix reconst.py EstimateFOD max_sh to be able to accept list

---

.circleci/config.yml
nipype/info.py
setup.py

Should probably have done this during the release.

MAINT: Add ``python_requires`` to package metadata

---

nipype/interfaces/petpvc.py
nipype/interfaces/tests/test_auto_PETPVC.py

Fixes incorrect stopping criterion flag in the nipype wrapper for PETPVC.

FIX: Specify correct stop criterion flag in PETPVC

---

.zenodo.json
nipype/interfaces/fsl/tests/test_auto_ImageStats.py
nipype/interfaces/fsl/utils.py

Allows fslstats calls with the -K option
- add an input to ImageStats corresponding to the `-K` option to fslstats

ENH: Add index_mask_file input to ImageStats

---

nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/tests/test_auto_N4BiasFieldCorrection.py

ENH: Add ``--rescale-intensities`` and name_source to N4BiasFieldCorrection

---

nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/tests/test_auto_N4BiasFieldCorrection.py

ENH: Additional arguments to ANTs N4BiasFieldCorrection

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

This flag is no longer need, so this PR removes it to simplify the code.
Fixes #3018

Remove versioning from loadpkl

---

nipype/utils/filemanip.py

Ref.: https://github.com/nipy/nipype/issues/3014#issuecomment-528408995

FIX: Ensure ``loadpkl`` returns a not None value

---

.zenodo.json
doc/changelog/1.X.X-changelog

Prep for 1.2.2 release, targeting Saturday, September 7.
Please add any issues you want to see included in the following release to the [upcoming 1.2.3 milestone](https://github.com/nipy/nipype/milestone/35) targetting September 23.
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Victor Férat (@vferat)

REL: 1.2.2 (revised)

---

nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Minimize the access to the ``result`` property when writing
pre/post-execution reports.
This modification should particularly preempt https://github.com/nipy/nipype/issues/3009#issuecomment-529799338

ENH: Avoid loading result from file when writing reports

---

nipype/pipeline/engine/nodes.py

Generating the hashvalue when outputs are not ready at cache check stage
when the node's directory does not exist (or no results file is in
there) leads to #3014.
This PR preempts those problems by delaying the hashval calculation.
Fixes # .

ENH: Lightweight node cache checking

---

nipype/interfaces/afni/preprocess.py

Replaces #2921 from @gpiantoni (apologies for the force push).

FIX: Qwarp in AFNI can have NIFTI and NIFTI_GZ as extensions

---

nipype/interfaces/fsl/preprocess.py

Fixes #2925 .
* Fixes MCFLIRT output checks for FSL 6, which now uses more sensible extensions for intermediate output file names.

ENH: Update MCFLIRT outputs for FSL 6+

---

nipype/__init__.py
nipype/info.py
nipype/utils/config.py
requirements.txt

Adds the ability to check for the most recent released version.
- add etelemetry as a dependency

enh: add telemetry to nipype

---

nipype/algorithms/modelgen.py
nipype/algorithms/tests/test_auto_SpecifyModel.py
nipype/algorithms/tests/test_auto_SpecifySPMModel.py
nipype/algorithms/tests/test_auto_SpecifySparseModel.py
nipype/info.py
tools/checkspecs.py

`make specs` currently flails a bit from user to user, apparently because `yapf` has changed its formatting rules.
Additionally, we've been ignoring errors reported by `make specs`, probably because they weren't really clearly errors.
* Set a new minimum version of `yapf >=0.27`. I've verified that 0.27 and 0.28 both give the same result, while 0.26 gives the old result.
* Add `extensions` metadata to list of accepted metadata to reduce noise
* Remove `exists` metadata from non-file traits as well as `mandatory=False` metadata

MAINT: Set minimum yapf for `checkspecs` to 0.27

---

nipype/interfaces/base/core.py
nipype/utils/filemanip.py

Exceptions do not take a `message` argument. This restores the `FileNotFoundError` to Python 3 compatibility.
Fixes issue introduced in #2969.

FIX: Drop deprecated message argument to FileNotFoundError

---

nipype/utils/filemanip.py

This should be a blessedly short-lived hack, but it is needed to resolve nipy/heudiconv#374.
* `Path.mkdir()` was failing for Python 2, due to a PY3 guard
* Had to import `TemporaryDirectory` from `nipype.utils.tmpdirs` instead of `tempfile`
* Updated our existing `makedirs` hack to include `mode`, for full replacement of `os.makedirs`

FIX: Patch Path.mkdir for Python 2

---

docker/generate_dockerfiles.sh
nipype/info.py
nipype/interfaces/dcm2nii.py
nipype/interfaces/tests/test_auto_Dcm2niix.py
nipype/interfaces/tests/test_extra_dcm2nii.py

This PR fixes the convoluted approach used for gathering `dcm2niix` outputs.
- Checks the output prefix for possible suffixes, instead of assuming outputs based off stdout switches.

RF: dcm2niix interface

---

nipype/interfaces/base/traits_extension.py
nipype/pipeline/engine/utils.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

In #3046, we see that pytest using our monkey-patched `Path` objects. This seems generally unsafe, and evidently possible for us to screw up, so I've switched to functions that try to use the original methods, with fallback implementations when they fail. These are marked with `#PY*` tags so we can drop them when we drop support for those versions.
I've left the `Path.write_text` method for now, just because the logic there is simpler and we'll be dropping Python 3.4 very soon.
Alternative to #3048.
* Replace `Path.mkdir` monkeypatch with `nipype.utils.filemanip.path_mkdir`
* Replace `Path.resolve` monkeypatch with `nipype.utils.filemanip.path_resolve`

RF: Provide functions to augment old Path.mkdir, Path.resolve methods

---

nipype/interfaces/tests/test_extra_dcm2nii.py

Trying again after #3058 - otherwise we should xfail it for the time being.

tst: use pytest fixture

---

.travis.yml
nipype/info.py

This PR does not attempt to hunt down Python 3.4-isms and purge them. Just removes the test battery and updates the package metadata.

MNT: Drop Python 3.4 support

---

nipype/pipeline/plugins/multiproc.py

Remove the asynchronous chdir callback in the multiproc plugin

FIX: Remove asynchronous chdir callback

---

.pre-commit-config.yaml
CONTRIBUTING.md

Add pre-commit config and developer information

enh: add precommit information for contributors and pre-commit style

---

.travis.yml
nipype/interfaces/afni/tests/test_auto_Remlfit.py
nipype/interfaces/afni/utils.py
nipype/interfaces/diffusion_toolkit/dti.py
nipype/interfaces/dipy/tracks.py
nipype/interfaces/fsl/utils.py
nipype/interfaces/image.py
nipype/interfaces/io.py
nipype/interfaces/tests/test_io.py
nipype/interfaces/utility/base.py
nipype/pipeline/engine/utils.py

Adds a `make check-before-commit` test to Travis, to verify that no changes are made to the working directory. This will help catch situations where people fail to run `make specs`, but it doesn't cause an error (e.g., adding an input) and when a test pollutes the repository with what should be temporary files.
Closes #2967.
* New Travis test
* Some cleanups from running locally, including a bunch of warnings about regexes

CI: make check-before-commit on Travis

---

nipype/interfaces/afni/base.py
nipype/interfaces/afni/model.py

In #2964 I broke some interfaces (@tsalo identified `Allineate` as one
of those) by removing the ``_get_fname`` function from the base
``AFNICommand``.
The intent was to migrate to a ``name_source``-based management of
automatically generated names, but in the case of ``Allineate``, the use
of `_get_fname` was a bit different (modifying the user-provide input
value under certain conditions to follow ANFI's ``3dAllineate``
behavior).
This PR restores the missing function. Closes #3070.
Fixes # .

FIX: Restore ``AFNICommand._get_fname``, required by some interfaces

---

nipype/interfaces/afni/preprocess.py

Fixed a typo in QwarpInputSpecs trait description for 'noXdis', 'noYdis', and 'noZdis'.

[FIX] Fixed typo in QwarpInputSpec Trait description

---

nipype/pipeline/engine/nodes.py

This PR attempts to alleviate #3014 by opening the result file of a source node only once when that node feeds into several inputs of the node collecting inputs. Before these changes, a call to ``_load_results`` was issued for every input field that needed to collect its inputs from a past node. Now, all the inputs coming from the same node are put together and the ``_load_results`` function is called just once. 
The PR also modifies the manner the ``AttributeError``s (#3014) were handled to make it easier to spot whether an error occurred while loading results araises when gathering the inputs of a node-to-be-run or elsewhere.

ENH: Minimize the number of calls to ``_load_results`` when populating inputs

---

.zenodo.json
doc/changelog/1.X.X-changelog
nipype/info.py

Prep for 1.3.0, for immediate release.
This is delayed from the originally planned release on Monday, October 28 for the sake of testing.
Emergency fixes only to be accepted between now and release.
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Victor Férat (@vferat)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Niklas …

REL: 1.3.0

---

nipype/interfaces/diffusion_toolkit/odf.py
nipype/interfaces/dipy/base.py
nipype/interfaces/elastix/utils.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/spm/model.py
nipype/pipeline/plugins/tests/test_tools.py
nipype/sphinxext/plot_workflow.py

Ran into some deprecation errors working on #3099. The escape characters were easy to handle.

FIX: Mark strings containing regex escapes as raw

---

nipype/pytest.ini

Current [tests](https://circleci.com/gh/nipy/nipype/10565) emit this warning from pytest:
```
/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/_pytest/junitxml.py:436
/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/_pytest/junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
Add 'junit_family=legacy' to your pytest.ini file to silence this warning and make your suite compatible.
_issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
```
In niworkflows, we were able to suppress it by making the included change. Selected the planned default value to embrace the future. If it fails, we can cling to the past.

MNT: Set junit_family to suppress pytest warning

---

nipype/algorithms/confounds.py
nipype/algorithms/icc.py
nipype/algorithms/mesh.py
nipype/algorithms/metrics.py
nipype/algorithms/misc.py
nipype/algorithms/rapidart.py
nipype/algorithms/stats.py
nipype/algorithms/tests/test_CompCor.py
nipype/algorithms/tests/test_normalize_tpms.py
nipype/algorithms/tests/test_splitmerge.py
nipype/algorithms/tests/test_stats.py
nipype/interfaces/cmtk/cmtk.py
nipype/interfaces/cmtk/parcellation.py
nipype/interfaces/dipy/anisotropic_power.py
nipype/interfaces/dipy/preprocess.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/simulate.py
nipype/interfaces/dipy/tensors.py
nipype/interfaces/dipy/tracks.py
nipype/interfaces/freesurfer/tests/test_model.py
nipype/interfaces/image.py
nipype/interfaces/nilearn.py
nipype/interfaces/nipy/model.py
nipype/interfaces/nipy/preprocess.py
nipype/interfaces/nipy/utils.py
nipype/interfaces/tests/test_image.py
nipype/interfaces/utility/base.py
nipype/utils/config.py

Updated Travis on master to actually install pre-release dependencies. Starting on deprecation warnings.
I would appreciate a careful review. In general, `np.[as[any]]array(niimg.dataobj)` is the more conservative change, keeping `get_data()` functionality, except for caching. When floats obviously make more sense, I'm switching to `get_fdata()`. We may want to specify `dtype=np.float32` in these cases.
I'm also in passing removing unnecessary loading of data blocks, such as `get_data().shape` or `get_data().ndim`.
* Purge `get_data()`
* ...?

ENH: Pacify DeprecationWarnings caused by nibabel 3 pre-release

---

CONTRIBUTING.md
README.rst

Ref #3113. 
* Add a Python 2 statement to README
* Mention maintenance branch in CONTRIBUTING

DOC: Add Python 2 statement to README, reference maintenance branch in CONTRIBUTING

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog
nipype/info.py
setup.py

Prep for 1.4.0, for immediate release, pending completion.
Open question: Should we move from `git-line-summary` to `git shortlog` for determining .zenodo ordering? With #3096, the line summary became:
```
$ head -n 13 line-contributors.txt
project  : nipype
lines    :   298318
authors  :
109691 Oscar Esteban                       36.8%
67391 Christopher J. Markiewicz            22.6%
53863 Satrajit Ghosh                       18.1%
10441 Krzysztof J. Gorgolewski             3.5%
3841 Christopher Burns                     1.3%
3836 Hans Johnson                          1.3%
3828 Erik Ziegler                          1.3%
3650 Alexandre M. Savio                    1.2%
3458 Dorota Jarecka                        1.2%
```
Shortlog:
```
$ git shortlog -ns | head   
3308	Satrajit Ghosh
1968 …
```

REL: 1.4.0

---

nipype/interfaces/ants/registration.py

Fixes #3117  .
- Change the trait type for ANTS number_of_time_steps from traits.Float to traits.Int

[FIX] change ANTS number_of_time_steps from Float to Int

---

examples/dmri_camino_dti.py
examples/dmri_connectivity.py
examples/fmri_ants_openfmri.py
examples/fmri_fsl.py
examples/fmri_spm_auditory.py
examples/fmri_spm_face.py
examples/rsfmri_vol_surface_preprocessing.py
examples/rsfmri_vol_surface_preprocessing_nipy.py
nipype/algorithms/confounds.py
nipype/algorithms/icc.py
nipype/algorithms/misc.py
nipype/algorithms/modelgen.py
nipype/algorithms/rapidart.py
nipype/algorithms/tests/test_misc.py
nipype/algorithms/tests/test_normalize_tpms.py
nipype/algorithms/tests/test_splitmerge.py
nipype/interfaces/dcmstack.py
nipype/interfaces/dipy/preprocess.py
nipype/interfaces/freesurfer/tests/test_model.py
nipype/interfaces/fsl/epi.py
nipype/interfaces/mrtrix/convert.py
nipype/interfaces/spm/base.py
nipype/utils/__init__.py
nipype/utils/config.py

Removed all use cases of numpy_mmap as it will always be true.
I acknowledge that this contribution will be available under the Apache 2 license.

[REF] removed all uses of numpy_mmap

---

docker/generate_dockerfiles.sh
examples/dmri_connectivity_advanced.py
examples/dmri_dtk_dti.py
examples/dmri_dtk_odf.py
examples/dmri_fsl_dti.py
examples/dmri_group_connectivity_camino.py
examples/dmri_group_connectivity_mrtrix.py
examples/dmri_preprocessing.py
examples/dmri_tbss_nki.py
examples/fmri_ants_openfmri.py
examples/fmri_fsl_feeds.py
examples/fmri_fsl_reuse.py
examples/fmri_spm_dartel.py
examples/frontiers_paper/smoothing_comparison.py
examples/nipype_tutorial.ipynb
examples/smri_ants_build_template.py
examples/smri_antsregistration_build_template.py
examples/smri_fsreconall.py
examples/tessellation_tutorial.py
nipype/interfaces/fsl/epi.py
nipype/sphinxext/plot_workflow.py

Master is broken -- this PR relocates the pip install of
``niflow-nipype1-workflows`` so that it happens AFTER nipype
was installed.
Fixes # .

FIX: Can't seem to import workflows from niflows in CircleCI

---

nipype/info.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_nodes.py

Fixes #3088  
Allows MapNodes that have one subnode to generate a results file before erroring out

fix: mapnode to generate result file when crashes in single node mode

---

nipype/info.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_nodes.py

Backports #3143 to 1.3.x.
* fix: mapnode to generate result file when crashes in single node mode
* enh: simplify test further

Backport: gh-3143 to 1.3.x branch

---

nipype/__init__.py
nipype/interfaces/base/core.py
nipype/pipeline/plugins/legacymultiproc.py
nipype/pipeline/plugins/multiproc.py
nipype/pipeline/plugins/tools.py
nipype/tests/test_nipype.py

Reduce number of version checks for nodes of workflows run through multiprocessing .
This is a rather drastic step, and we should think through how to handle this in general. this will prevent this for other libraries which are used as well.

fix: improve version checking for nodes of workflows

---

nipype/interfaces/io.py

Due to how `pathlib.Path` handles path strings, S3 bucket paths are missing a `/`.
Fixes #3105.
* Changes DataSink input specs for output paths to be `Str` rather than `Directory`.

FIX: DataSink to S3 buckets

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
doc/interfaces.rst
nipype/info.py

Prep for bug-fix release 1.4.1, targeting Monday, January 27.
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Niklas Förster (@niklasfoe)
No entry to sort: Kirstie Whitaker (@KirstieJane)
No entry to sort: Jonathan R. Williford (@williford)
~~No entry to sort: Abel González (@abelalez)~~
No entry …

REL: 1.4.1

---

nipype/interfaces/base/traits_extension.py

Addresses #3157 in `maint/1.4.x`.
After merging, `maint/1.4.x` should be merged into `master`.

FIX: Move TraitType import, handle API change for NoDefaultSpecified

---

nipype/pipeline/plugins/sgegraph.py

Fixes #3164
* added regex to awk command extracting job_ids for sge jobs

FIX: Reliably parse SGE job IDs in the presence of warnings

---

CONTRIBUTING.md

DOC: Update links, typos in contributing guide

---

nipype/interfaces/io.py

Fixes #2712 through clarification.
* Clarifies that SelectFiles does not support lists as inputs.

[DOC] Update SelectFiles docstring to match actual behavior

---

nipype/algorithms/modelgen.py

RF: Prefer math.gcd to hand-rolled Euclid's algorithm

---

nipype/pipeline/engine/utils.py
nipype/pipeline/plugins/tests/test_sgelike.py

If a job crashes on computing nodes a result-file is written containing a dictionary (with traceback, etc). Then the 'controller' job reads the dictionary in order to produce the pickeled crash file. During reading of the results-file an exception arises in `load_resultfile` with `AttributeError: 'dict' object has no attribute 'outputs'`.
In #2985 `loadpkl` was replaced by `load_resultfile`. But `result_data` could be a dictionary as assumed in the following source snippet:
https://github.com/nipy/nipype/blob/b75a7cebc8dbefa796ed2504ca40197e65a9549e/nipype/pipeline/plugins/base.py#L531-L536
But `result_data` will never be a dictionary, because in `load_resultfile`  it has to have an attribute `outputs`:
https://github.com/nipy/nipype/blob/b75a7cebc8dbefa796ed2504ca40197e65a9549e/nipype/pip …

FIX: load_resultfile crashes if open resultsfile from crashed job

---

.zenodo.json
nipype/pipeline/engine/tests/test_workflows.py
nipype/pipeline/engine/workflows.py

Hi :-) I'm using nipype with fmriprep to process hundreds of subjects. When doing that, I noticed that creating the nipype workflows can be quite slow. This was mostly noticeable when there were nested workflows. To find out why, I ran a quick python cProfile.
It turns out that a prominent performance bottleneck is the `workflow.connect` function, or rather the `_has_attr` function that is called by it. This function checks if a nested workflow has a specific input or output. If the input/output is not found, an error message is printed. 
To check for inputs/outputs, `_has_attr` uses the workflow's `inputs` or `outputs` properties, which return a dictionary of the inputs/outputs of all nested nodes. `_has_attr` now checks whether the target input or output is listed in the dictionary and …

[ENH] Workflow connect performance

---

nipype/interfaces/ants/segmentation.py

In the last maintenance (#3180) of the interface, we eliminated an
important section of the ``_list_outputs``:
https://github.com/nipy/nipype/commit/6979cbdcb041cb12b064513a57ff74b000bacdad#diff-b6f33a19b0e06b91023416db5faf7323L544-L547
This PR addresses the problem:
```
Execution Outputs
-----------------
* bias_image : <undefined>
* output_image : /home/oesteban/tmp/fmriprep-ds005/fprep-work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/inu_n4_final/mapflow/_inu_n4_final0/sub-01_T1w_cor
rected.nii.gz
Runtime info
------------
* cmdline : N4BiasFieldCorrection --bspline-fitting [ 200 ] -d 3 --input-image /oak/stanford/groups/russpold/data/openfmri/ds000005/sub-01/anat/sub-01_T1w.nii.gz --convergence [ 50x
50x50x50x50, 1e-07 ] --output [ sub-01_T1w_corrected.nii.gz, …
```

FIX: Partial rollback of N4BiasFieldCorrection

---

nipype/interfaces/niftyreg/base.py

Fixes #2615.
- Use `PackageInfo` to get NiftyReg version as suggested in #2615.

FIX: Use PackageInfo to get NiftyReg version

---

nipype/interfaces/base/tests/test_core.py
nipype/interfaces/tests/test_extra_dcm2nii.py

Closes #3185.
Without pytest-xdist, this reliably fails:
```
pytest --pdb --doctest-modules nipype/interfaces/base/tests/test_core.py nipype/interfaces/freesurfer/tests/test_utils.py
```
I assume the intermittent CI failures are for when the two tests were run on the same worker.

TEST: Mock terminal output before testing changing default value

---

.travis.yml
nipype/__init__.py
nipype/algorithms/tests/test_TSNR.py
nipype/info.py
nipype/interfaces/fsl/tests/test_base.py
nipype/pipeline/plugins/tests/test_oar.py
nipype/pipeline/plugins/tests/test_pbs.py
nipype/pipeline/plugins/tests/test_tools.py
nipype/testing/tests/test_utils.py
nipype/tests/test_nipype.py
nipype/utils/tests/test_config.py
nipype/utils/tests/test_filemanip.py
nipype/utils/tests/test_provenance.py

Discovered while working through #3154.

TEST: Clean up tests

---

.travis.yml
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/__init__.py
nipype/algorithms/tests/test_TSNR.py
nipype/info.py
nipype/interfaces/ants/registration.py
nipype/interfaces/ants/tests/test_auto_Registration.py
nipype/interfaces/base/tests/test_core.py
nipype/interfaces/base/traits_extension.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/fsl/tests/test_base.py
nipype/interfaces/fsl/tests/test_model.py
nipype/interfaces/io.py
nipype/interfaces/niftyreg/base.py
nipype/interfaces/tests/test_auto_ExportFile.py
nipype/interfaces/tests/test_extra_dcm2nii.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/tests/test_oar.py
nipype/pipeline/plugins/tests/test_pbs.py
nipype/pipeline/plugins/tests/test_tools.py
nipype/testing/tests/test_utils.py
nipype/tests/test_nipype.py
nipype/utils/tests/test_config.py
nipype/utils/tests/test_filemanip.py
nipype/utils/tests/test_provenance.py
tools/checkspecs.py
tools/update_zenodo.py

Prep for new feature release 1.5.0, targeting release on Monday, February 24.
Given that we just released 1.4.2 about a week ago, I'm inclined to hold this one off for any feature PRs that would like to shoot for inclusion.
Require merge or postponement decision on all issues/PRs in https://github.com/nipy/nipype/milestone/38:
Will try review the open PRs and see if anything is close enough to push on, tomorrow.
The following authors have contributed, but not added themselves to the [`.zenodo.json`](https://github.com/nipy/nipype/blob/master/.zenodo.json) file. If you would like to be an author on Zenodo releases, please add yourself or comment with your preferred publication name, affiliation and [ORCID](https://orcid.org/). If you would like to stop being spammed whenever I'm the one …

REL: 1.5.0

---

Makefile
doc/conf.py
nipype/interfaces/freesurfer/preprocess.py
tools/toollib.py

It is largely based on patches which are now in debian packaging of nipype.  In an effort to upgrade debian distribution from python 2 to 3, there should be better control over which python is actually invoked by the processes. E.g. there could be `python` and `python3` executables, and nipype imported in `python3`.  Then all underlying calls should also use `python3` and not just plain `python`.  Also Makefile already had provision (`$(PYTHON)` variable) to define which python to use but it was not uniformly used.  This PR should address those. 
See individual commits for possibly more comments

REF: make invocations of python and pytest consistent with the one used/desired python

---

.travis.yml
nipype/info.py
nipype/pipeline/plugins/tests/test_legacymultiproc_nondaemon.py
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/pipeline/plugins/tests/test_oar.py
nipype/pipeline/plugins/tests/test_pbs.py
nipype/utils/tests/test_provenance.py
requirements.txt

CI: Test Python 3.8

---

nipype/interfaces/ants/utils.py

``"TruncateImageIntensity"`` is part of ``antsBrainExtraction.sh`` and therefore, having it supported by nipype is of great interest.
This PR addresses a problem @eilidhmacnicol just discovered. Having this merged will also allow us to call the upstreaming of ANTS interfaces from niworkflows done.
Fixes # .

ENH: Add ``"TruncateImageIntensity"`` operation to ``ants.utils.Image.Math``

---

nipype/info.py

MAINT: Permit recent nilearns

---

nipype/interfaces/freesurfer/base.py

fix: allow parsing freesurfer 7 version string

---

nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py

Closes #3103 
This should fix cases where terminal output (stdout / stderr) is given as a string, and each character is printed on a new line.

FIX: report.rst terminal output

---

.gitignore
nipype/interfaces/fsl/preprocess.py

Added `cwd` keyword argument to `_gen_fname()` calls so that the returned output will reference the correct paths. This fixes #2916.
- [V] I acknowledge that this contribution will be available under the Apache 2 license.

[FIX] BET incorrect output paths

---

nipype/interfaces/spm/model.py

For fMRI model specification, in SPM, matlabbatch{n}.spm.stats.fmri_spec.volt = 2 corresponds to 'Model Interactions' and matlabbatch{n}.spm.stats.fmri_spec.volt =1 corresponds to 'Do not model Interactions'.
Currently, for the corresponding process in nipype, the Level1Design, we see volterra_expansion_order = traits.Enum(1, 2, field="volt", desc=("Model interactions - yes:1, no:2")).
I guess the correct description should rather be volterra_expansion_order = traits.Enum(1, 2, field="volt", desc=("Model interactions - no:1, yes:2"))

volterra_expansion_order documentation error

---

nipype/conftest.py
nipype/interfaces/io.py

DOC: Skip BIDSDataGrabber doctest if pybids is missing

---

.travis.yml
nipype/tests/test_nipype.py

Travis is consistently hanging on Python 3.8, apparently at test_no_et. This adds verbosity, and splits up the test to hopefully make it easier to track down.
Cannot reproduce this locally by running the specific file, but there may be state changes in the test workers...

FIX: test_no_et hanging on Python 3.8

---

nipype/interfaces/ants/resampling.py

antsApplyTransforms currently permits `identity` or a chain of transformations, but it can be useful to insert an `identity` into a chain.
* Changes transforms from `Either(InputMultiObject(File), "identity")` to `InputMultiObject(Either(File, "identity"))`.
* Change `InputMultiPath` to `InputMultiObject` throughout the file, in passing.
* Simplifies the logic for constructing `--transform` arguments.

FIX: Permit identity transforms in list of transforms given to ants.ApplyTransforms

---

nipype/pipeline/engine/tests/test_utils.py
nipype/pipeline/engine/utils.py

@matteomancini Apologies for taking over your PR. I had some maintenance changes to make, and ended up making more significant changes than I felt comfortable force-pushing to your branch. Feel free to take these changes to your PR, if you have further changes you want to make. I would also appreciate your review.
Fixes #3230.
Closes #3231.
#3231 Ensured that values passed to nodes would be reproduced after being serialized. This PR:
1) Added a test to verify that the problem was demonstrated and the solution resolved it. (It did.)
2) Rebased against `maint/1.5.x` so that this can go in the next release.
3) Decided to use f-strings and the `repr` (`!r`) format to avoid branching, then saw opportunities to further refactor.

FIX: Serialize all interface arguments when exporting workflows

---

nipype/interfaces/base/core.py
nipype/interfaces/base/tests/test_core.py

@TheChymera Apologies for taking over #3234, but I would like to get a bug-fix release out quickly.

FIX: Warn for min/max_ver traits when tool version can't be parsed

---

.zenodo.json
doc/changelog/1.X.X-changelog.rst
doc/interfaces.rst
nipype/info.py
nipype/interfaces/ants/registration.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/ants/utils.py
nipype/interfaces/freesurfer/base.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/fsl/preprocess.py
nipype/interfaces/niftyreg/base.py
nipype/interfaces/spm/preprocess.py
nipype/pipeline/plugins/tests/test_legacymultiproc_nondaemon.py
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/utils/tests/test_filemanip.py

Release prep for 1.5.1. We're due a release, and there are a couple very small changes.
I would like to get in:
We could probably quickly finish up:
No entry to sort: cdla (@cdla)
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Victor Férat (@vferat)
No entry to sort: Niklas Förster (@niklasfoe)
No entry to sort: Kirstie Whitaker …

REL: 1.5.1

---

.travis.yml
nipype/algorithms/misc.py

Trying to figure out what's going on with #3261. Possibly xenial is being relegated to slow machines?
Also found a small bug while looking at the Travis outputs.

FIX: CI issues

---

nipype/pipeline/engine/workflows.py

A few months back, I submitted pull request #3184 to improve the performance of using `connect` when creating large workflows. Specifically, I had discovered that the use of the `inputs` or `outputs` properties of workflows can create a performance bottleneck if there are many child nodes or nested workflows. 
Recently, I noticed that the same bottleneck can cause a delay between calling `workflow.run()` and the start of the actual execution, meaning when nodes and interfaces start to run. 
Running cProfile suggests that the delay occurs in `_create_flat_graph`. Note that the profile does not include the full workflow execution, but was cancelled immediately when the first node started to run.
As far as I can tell, before execution starts, nested workflows are merged into one overall …

[ENH] Optimize workflow.run performance

---

.zenodo.json
nipype/interfaces/fsl/epi.py

Fixes #3264 
FSL's epi_reg script does not perform segmentation when a white matter segmented file is already provided. Hence, the interface should not check whether the 'seg' output exists in in case a 'wmseg' input is specified.
* added simple conditional to the _list_outputs() methods of the EpiReg interface such that the outputs 'seg', 'wmseg', and 'wmedge' are not listed when 'wmseg' is already specified as an input

[FIX] EpiReg changed to not list certain outputs when 'wmseg' input is specified

---

.zenodo.json

My [previous contribution](https://github.com/nipy/nipype/pull/2875) was very small. I don't need credit on every subsequent release, nor the ORICD spam :-)
Thanks, though!

DOC: Remove myself (@mr-c) from the zenodo metadata

---

nipype/interfaces/base/core.py
nipype/interfaces/base/tests/test_core.py
nipype/interfaces/tests/test_io.py

This turns all unavailable traits to undefined at runtime, and switches the order of checks. i'm not sure run is the best place for this yet.
Needs tests. @salma1601 and @effigies let's use this to see if we can address this. 
Fixes #3138 .
- Make unavailable traits undefined

handle unavailable traits due to version differences

---

nipype/interfaces/base/tests/test_specs.py
nipype/interfaces/io.py
nipype/utils/filemanip.py
nipype/utils/subprocess.py

Apparently this was deprecated in Python 2.6 and we missed it. `BaseException.__str__` is the generic way to access messages.
Fixes #3270.
* Remove uses of `BaseException.message; Update to `BaseException.__str__`
* Remove uses of `OSError.__getitem__`; Update to `OSError.errno`

FIX: Purge deprecated exception content accesses

---

nipype/interfaces/base/core.py
nipype/utils/filemanip.py

Reading through #2509 and CPython's [_winapi.c](https://github.com/python/cpython/blob/e087f7cd43dfa4223c55a8ecd71f4a7d685178e4/Modules/_winapi.c#L801-L805), it looks like we actually want to pass `dict`s of `str`, rather than `bytes`.
```C
if (! PyUnicode_Check(key) || ! PyUnicode_Check(value)) {
PyErr_SetString(PyExc_TypeError,
"environment can only contain strings");
goto error;
}
```
Fixes #2509.
* Fix canonicalize to str
* Pass canonicalized env to Popen in `version_from_command()`
This last is deprecated and shouldn't be getting called, but NiftyReg still uses it, so that's a separate task.

FIX: Canonicalize environment dicts to strings in Windows

---

.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Release prep for 1.6.0. No specific timeline.
Remaining issues/PRs:
Going to skip this. Many releases of no responses suggest I'm just spamming at this point. @satra has also suggested paring down the authors to more recently active contributors.

REL: 1.6.0

---

nipype/interfaces/fsl/model.py

As mentioned previously (https://github.com/poldracklab/ds003-post-fMRIPrep-analysis/issues/7), the `resels` output of FSL's smoothest refers to the size of a resel, not the *number of resels*. 
I propose to update the output spec to avoid misunderstandings.

FIX: Update SmoothEstimateOutputSpec resels description

---

nipype/interfaces/fsl/preprocess.py
nipype/interfaces/fsl/tests/test_preprocess.py

Trying to fix #3211.
@satra or @oesteban, I'll try a couple of things and see if it works, but I'm not confident if I completely understood:
> 2. make the output filename be local (no absolute path) for generation, but not for list_outputs.
If you could help clarify how exactly this would be best implemented, I would be happy to update the PR and hopefully resolve this issue.

FIX: BET raising "No image files match: ..." with very long file names

---

nipype/info.py

We forgot to drop support for numpy < 1.14 for the last minor release, but the next [NEP29+1y](https://github.com/nipy/nibabel/issues/803) milestone is Jan 7 2021, and I doubt we'll have a minor release before then. This drops support for <1.15.3, which means we can drop our split between 3.6 and 3.7+ dependencies.

MNT: Drop support for numpy < 1.15.3

---

.github/workflows/tests.yml
tools/ci/activate.sh
tools/ci/build_archive.sh
tools/ci/check.sh
tools/ci/create_venv.sh
tools/ci/env.sh
tools/ci/install.sh
tools/ci/install_deb_dependencies.sh
tools/ci/install_dependencies.sh

CI: Move from Travis to GitHub actions

---

nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/tests/test_auto_Randomise.py

Fixes #3322.
- corrects typo in fsl randomise interface for running only f-tests.
- [ x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

[FIX] change fsl interface randomise --f_only to --fonly for #3322

---

.zenodo.json
doc/users/install.rst

Changed the link for developer setup in install.rst to make it working. Previously showing Error 404.
Now the link is working and redirecting to appropriate page.

[DOC] Fixed Developer Setup Link in install.rst

---

nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py

I'm working with fMRIPrep and large data sets (via the ENIGMA consortium). In my testing, Nipype workflows with more than a few hundred thousand nodes can be prohibitively slow, so that it can take days before processing starts. This comes specifically from the function `_generate_flatgraph` and `generate_expanded_graph`. While my previous pull requests #3184 and #3260 fixed some bottlenecks, I recently had the time to do some more profiling and try to fix some more. 
I understand that Pydra is just around the corner, and that switching to it may solve my performance troubles then. However, the small changes outlined here can reduce the time before processing starts by approximately half (in my testing with a workflow of 75k nodes). 
I have tried to divide up the changes into independent …

[REF] Cache nodes in workflow to speed up construction, other optimizations

---

docker/generate_dockerfiles.sh

Circle tests are failing because h5py no longer builds wheels for Python 3.6, and our docker images are not equipped to build the wheels. Python 3.6 is on its way out, so upgrading to Python 3.8.
Or should I target 3.9?

CI: Build docker images with Python 3.8

---

nipype/info.py

CI is failing because dipy 1.4.1 is incompatible with our conversion script.
See https://github.com/dipy/dipy/issues/2402 for more details.
* Avoid installing dipy 1.4.1

MNT: Blacklist Dipy 1.4.1

---

nipype/interfaces/utility/base.py

Silence a deprecation warning in the tests. Making a separate PR in case tests fail and more inspection is needed.

FIX: Specify dtype object when making arrays from list that might contain lists

---

nipype/pipeline/plugins/base.py

In 39c4ee391baf9fb3bd3093a7b4b8db63ad26ac4e, we had
```Diff
def _generate_dependency_list(self, graph):
""" Generates a dependency list for a list of graphs.
"""
self.procs = graph.nodes()
-        self.depidx = nx.adj_matrix(graph).__array__()
-        self.refidx = deepcopy(self.depidx>0)
-        self.refidx.dtype = np.int8
+        self.depidx = ssp.lil_matrix(nx.adj_matrix(graph).__array__())
+        self.refidx = deepcopy(self.depidx)
+        self.refidx.astype = np.int
self.proc_done    = np.zeros(len(self.procs), dtype=bool)
self.proc_pending = np.zeros(len(self.procs), dtype=bool)
```
This looks like a typo, that should have been `self.refidx = deepcopy(self.depidx).astype(np.int)` or similar.
In this PR, I simply use `self.depidx.astype(int)`. …

FIX: Set DistributedPluginBase.refidx type correctly

---

nipype/algorithms/modelgen.py
nipype/algorithms/rapidart.py

Wanted to run this one by people rather than tucking into #3336.
Because `np.float` is just `__builtins__.float`, which is in turn promoted to `np.float64` when used as a dtype, this should have no effect. Just want to make sure that this is what's intended in these cases.

MNT: Remove deprecated np.float usage

---

.circleci/config.yml
.github/workflows/package.yml
.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
doc/interfaces.rst
nipype/algorithms/confounds.py
nipype/algorithms/metrics.py
nipype/info.py
nipype/interfaces/afni/base.py
nipype/interfaces/base/traits_extension.py
nipype/interfaces/diffusion_toolkit/base.py
nipype/utils/misc.py
nipype/utils/tests/test_filemanip.py
setup.py

Release prep for 1.6.1. No specific timeline.
Remaining issues/PRs:
@henrymj @d-vogel If you would like to be listed as authors on the Zenodo releases, could you please provide your preferred name, affiliation, and ORCID?

REL: 1.6.1

---

nipype/algorithms/confounds.py
nipype/interfaces/afni/base.py
nipype/interfaces/afni/utils.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/base/core.py
nipype/interfaces/base/support.py
nipype/interfaces/fsl/base.py
nipype/interfaces/fsl/model.py
nipype/interfaces/petpvc.py
nipype/interfaces/quickshear.py
nipype/interfaces/spm/base.py

STY: Make private member name consistent with the rest of them

---

nipype/interfaces/base/core.py
nipype/interfaces/base/support.py
nipype/utils/profiler.py

Python contexts seem the most appropriate pattern to follow.
Fixes # .

RF: Clean-up the BaseInterface ``run()`` function using context

---

nipype/interfaces/ants/registration.py
nipype/interfaces/ants/tests/test_auto_Registration.py
nipype/interfaces/base/tests/test_core.py

ENH: ``verbose`` input should not be hashed in ``ants.Registration``

---

docker/generate_dockerfiles.sh

Fixing an apparent datalad 0.15 regression that causes failures if `user.name` and `user.email` aren't set in Docker containers.

MNT: Add user name and email to Docker to appease git/annex/datalad

---

nipype/interfaces/io.py

Updates `BIDSDataGrabber` to reflect that `extensions` is a deprecated keyword, in favor of `extension`
Related issue: https://neurostars.org/t/issue-with-bidsdatagrabber-in-nipype-1-6-1/20243/3
- [ X ] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

FIX: Extension not extensions, after pybids v0.9

---

nipype/interfaces/fsl/maths.py

When setting MathsCommand().inputs.out_file argument, a Trait error is thrown because of the exists=True, although this file is to be created. This PR fixed this by removing the `exists=True` argument.
Fixes #3384 .
* Removed `exists=True` from `MathsOutput` `File()`.

[FIX] Removed exists=True from MathsOutput

---

nipype/algorithms/tests/test_CompCor.py

Debian's updating LAPACK to 3.10 revealed that we weren't handling sign flips for CompCor components.
This patch is split into two components, one cleaning up the test so we can use `np.allclose`, and the other switching to and validating an allclose that tolerates sign flips of entire columns, but not arbitrary sign flips.
Closes #3382.

TEST: Allow SVD columns to flip sign

---

nipype/interfaces/base/support.py

When running Nipype 1.7.0 with `enable_resource_monitor`, I get the following error:
```
File "/usr/local/miniconda/lib/python3.8/site-packages/halfpipe/plugins/linear.py", line 45, in run
node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
result = self._run_interface(execute=True)
File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
return self._run_command(execute)
File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 715, in _run_command
result = self._interface.run(cwd=outdir, ignore_exception=True)
File …
```

Fix `ValueError` when using `ResourceMonitor`

---

nipype/info.py
nipype/interfaces/dipy/base.py
nipype/interfaces/dipy/tests/test_base.py

This PR should fix the import issue with the DIPY interface. DIPY project introduces a new deprecator decorator which was not well handled by  `inspect.getfullargspec()`. So,  I just replace `inspect.getfullargspec()`  by `inspect.signature()`. 
fix #3411
fix https://github.com/dipy/dipy/issues/2402
Could you test this PR  @koenhelwegen  @HippocampusGirl? Thank you.

[FIX] Import error for nipype.interfaces.dipy.base

---

.zenodo.json
nipype/interfaces/dcm2nii.py
nipype/interfaces/tests/test_dcm2nii.py

This PR should fix the issue with dcm2niix interface not able to parse the output files when the file name contains meta characters. 
Fixes #3416 .

[FIX] Escape metacharacters when parsing dcm2niix outputs

---

nipype/interfaces/ants/tests/test_auto_ImageMath.py
nipype/interfaces/ants/utils.py

This PR addresses Issue #3434 . ReplicateImage and ReplicateDisplacement operations have been included in ANTs's ImageMath interface. Futhermore several other operations, that work well with the current structure of the interface, are included. Also, "args" trait has been overloaded so that its content is in the last position of the command line. Finally, for several of the included operations, copying the header of the input image does not make sense. A tuple called "_no_copy_header_operation" is defined to list such operations.

[ENH] Include several operations to ANTs's ImageMath interface, including ReplicateImage and ReplicateDisplacement

---

.github/workflows/tests.yml
nipype/info.py
nipype/sphinxext/apidoc/__init__.py
nipype/sphinxext/apidoc/docstring.py
nipype/utils/tests/test_cmd.py

Should be advertising that we support 3.9. Checking that we support 3.10 while we're at it.
Next minor release should drop support for 3.6.

MNT: Test on Python 3.10

---

nipype/interfaces/mrtrix/convert.py

The dipy function `move_streamlines` was removed (https://dipy.org/documentation/1.1.1./api_changes/) and later added back under a different name (https://github.com/dipy/dipy/commit/1046084862054166ec23f58ecf5b7c802c047ab3).
I haven't been able to test this yet due to an unrelated error (#3413).

rename dipy `move_streamlines` to `transform_tracking_output`

---

nipype/interfaces/ants/base.py
nipype/interfaces/ants/tests/test_base.py

FIX: Use a more robust strategy for detecting ANTs version

---

nipype/algorithms/metrics.py

FIX: Change plt.hist() argument from deprecated 'normed' to 'density'

---

nipype/algorithms/icc.py

@bbfrederick Post #3453, I got motivated to look at your PR again. I grokked the code a little better and realized we could do this more Pythonically.
WDYT? I set the `maxsize=1` to match your effective cache size. I don't really know how big these matrices can get, so I'm not sure whether that was a memory optimization or just an assumption that the number of switches back and forth between shapes is likely to be small.
@kristoferm94 Would be interested in your thoughts. This does break up the improved matrix ordering you provided, but I suspect the caching benefit is going to dominate here.
As some basic tests:
```Python
In [1]: import numpy as np
In [2]: rng = np.random.default_rng()
In [3]: from nipype.algorithms.icc import *
In [4]: %time ICC_rep_anova(rng.normal(size=(50, 10)))
CPU …
```

RF: Optimize ICC_rep_anova with a memoized helper function

---

.circleci/config.yml

OSF seems to have been down for a bit. This should save us some time anyway.

CI: Cache test data

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Preparation for the 1.8.0 release, targeting Thursday.
The main impetus is the PETSurfer interfaces (#3437) which it will help people to have released. Also, we're dropping support for Python 3.6, which is overdue.

REL: 1.8.0

---

nipype/external/tests/test_version.py
nipype/external/version.py

Turns out we need LooseVersions to be compatible with one another.

FIX: Make vendored LooseVersion comparable to distutils.version.LooseVersion

---

nipype/__init__.py
nipype/interfaces/base/core.py

In cases where `check_latest_version` returned None, each time
`BaseInterface.__init__` was called would lead to another server ping.
This avoids this loop by falling to a string, n/a, if the server fails
to produce a version.
Fixes #3483 .

FIX: Avoid excessive etelemetry pings

---

nipype/interfaces/mrtrix/convert.py

FIX: Delay access of nibabel.trackvis until actually needed

---

nipype/algorithms/confounds.py
nipype/algorithms/tests/test_auto_ComputeDVARS.py

Closes #3487.
Also made some changes to avoid numpy deprecation warnings, and used nibabel 3+ idioms for coercing data types.

FIX: Add tolerance parameter to ComputeDVARS

---

nipype/interfaces/fsl/utils.py

Hi,
This pull request is a fix to a potential bug about wrong order of function arguments at `nipype/interfaces/fsl/utils.py`. Please check the changes.
Best,
Jingxuan

Fix a bug about wrong order of function arguments

---

.github/workflows/contrib.yml
.github/workflows/package.yml
.github/workflows/tests.yml
nipype/algorithms/tests/test_CompCor.py
nipype/info.py

This basically sets a lifetime on nipype 1.x. Refactoring to work with breaking changes in traits seems more work than it's worth (and would presumably break with older traits).
Fixes # .

MNT: Pin traits < 6.4

---

nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py

This change is fully backwards compatible and will
not affect existing pipelines, but it will prevent
the pipeline engine from crashing when some parameters
are long and it was trying to create subdirectories
longer than 255 characters (a typical unix limit).
Fixes #2061 .

Fixed bug for work dirs longer than 255 characters, fixes #2061

---

nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/tests/test_nodes.py

Partially addresses #3492 
This adds runtime information to the error message when node execution fails.
1.8.x series:
```
220914-11:28:50,439 nipype.workflow WARNING:
[Node] Error on "test-fail" (/private/tmp/nipype/test-fail)
File "/private/tmp/nipype/test-fail.py", line 21, in <module>
eg = x.run()
File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
result = self._run_interface(execute=True)
File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
return self._run_command(execute)
File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in …
```

FIX: Provide more runtime information when node execution fails

---

nipype/interfaces/matlab.py

https://mathworks.com/help/compiler/isdeployed.html
> The path of a deployed application is fixed at compile time and cannot change. Use `isdeployed` to ensure that the application uses path modifying functions, such as `addpath`, before deployment.
As suggested by @servoz, this fixes the case where nipype calls SPM12 Standalone, associated to Matlab Compiler Runtime (MCR) R2019a (9.6) or later. Upcoming versions of SPM12 Standalone will most probably be compiled with Matlab R2021b, and hence will be subject to this bug.
Fixes #3507.
* Do not call `addpath` in Matlab scripts called from a deployed Matlab application.

FIX: Deployed Matlab applications must not call addpath()

---

nipype/algorithms/confounds.py

Bug introduced in #3489. Numpy 1.22 introduced method and deprecated interpolation in a single shot. Typically, they deprecate a few versions after they introduce an alternative, so I missed this and now things that have pinned, e.g., numpy 1.21 are going to break on nipype.

FIX: Use interpolation/method in numpy.percentile as available

---

.github/workflows/tutorials.yml

This is an effort to remove a manual step in the release process. 
Currently, we are submitting a PR to the tutorials repo to build from the current release branch.
This proposes a new action that runs whenever an upstream `rel/*` branch is pushed to that:
1) Triggers a "manual" dispatch to the tutorial's action
1) Tracks the status of the job until it i) succeeds, ii) fails, or iii) hits the timeout (currently 1 hour)
For this to work, it will require (cc @djarecka who may have the proper permissions):
1) ~https://github.com/miykael/nipype_tutorial/pull/180 to be merged in~
1) A PAT for the nipype_tutorial repo to be created and added to this organization's secrets as `TUTORIAL_ACCESS_TOKEN`

MAINT: Add github action to trigger tutorials for release branches

---

doc/devel/interface_specs.rst
doc/devel/provenance.rst
nipype/interfaces/afni/utils.py
nipype/interfaces/diffusion_toolkit/dti.py
nipype/interfaces/dtitk/utils.py
nipype/interfaces/minc/minc.py
nipype/interfaces/mipav/developer.py
nipype/interfaces/semtools/diffusion/gtract.py
nipype/interfaces/slicer/generate_classes.py
nipype/interfaces/slicer/registration/brainsfit.py
nipype/interfaces/slicer/registration/brainsresample.py
nipype/interfaces/spm/model.py
nipype/pipeline/engine/utils.py
nipype/utils/spm_flat_config.m
nipype/utils/tests/test_filemanip.py

Fix typos.
* Fix a few more typos.

DOC: Fix a few more typos

---

.github/workflows/tutorials.yml

Currently, after the tutorial workflow is dispatched, it runs to completion, regardless of our workflow ending early. This adds a step to cancel the workflow upon failure or cancellation, to avoid overbearing the external runners.

CI: Allow tutorial test cancellation

---

nipype/interfaces/fsl/model.py

Fixes #3520  .
- Removed leftover debug print statement in FEAT class

Removed leftover debug print statement in FEAT class

---

nipype/interfaces/mrtrix3/preprocess.py

The function `_list_outputs` in `DWIBiasCorrect` doesn't take into account the fact that `output_file` is not a mandatory input, thus making any pipeline using this interface without specifying the output crash. It crashes with the following error:

FIX: Check for non-mandatory output in DWIBiasCorrect

---

.github/workflows/contrib.yml
.github/workflows/tests.yml
.github/workflows/tutorials.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

.github/workflows/tests.yml
tools/ci/env.sh

CI is broken because nipy is not being updated to deal with numpy deprecations. This removes nipy tests generally. I'm seeing if I can add a requirement config that will cap numpy for now so we don't skip these tests entirely.

CI: Disable nipy tests generally, re-add with max numpy

---

nipype/interfaces/dcmstack.py

Fixes issues with dcmstack interface on Python3 with newer pydicom.

BF: Update dcmstack interface for Py3 / newer pydicom

---

.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Preparation for the 1.8.6 release, delayed by broken CI, but needs doing.
@MatthieuJoulot @somso2e @sashashura Please let me know if you would like to be credited in releases, and if so what name, ORCID and affiliation you would like. See https://github.com/nipy/nipype/blob/master/.zenodo.json for examples.
* ... Please let me know if you want to try to merge something in. This is really intended to get things fixed for downstream projects, though.

REL: 1.8.6

---

.codespellrc
.github/workflows/codespell.yml
doc/changelog/0.X.X-changelog.rst
doc/changelog/1.X.X-changelog.rst
nipype/algorithms/icc.py
nipype/interfaces/ants/registration.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/base/specs.py
nipype/interfaces/base/tests/test_core.py
nipype/interfaces/cmtk/nx.py
nipype/interfaces/freesurfer/longitudinal.py
nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/preprocess.py
nipype/interfaces/io.py
nipype/interfaces/mrtrix/tracking.py
nipype/interfaces/spm/tests/test_utils.py
nipype/interfaces/tests/test_io.py
nipype/utils/profiler.py
tools/ex2rst

there was c634f29277c2195982c376ede7d6ff07503e6fdc which brought in lots of fixes already but did not "incorporated" codespelling into CI.  This one does that + fixes some remaining/fresh typos.

codespell: config, workflow, typos fixed

---

nipype/interfaces/fsl/epi.py

`out_shell_pe_translation_parameters` in `fsl.epi.eddy` appeared twice, removed the second one to avoid redundancy

STY: Remove duplicated trait in EddyOutputSpec

---

nipype/interfaces/freesurfer/petsurfer.py

This PR fixes the output specification for 'optimization_schema' in the petsurfer interface GTMPVC.
Fixes #3570 https://github.com/nipy/nipype/issues/3570#issue-1713336530
* update output to match input spec

FIX: update self.inputs.optimization in outputs for GTMPVC

---

.pre-commit-config.yaml
.zenodo.json
nipype/interfaces/spm/model.py

Hi,
The SPM interface currently does not support voxel-based FDR. The MATLAB version of SPM readily provides this functionality, however, if you change your SPM defaults accordingly. There is no easy way to achieve this in nipype. I believe that FDR is a very useful way of correcting for multiple comparisons when analyzing fMRI data. Other users share this view because a similar PR has already been made by Lorenzo [here](https://github.com/nipy/nipype/pull/3333). The changes proposed in my PR are minimally invasive and thus are very unlikely to cause any problems with respect to backward compatibility. 
* Added a single new binary (Boolean) input for whether or not the user wants to use voxel-based FDR.
* Default is False.
* ThresholdInputSpecs checks if the input for this parameter …

[ENH] Enable SPM voxel-based FDR

---

nipype/sphinxext/plot_workflow.py

In Python 3, `io.open()` is an alias for the builtin `open()` function:
https://docs.python.org/3/library/io.html#io.open
* io.open() → open()

[REF] io.open() → open()

---

nipype/interfaces/fsl/dti.py

updated random_seed to accept an integer value and sample_random_points to accept a float value
https://github.com/nipy/nipype/issues/3534

[FIX] update sample_random_points and random_seed type of ProbTrackXBaseInputSpec

---

.github/workflows/tests.yml
nipype/info.py
nipype/utils/filemanip.py

Testing on 3.11. Curious to see how this breaks.

CI: Test on Python 3.11

---

nipype/interfaces/spm/model.py
nipype/interfaces/spm/tests/test_auto_EstimateModel.py

If factorial design is used for fMRI model specification (parameter "factor_info" in Level1design), spm automatically creates contrasts (con*, ess*, spmF* and spmT* images) during model estimation (EstimateModel). 
Those outputs are not yet in EstimateModel in Nipype, the aim of this PR is to add them. 
Issue : https://github.com/nipy/nipype/issues/3576

add contrast outputs for EstimatedModel 

---

nipype/utils/filemanip.py
nipype/utils/subprocess.py

MNT: Replace deprecated locale.getdefaultlocale

---

.zenodo.json
nipype/interfaces/mrtrix3/preprocess.py

Just a small fix in MRtrix3's DWIPreproc class - referencing `out_grad_mrtrix` instead of `export_grad_mrtrix` in the `_list_outputs` method of the class.
Fixes #3595.
* Fixed DWIPreproc class.

FIX: DWIPreproc issue

---

nipype/interfaces/spm/preprocess.py

Please consider this PR that will be fast to review:
1-  `deformation_file` and `image_to_align` are mutually exclusive. So we can't use the `mandatory=True` option for these two traits, as one of them will always be Undefined.
2- the `self.inputs.jobtype == "estimate"` statement is useless because the `jobtype` trait can only take values in [["est", "write", "estwrite"]](https://github.com/nipy/nipype/blob/dac6aee9a0f331c4f498f14a7ffb84abc989594a/nipype/interfaces/spm/preprocess.py#L1315).
For point 2- it's not very important, it doesn't stop the run, it's just useless.
For point 1-, it's critical because the condition for one or the other can never be met, and this blocks the use of this process in our application, which uses nipype.

Fix typo in spm.Normalize12 process

---

CONTRIBUTING.md
nipype/interfaces/afni/preprocess.py
nipype/interfaces/dcmstack.py
nipype/interfaces/dipy/base.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/io.py
nipype/interfaces/semtools/brains/utilities.py
nipype/interfaces/semtools/diffusion/gtract.py
nipype/interfaces/semtools/diffusion/tractography/ukftractography.py
nipype/interfaces/semtools/segmentation/specialized.py
nipype/interfaces/slicer/registration/brainsfit.py
nipype/pipeline/plugins/sge.py
tools/update_changes.sh

DOC: Fix typos newly found by codespell

---

nipype/utils/draw_gantt_chart.py

This patch attempts to convert string date representations back to datetime.date objects to that computations
can be done on them.
Partially Fixes #3527
After fixing the string-to-date object crash, other crashes began to appear.  Hopefully, a more knowledgeable person can identify what needs to happen quickly.

BUG: Reading serialized event requires conversion of dates

---

nipype/pipeline/engine/utils.py

Codespell currently fails due to false positive detection of “inports”, which are input ports and not a misspelling of imports.
Also makes the code more clear I think.

Adjusted variable names for clarity and codespell false positives

---

nipype/interfaces/afni/preprocess.py

DOC/FIX: Fix wrong name, should be al_ea

---

nipype/interfaces/petpvc.py

This PR adds single-target PVC correction to the PETPVC interface in Nipype. The STC is already included in PETPVC, however, the interface needs to be updated to reflect these changes.
Fixes #3633
1. Add the 'STC' option to the 'pvc' flag in the PETPVC interface

ENH: add STC PVC to PETPVC interface

---

nipype/interfaces/mrtrix3/tests/test_auto_MRTransform.py
nipype/interfaces/mrtrix3/utils.py

If several arguments are used (for example invert and linear_transform) they are not all take into account (and so it is not the same behavior as the native mrtrix3 command). 
I think that it is because they are all set to `position = 1`
I think it is not necessary to precise `position` for those arguments as `argstr` is already filled with an information about position .

[FIX] MRTrix3 change inputs position for MRTransform

---

nipype/interfaces/utility/csv.py
nipype/interfaces/utility/tests/test_auto_CSVReader.py
nipype/interfaces/utility/tests/test_csv.py

Fixes #3635 
* Use the `csv` library to parse CSV files, so that quoted fields are correctly parsed.
* Add a `delimiter` field to `CSVReader` so that things like TSVs can be parsed.

FIX: Parse commas in CSV fields

---

.zenodo.json
nipype/interfaces/mrtrix3/utils.py

- added Hybrid Surface and Volume Segmentation ('hsvs') option to the 5TT image generation class
- removed the in_file existing requirement (exists=True -> exists=False) for 5ttgen because hsvs requires a directory not a file as input
- changed '-inverse' parameter location from 1 to 2 in mrtransform class (to make it possible to insert it in the command together with other parameters)

ENH: added 'hsvs' option to 5ttgen + mrtransform fix

---

.github/workflows/contrib.yml
.github/workflows/tests.yml
.github/workflows/tutorials.yml
nipype/info.py
tools/ci/env.sh

If this passes, I'll try re-adding nipy tests.

Test Python 3.12 support

---

nipype/external/fsl_imglob.py
nipype/interfaces/io.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/sge.py
nipype/pipeline/plugins/sgegraph.py
nipype/pipeline/plugins/slurmgraph.py

Apply `UP` rules except `UP031` (598 errors) and `UP032` (86 errors)
* Apply ruff/pyupgrade rule UP018
UP018 Unnecessary `float` call (rewrite as a literal)
* Apply ruff/pyupgrade rule UP024
UP024 Replace aliased errors with `OSError`
* Apply ruff/pyupgrade rule UP030
UP030 Use implicit references for positional format fields
* Apply ruff/pyupgrade rule UP036
UP036 Version block is outdated for minimum Python version

STY: Apply ruff/pyupgrade rules

---

nipype/algorithms/misc.py
nipype/interfaces/ants/registration.py
nipype/interfaces/cmtk/nx.py
nipype/interfaces/cmtk/tests/test_nbs.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/elastix/registration.py
nipype/interfaces/fsl/model.py
nipype/interfaces/io.py
nipype/interfaces/nipy/preprocess.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/somaflow.py
nipype/sphinxext/apidoc/docstring.py
nipype/sphinxext/plot_workflow.py
nipype/utils/docparse.py

Partially apply `FURB` rules, where they make sense, except `FURB101` (26 errors), `FURB103` (21 errors), `FURB113` (2 errors), `FURB118` (3 errors), `FURB140` (2 errors), `FURB171` (25 errors).
* STY: Apply ruff/refurb rule FURB113
FURB113 Use `list.extend(...)` instead of repeatedly calling `list.append()`
* STY: Apply ruff/refurb rule FURB129
FURB129 Instead of calling `readlines()`, iterate over file object directly
* STY: Apply ruff/refurb rule FURB136
FURB136 Replace `20 if len(nodiffidx) >= 20 else len(nodiffidx)` with `min(20, len(nodiffidx))`
* STY: Apply ruff/refurb rule FURB148
FURB148 `enumerate` index is unused, use `for x in y` instead
* STY: Apply ruff/refurb rule FURB167
FURB167 Use of regular expression alias `re.X`
FURB167 Use of regular expression alias `re.M`

STY: Apply ruff/refurb rules

---

nipype/interfaces/ants/__init__.py
nipype/interfaces/base/support.py
nipype/interfaces/slicer/generate_classes.py
nipype/interfaces/spm/base.py
nipype/pipeline/plugins/base.py
nipype/pipeline/plugins/condor.py
nipype/pipeline/plugins/lsf.py
nipype/pipeline/plugins/oar.py
nipype/pipeline/plugins/pbs.py
nipype/pipeline/plugins/sge.py
nipype/pipeline/plugins/sgegraph.py
nipype/pipeline/plugins/slurm.py
nipype/pipeline/plugins/slurmgraph.py
nipype/pipeline/plugins/tools.py
nipype/utils/filemanip.py
nipype/utils/nipype_cmd.py

Apply [Ruff-specific rules (RUF)](https://docs.astral.sh/ruff/rules/#flake8-bugbear-b), except:
* [RUF002](https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-docstring/) (seems useless to me)
* [RUF005](https://docs.astral.sh/ruff/rules/collection-literal-concatenation/) (not sure the resulting code is more readable)
* [RUF012](https://docs.astral.sh/ruff/rules/mutable-class-default/) (only useful with MyPy)
* [RUF015](https://docs.astral.sh/ruff/rules/unnecessary-iterable-allocation-for-first-element/) (left for later...)
* [RUF017](https://docs.astral.sh/ruff/rules/quadratic-list-summation/) (breaks CI, left for later...)

STY: Apply ruff rules (RUF)

---

nipype/algorithms/rapidart.py
nipype/interfaces/afni/base.py
nipype/interfaces/ants/resampling.py
nipype/interfaces/base/core.py
nipype/interfaces/base/specs.py
nipype/interfaces/brainsuite/brainsuite.py
nipype/interfaces/cat12/surface.py
nipype/interfaces/dtitk/base.py
nipype/interfaces/freesurfer/model.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/fsl/base.py
nipype/interfaces/fsl/tests/test_preprocess.py
nipype/interfaces/io.py
nipype/interfaces/mne/base.py
nipype/interfaces/niftyfit/base.py
nipype/interfaces/niftyreg/base.py
nipype/interfaces/petpvc.py
nipype/interfaces/spm/preprocess.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/tests/test_legacymultiproc_nondaemon.py
nipype/pipeline/plugins/tests/test_linear.py
nipype/pipeline/plugins/tests/test_oar.py
nipype/pipeline/plugins/tests/test_pbs.py
nipype/pipeline/plugins/tests/test_somaflow.py
nipype/pipeline/plugins/tools.py
nipype/utils/docparse.py
nipype/utils/filemanip.py
nipype/utils/tests/test_filemanip.py
tools/checkspecs.py

Apply [flynt (FLY)](https://docs.astral.sh/ruff/rules/#flynt-fly) rules.

STY: Apply ruff/flynt rules (FLY)

---

pyproject.toml

https://learn.scientific-python.org/development/guides/repo-review/?repo=nipy%2Fnipype&branch=master

MNT: Apply assorted repo-review rules

---

nipype/pipeline/plugins/tests/test_sgelike.py
nipype/utils/tests/test_filemanip.py

Apply [flake8-raise (RSE)](https://docs.astral.sh/ruff/rules/#flake8-raise-rse) rules.

STY: Apply ruff/flake8-raise rules (RSE)

---

nipype/algorithms/misc.py
nipype/interfaces/ants/registration.py
nipype/interfaces/cmtk/cmtk.py
nipype/interfaces/cmtk/nx.py
nipype/interfaces/dcm2nii.py
nipype/interfaces/dipy/reconstruction.py
nipype/interfaces/dipy/simulate.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/freesurfer/utils.py
nipype/interfaces/fsl/model.py
nipype/interfaces/mrtrix3/base.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/plugins/sge.py
nipype/pipeline/plugins/tests/test_legacymultiproc_nondaemon.py
nipype/utils/draw_gantt_chart.py
nipype/utils/filemanip.py
nipype/utils/nipype2boutiques.py

Apply [flake8-pie (PIE)](https://docs.astral.sh/ruff/rules/#perflint-perf) rules, except:
* [PIE794](https://docs.astral.sh/ruff/rules/duplicate-class-field-definition/) (doesn't help here)

STY: Apply ruff/flake8-pie rules (PIE)

---

nipype/algorithms/confounds.py
nipype/algorithms/misc.py
nipype/algorithms/modelgen.py
nipype/interfaces/ants/registration.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/base/core.py
nipype/interfaces/cmtk/cmtk.py
nipype/interfaces/dipy/simulate.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/fsl/fix.py
nipype/interfaces/io.py
nipype/interfaces/mne/base.py
nipype/interfaces/nilearn.py
nipype/interfaces/nipy/model.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/somaflow.py
nipype/utils/filemanip.py
nipype/utils/misc.py
nipype/utils/nipype2boutiques.py

Apply [Perflint (PERF)](https://docs.astral.sh/ruff/rules/#perflint-perf) rules, except:
* [PERF203](https://docs.astral.sh/ruff/rules/try-except-in-loop/)

STY: Apply ruff/Perflint rules (PERF)

---

nipype/interfaces/mrtrix3/tests/test_auto_Generate5tt.py
nipype/interfaces/mrtrix3/utils.py

Just a small addition of inputs to match those available through the [original implementation of MRTrix3](https://mrtrix.readthedocs.io/en/dev/reference/commands/5ttgen.html).
Fixes #3657.
Just some additional inputs (t2 file, mask file, etc.).

[ENH] Added available inputs for MRTrix3's 5ttgen

---

nipype/algorithms/modelgen.py
nipype/algorithms/tests/test_CompCor.py
nipype/interfaces/ants/segmentation.py
nipype/interfaces/base/core.py
nipype/interfaces/cmtk/cmtk.py
nipype/interfaces/diffusion_toolkit/dti.py
nipype/interfaces/diffusion_toolkit/odf.py
nipype/interfaces/freesurfer/preprocess.py
nipype/interfaces/fsl/model.py
nipype/interfaces/io.py
nipype/interfaces/spm/model.py
nipype/interfaces/utility/wrappers.py
nipype/pipeline/engine/nodes.py
nipype/pipeline/engine/utils.py
nipype/pipeline/engine/workflows.py
nipype/pipeline/plugins/base.py
nipype/pipeline/plugins/linear.py
nipype/scripts/instance.py
nipype/utils/docparse.py
nipype/utils/filemanip.py
nipype/utils/misc.py
nipype/utils/nipype_cmd.py

Apply [flake8-comprehensions (C4)](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4) rules, except:
* [C408](https://docs.astral.sh/ruff/rules/unnecessary-collection-call/) (15011 errors!)

 STY: Apply ruff/flake8-comprehensions rules (C4) 

---

nipype/algorithms/tests/test_modelgen.py
nipype/interfaces/afni/utils.py
nipype/interfaces/ants/utils.py
nipype/interfaces/base/support.py
nipype/interfaces/elastix/utils.py
nipype/interfaces/fsl/utils.py
nipype/interfaces/spm/model.py
nipype/interfaces/tests/test_io.py
nipype/interfaces/utility/wrappers.py
nipype/pipeline/engine/tests/test_engine.py
nipype/pipeline/engine/utils.py
nipype/pipeline/plugins/debug.py
nipype/utils/config.py
nipype/utils/profiler.py
nipype/utils/provenance.py
tools/checkspecs.py

Apply [flake8-bugbear (B)](https://docs.astral.sh/ruff/rules/#flake8-bugbear-b) rules, except:
* [B011](https://docs.astral.sh/ruff/rules/assert-false/)
* [B017](https://docs.astral.sh/ruff/rules/assert-raises-exception/)
* [B018](https://docs.astral.sh/ruff/rules/useless-expression/)
* [B020](https://docs.astral.sh/ruff/rules/loop-variable-overrides-iterator/)
* [B028](https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/)
* [B904](https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/)

STY: Apply ruff/flake8-bugbear rules (B)

---

nipype/interfaces/base/support.py
nipype/pipeline/engine/workflows.py
nipype/utils/datetime.py

It is mandated by starting to receive a DeprecationWarning in python 3.12
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC)
discovered while addressing some other rot in heudiconv.

Use regular ".now" instead of ".utcnow" with UTC zone

---

nipype/interfaces/mrtrix3/tests/test_auto_TensorMetrics.py
nipype/interfaces/mrtrix3/utils.py

Simply changed the inheritance to the correct one (`TensorMetricsInputSpec` instead of `CommandLineInputSpec`
Fixes #3662.

Changed inheritence of TensorMetricsInputSpec

---

.zenodo.json
nipype/interfaces/fsl/base.py
nipype/interfaces/fsl/model.py

Fixes # .
FILMGLS is an interface for the FSL utility (film_gls) that fits GLM models to fMRI data. Most of FSL is only compatible with NIFTI files and NIFTI variants (e.g. NIFTI_GZ), but modern versions of film_gls in particular support gifti processing and output .func.gii files if a surface mode argument is included when invoking film_gls. Surface mode selection is supported by nipype but cannot be used in nipype workflows due to automated substitution of supported extensions for FSL outputs. With most FSL utilities the extension used to specify output files on the command line automatically selects the output format FSL uses, but film_gls in surface mode produces *.func.gii file in spite of this substitution. When workflow nodes downstream of FILMGLS then attempt to use the outputs of …

ENH: FILMGLS gifti output support in surface mode

---

nipype/interfaces/base/core.py

`pkgutil.find_loader` was deprecated in 3.12, will be removed in 3.14, and its replacement has been around since 3.4.

RF: Replace deprecated pkgutil.find_loader with importlib.util.find_spec

---

nipype/pipeline/engine/utils.py

if I'm understanding [evaluate_connect_function](https://github.com/nipy/nipype/blob/4d1352ade7171fd5f55eff62cee4c99a4f9cfed1/nipype/pipeline/engine/utils.py#L687) correctly, the _intent_ of the if-clause is to catch errors that arise from calling libraries/modules/functions that were imported at the module level (as opposed to nesting the imports at the function level), and raises a more informative error for those cases. 
I think https://github.com/nipreps/nibabies/pull/365 gives one example where the if-clause _should_  catch such an error, but doesn't, because the error doesn't start with `"global name"`. So I think it should be okay to make the if-clause more permissive, i.e. just check if the error message ends with `"is not defined"`, then return the extra-informative error message …

FIX: evaluate_connect_function should raise error on un-nested imports

---

nipype/interfaces/spm/model.py
nipype/interfaces/tests/test_matlab.py
nipype/utils/filemanip.py

Fixes #2162
Fixes #3432
* Replace `sio.loadmat` with a load function specific for `SPM.mat` files, so it also supports >2 GB mat 7.3 HDR files
* Fix MATLAB's `test_run_interface` which I also encountered while running the tests

[FIX] mat 7.3 support for SPM.mat files

---

nipype/interfaces/fsl/utils.py

fsl.MotionOutliers output spec no longer requires out_file to exist. fsl_motion_outliers does not create an output file when no timepoints are above the threshold, and in this situation fsl.MotionOutliers would throw a FileNotFoundError. This pull request fixes that immediate problem.

fsl.MotionOutliers output spec no longer requires out_file to exist

---

nipype/interfaces/ants/registration.py

```txt
https://github.com/ANTsX/ANTs/commit/e1e47994b233441726c1440cc2fb077a24287d6bo
The flag --use-estimate-learning-rate-once was not used inside of antsRegistration, and was removed on 2022-08-09 in ants commit e1e47994b
e1e47994b Examples/antsRegistration.cxx
(Nick Tustison     2022-08-09 16:45:01 -0700 453)
//   option->SetLongName("use-estimate-learning-rate-once");
```
Removes unnecessary antsRegistration flag that never had an effect in the code, and has been removed since 2022-08-09.

ENH: Remove unused and recently unsupported antsRegistration flag

---

.zenodo.json
nipype/interfaces/afni/preprocess.py

Fixes #3696.
* https://github.com/nipy/nipype/blob/237a9a7ca244ca87916e1f9c5bd73c3f08c00c5d/nipype/interfaces/afni/preprocess.py#L2744 ↓ https://github.com/nipy/nipype/blob/44e9d675d9773baaaa9aeddf38ce6a8d04a208b0/nipype/interfaces/afni/preprocess.py#L2744
* Replaces `NetCorr.inputs.ts_Z_corr` with `NetCorr.inputs.ts_wb_Z`
* Unwraps `ts_wb_*` checks from `isdefined`
* Adds myself to `.zenodo.json` https://github.com/nipy/nipype/blob/cbcb487a90eb293acfabf1a444383c4a4dfa64c8/.zenodo.json#L923-L927

[FIX] `ts_Z_corr` → `ts_wb_Z`

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Prep for 1.9.1 release, targeting tomorrow or whenever we can.

REL: 1.9.1

---

doc/changelog/1.X.X-changelog.rst
nipype/info.py

REL: 1.9.2

---

.wci.yml

The headline information contains a colon, thus it is necessary to put the text within quotes. I will comment the nipype repo in the Workflows Community website for now as it is failing the build. Once this fix is accepted, I will enable the repository again. Thank you!

Update to .wci.yml

---

nipype/pipeline/engine/nodes.py
nipype/pipeline/plugins/multiproc.py

Any workflow running with updatehash=True will crash
That happens because in nodes.py line 457 we try to update the hashfile even if the node was never executed before, so no hashfile is found and _update_hash function raises an exception.

fix: Resolve crashes when running workflows with updatehash=True

---

nipype/sphinxext/apidoc/__init__.py

fix: Allow nipype.sphinx.ext.apidoc Config to work with Sphinx 8.2.1+

---

tox.ini

Traits 7 is released, with Python 3.13 support.

chore: Remove direct URL for traits on py313

---

nipype/algorithms/misc.py

Fixes #3712 .
- try getting the len of `idxs`
- if it fails with TypeError (which happens when `idxs` is a 0D array)
- set `nels` to 1

[FIX] Set length to 1 when np.squeeze returns a 0D array

---

nipype/info.py
nipype/pipeline/plugins/multiproc.py
nipype/pipeline/plugins/tools.py
nipype/utils/gpu_count.py

fix #3717 
I tried to write a simpler implementation of `getGPUs` from gputil package. 
I used a separate file to include their license.
This need to be tested under windows with Python 3.12+ and I don't have such system, so it's **untested** for now.

reimplementation of gpu_count

---

doc/changelog/1.X.X-changelog.rst

#3716 needs to be released to unbreak doc builds. #3642 justifies a minor version bump.

REL: 1.10.0
