nipype/interfaces/io.py

Add abspath to json sink output file

---

CHANGES
nipype/interfaces/dcmstack.py
nipype/interfaces/tests/test_auto_DcmStack.py
nipype/interfaces/tests/test_auto_GroupAndStack.py
nipype/interfaces/tests/test_auto_MergeNifti.py
nipype/interfaces/tests/test_auto_SplitNifti.py

A new solution to DCMStack output folder

---

.travis.yml

based on information from here:
http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html

enh: update travis to deploy to pypi

---

nipype/utils/nipype_cmd.py
nipype/utils/tests/test_cmd.py

Provides functionality requested by dipy folks: https://github.com/nipy/dipy/pull/695

Added support for lists of files as command line inputs.

---

.gitignore
.mailmap
Makefile
README.rst
doc/README.txt
doc/devel/interface_specs.rst
doc/devel/matlab_interface_devel.rst
doc/devel/python_interface_devel.rst
doc/links_names.txt
doc/users/index.rst
doc/users/mapnode_and_iterables.rst
doc/users/mipav.rst
doc/users/nipypecmd.rst
doc/users/saving_workflows.rst
nipype/external/d3.js
tools/ex2rst

@satra 
These patches allow me to run:
python setup.py install; make specs; make check-before-commit
cleanly.  This allows for repeated runs do not report files that need to be committed to git.

Trailing whitespace romoval

---

nipype/algorithms/modelgen.py
nipype/algorithms/tests/test_modelgen.py

to fix bad merge in #1200, to solve issue #1198

refix conditions and duration matching issue

---

circle.yml
examples/test_spm.py
nipype/interfaces/spm/preprocess.py
nipype/interfaces/spm/tests/test_auto_Realign.py

See: https://neurostars.org/p/3047/

SPM realign used to omit the first volume/run

---

nipype/workflows/dmri/fsl/utils.py

This PR fixes #1232 (magic in lines 452-3)
Additionaly, some PEP8 fixes.

[FIX] Global name b0_indices not defined

---

nipype/interfaces/afni/preprocess.py

Fixes https://github.com/FCP-INDI/C-PAC/issues/370

skullstrip needs X... for something!

---

nipype/interfaces/spm/preprocess.py
nipype/interfaces/spm/utils.py

Change absolute imports to relative in 2 files.

fix: absolute to relative imports

---

nipype/pipeline/plugins/condor.py
nipype/pipeline/plugins/dagman.py
nipype/pipeline/plugins/lsf.py
nipype/pipeline/plugins/oar.py
nipype/pipeline/plugins/pbs.py
nipype/pipeline/plugins/pbsgraph.py
nipype/pipeline/plugins/sge.py
nipype/pipeline/plugins/sgegraph.py
nipype/pipeline/plugins/slurm.py
nipype/pipeline/plugins/slurmgraph.py

AFAIK this solution works on both versions.

Python 3 compatibility: os.environ.data to dict(os.environ)

---

nipype/interfaces/ants/resampling.py

this potentially addresses #1343

fix antsApplyTransforms examples

---

doc/links_names.txt

Updated IPython and a few other links I know have moved.
Not a comprehensive update.

DOC: Update link_names.txt

---

doc/users/plugins.rst

Just a new line in the doc about a plugin-args flag

Added important flag to the OAR section

---

nipype/testing/utils.py

@oesteban The strategy I went with in #1391 was to skip the test on a caught `IOError`, so this makes all failures appear as `IOError`. I'm open to an alternative skipping strategy.
cc @chrisfilo.
Closes #1408.

FIX: Raise IOErrors on mkfs.vfat and fusefat calls

---

nipype/interfaces/freesurfer/model.py

this failed at os.path.join if value was a bool

fix: segstats avgwf_txt_file can be a bool without error

---

examples/smri_fsreconall.py
nipype/workflows/smri/freesurfer/recon.py

I added some documentation to the create_reconall_workflow and its example script that may help.

DOC: Adds documentation to create_reconall_workflow

---

nipype/interfaces/fsl/epi.py
nipype/interfaces/fsl/tests/test_auto_ApplyTOPUP.py

Allow ```in_index``` to be undefined.

[ENH] Fill in_index automatically in ApplyTOPUP if not defined

---

.travis.yml
circle.yml
doc/users/install.rst
nipype/info.py
requirements.txt

re Chris's comment: https://github.com/nipy/nipype/pull/1490#discussion_r66707986

WIP/FIX clean up dependency, installation

---

nipype/interfaces/ants/registration.py

Changed method for setting default for invert_initial_moving_transfor…m and initial_moving_transform_com for Registration.
Changed try/except loop on integer values to a check for defined inputs and added a test.

Fix issue #1569

---

nipype/interfaces/dipy/base.py

[FIX] Dipy logged an error if not found

---

circle.yml
docker/nipype_test_base/Dockerfile
docker/nipype_test_py27/Dockerfile

With all the meat in the base image

[ENH] Minimize nipype test docker image

---

nipype/interfaces/tests/test_runtime_profiler.py

https://github.com/nipy/nipype/issues/1502#issuecomment-249398225

TST multiproc test fix, part 2

---

nipype/interfaces/base.py
nipype/interfaces/tests/test_runtime_profiler.py

https://github.com/nipy/nipype/issues/1663

TST Skip test until fixed

---

nipype/pipeline/engine/utils.py

This is related to issue #1684.
I am trying to figure out how to make a test for this case.

Improve inline functions in a series error message

---

README.rst

[FIX] README after neurostars is down

---

circle.yml
nipype/pipeline/plugins/tests/test_multiproc.py
nipype/pipeline/plugins/tests/test_multiproc_nondaemon.py

Temporary measure until: https://github.com/nipy/nipype/issues/1692 is resolved

skip python2 multiproc tests until the deadlock issue will be resolved

---

nipype/algorithms/confounds.py
nipype/algorithms/tests/test_confounds.py
nipype/interfaces/nilearn.py
nipype/interfaces/tests/test_nilearn.py

https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.89uwob8yetyv

Conform with BIDS Derivatives label names

---

nipype/interfaces/fsl/model.py

made melodic output paths absolute

---

nipype/interfaces/freesurfer/preprocess.py

Fix typo in ReconAllOutputSpec

---

nipype/interfaces/ants/registration.py

doc: fix desc for fixed_image

---

nipype/interfaces/fsl/model.py
nipype/interfaces/fsl/tests/test_Level1Design_functions.py
nipype/interfaces/script_templates/feat_ev_custom.tcl
nipype/interfaces/script_templates/feat_ev_hrf.tcl
nipype/interfaces/script_templates/feat_ev_none.tcl

Two more variables need to be added - `set fmri(basisorth1) 1` and `set fmri(basisfnum1) 1`, but I am still holding out because I don't get what they do exactly (and thus, how best to manage them).
I have [asked the FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1702&L=FSL&F=&S=&X=0DEDE23E0EB8FCD9BA&Y=ioanas%40biomed.ee.ethz.ch&P=191089) but gotten no reply. If you know anything about what these variables do exactly, I would be happy to know.

aded support for custom IRF in FSL models

---

nipype/interfaces/afni/utils.py

ENH: add name template and assign output filename for autobox

---

.zenodo.json
CONTRIBUTING.md
doc/about.rst

When releasing remember to:
- Use a consistent release title with the version number
- Populate the release description with the changelog

Added .zenodo.json file with instructions.

---

.zenodo.json

Thanks @effigies for the alert, and for digging up my OrcID :)

Update .zenodo.json with @bcipolli 's information

---

.zenodo.json

and i guess atom removes trailing whitespace

add: mathias to zenodo

---

.zenodo.json

Added myself to contributors list and made a formatting fix to the file.

DOC: Add contributor to .zenodo.json

---

nipype/interfaces/fsl/preprocess.py

doc: mcflirt mean image

---

nipype/interfaces/fsl/model.py
nipype/interfaces/script_templates/feat_ev_custom.tcl

corrected level1design EV parameter substitution

---

nipype/interfaces/freesurfer/preprocess.py

FIX: Typo in private method name

---

nipype/interfaces/fsl/model.py

Related to : https://github.com/nipy/nipype/pull/1999
It has to be int(bool()): fsl reads 0's or 1's.

Add int to temporal derivatives

---

nipype/interfaces/fsl/model.py

https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;e95b4651.1501
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4289914/

added migp options

---

nipype/interfaces/io.py

freesurfersource did not receive aseg and wmparc stats properly. this address the issue.

fix: retrieve aseg and wmparc stats properly

---

nipype/interfaces/fsl/preprocess.py
nipype/interfaces/fsl/tests/test_preprocess.py

adding the missing coma in fnirt

fix to #2124

---

nipype/pipeline/engine/nodes.py

Improve logging message

---

nipype/interfaces/afni/tests/test_auto_Refit.py
nipype/interfaces/afni/utils.py

adding a parameter to `afni.Refit`

add xyzscale to AFNI 3drefit

---

CHANGES

Make a distinction between release candidates and the final release.

Update CHANGES [skip ci]

---

nipype/interfaces/afni/tests/test_auto_Unifize.py
nipype/interfaces/afni/utils.py

add option `-rbt` for AFNI `3dUnifize`

Afni unifize rbt

---

nipype/algorithms/confounds.py
nipype/algorithms/metrics.py

using `matplotlib_backend` from `utils.config.py`

setting matplotlib backend, closes #366

---

.zenodo.json

- Adds Elizabeth DuPre as contributor

[ENH] Update zenodo

---

nipype/interfaces/base.py

- remove `-L` flag from ldd call

fix: remove ldd flag

---

nipype/interfaces/diffusion_toolkit/dti.py
nipype/interfaces/diffusion_toolkit/tests/test_auto_DTITracker.py

I took #1653 and updated the auto test

updating dti.py (cont #1653)

---

doc/quickstart.rst

doc: add porcupine to quickstart

---

doc/users/saving_workflows.rst
nipype/workflows/smri/ants/ANTSBuildTemplate.py
nipype/workflows/smri/ants/antsRegistrationBuildTemplate.py

Revert "[FIX,WIP] Setting inputs.ignore_exception"

---

nipype/utils/filemanip.py

Check some hard-coded md5 sums to make sure that #2404 does not come from faulty hash calculations.

[ENH] Add tests to ``hash_files``

---

nipype/pipeline/plugins/slurmgraph.py

Replacement for orphaned #1263, which is too old a branch for me to push to.

FIX: Default value for sbatch_args (SLURMGraph)

---

nipype/interfaces/mrtrix3/preprocess.py
nipype/interfaces/mrtrix3/tests/test_auto_ResponseSD.py

Fixes #2408.
Changes proposed in this pull request:
- Change `algorithm` argument position

[FIX] Fix issue #2408

---

.zenodo.json

I added myself as contributor after reporting issue https://github.com/nipy/nipype/issues/2435 and PR https://github.com/nipy/nipype/pull/2460
Pull-request guidelines (Remove this section after reading):
1. If you would like to list yourself as a Nipype contributor and your name is not mentioned please modify .zenodo.json file.
2. By submitting this request you acknowledge that your contributions are available under the Apache 2 license.
3. Use a descriptive prefix for your PR: ENH (enhancement), FIX, TST, DOC, STY, REF (refactor), WIP (Work in progress)
4. The person who accepts/merges your PR will include an update to the CHANGES file: prefix: description (URL of pull request)
5. Run `make check-before-commit` before submitting the PR.
----- REMOVE TILL HERE -----
Fixes # .
Changes …

Adding new entry in the contributors list

---

doc/users/index.rst

DOC: Add tutorials, porcupine to users TOC

---

nipype/workflows/smri/freesurfer/recon.py

For the sake of the copy-pasters out there, better to use the same variable name throughout
Fixes # .

DOC: use consistent name

---

nipype/interfaces/base/core.py

[STY] Combine split import

---

nipype/pipeline/plugins/lsf.py

[FIX] Change undefined ScriptError on LFS plugin to IOError

---

nipype/interfaces/base/core.py

Fixes what looks like a swapped index.
change indices

[FIX] Indices were swapped for memory and cpu profile data

---

tools/build_interface_docs.py

DOC/FIX: Skip conftest module in API generation

---

.zenodo.json

Relates to #2864.
Add my name to the Zenodo file.

Accept invitation as Zenodo release co-author (see #2864)

---

docker/generate_dockerfiles.sh

tst: fix CI builds

---

nipype/utils/filemanip.py

Addresses https://github.com/nipy/nipype/pull/2985#discussion_r311126456
Fixes # .

ENH: Let ``indirectory`` handle ``nipype.utils.filemanip.Path``

---

nipype/interfaces/tests/test_extra_dcm2nii.py

TST: dcm2niix test fix

---

.zenodo.json

My ORCID was a copy of the "Ziegler, Erik" number

MNT: Fix Dorota Jarecka ORCID

---

nipype/interfaces/base/traits_extension.py

Addresses #3157 in `maint/1.3.x`.

FIX: Move TraitType import, handle API change for NoDefaultSpecified

---

.zenodo.json

Added my affiliation and orcid to my zenodo entry.
Fixes # 
No fix
Changed my zenodo entry.

DOC: Updated .zenodo.json file

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Accidentally closed #3174 by trying to keep master synced with 1.5.0-rc1.post-dev.
Prep for new feature release 1.5.0, targeting release when we can manage it.
Require merge or postponement decision on all issues/PRs in https://github.com/nipy/nipype/milestone/38:
Will try review the open PRs and see if anything is close enough to push on, tomorrow.
No …

REL: 1.5.0

---

nipype/interfaces/ants/tests/test_auto_AI.py
nipype/interfaces/ants/utils.py

FIX: Raise version error when using ``-g`` with ``antsAI`` < 2.3.0

---

.zenodo.json

Updated personal entry with ORCID iD.

Added ORCID iD

---

.circleci/config.yml
.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
doc/users/install.rst
nipype/info.py
tools/feedstock.sh

Release prep for 1.7.1. Aiming for Monday, but if PRs look to be wrapping up, I'm happy to hold off for a couple days to get them in.

REL: 1.7.1

---

.circleci/config.yml
.github/workflows/tests.yml
doc/interfaces.rst
nipype/info.py

MNT: 1.8.0.dev0

---

nipype/interfaces/mrtrix3/preprocess.py

[ENH] Added outputs' generation to DWIBiascorrect interface

---

.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py
tools/update_changes.sh
tools/update_mailmap.sh

Preparation for the 1.8.4 release, to be merged immediately pending tests passing.
Critical fixes in #3501 
* ... Please let me know if you want to try to merge something today.

REL: 1.8.4

---

.github/workflows/tutorials.yml
.mailmap
.zenodo.json
doc/changelog/1.X.X-changelog.rst
nipype/info.py

Preparation for the 1.8.5 release, to be merged as convenient.
* ... Please let me know if you want to try to merge something in.

REL: 1.8.5

---

nipype/interfaces/base/traits_extension.py
nipype/interfaces/semtools/brains/utilities.py

STY: Codespell
